/**
 * Generate Web Dev round CSV imports (100 rows: 50 mcq_exact + 50 rubric_llm).
 *
 *   node scripts/generateWebDevQuestionCsv.js
 *
 * Import each file via data entry with:
 *   roundType: Web Dev, difficulty: medium, roleTags: (per file), evaluationStrategy: (per file)
 */
import dotenv from "dotenv";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.join(__dirname, "data", "generated-interview-imports");

const COMPANY_POOLS = {
  fe: ["Google", "Adobe", "Microsoft", "Flipkart", "Atlassian", "LinkedIn", "Amazon", "Meesho"],
  be: ["Amazon", "Razorpay", "PhonePe", "Atlassian", "Goldman Sachs", "Intuit", "Flipkart", "ThoughtWorks"],
  fs: ["Microsoft", "Google", "Amazon", "Razorpay", "PhonePe", "Adobe", "Flipkart", "Swiggy"],
};

const SRC = {
  mdn: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  react: "https://react.dev/learn",
  node: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick",
  express: "https://expressjs.com/en/guide/routing.html",
  python: "https://docs.python.org/3/tutorial/",
  mongo: "https://www.mongodb.com/docs/manual/core/document/",
  gfg: "https://www.geeksforgeeks.org/javascript-interview-questions-and-answers/",
  rest: "https://restfulapi.net/rest-api-design-tutorial-with-example/",
};

const rubricFor = (criteria, mode = "conceptual") =>
  criteria.map((text, index) => ({
    text,
    category: ["fundamentals", "depth", "tradeoffs", "communication", "best-practices"][index] || "coverage",
    importance: index < 3 ? "mustHave" : "goodToHave",
    expectedAnswerMode: mode,
  }));

const csvEscape = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;
const writeCsv = async (fileName, columns, rows) => {
  const output = [
    columns.map(csvEscape).join(","),
    ...rows.map((row) => columns.map((column) => csvEscape(row[column])).join(",")),
  ].join("\n");
  await fs.writeFile(path.join(outputDir, fileName), `${output}\n`, "utf8");
};

const tagsFor = (pool, index) => {
  const list = COMPANY_POOLS[pool];
  return Array.from({ length: 4 }, (_, i) => list[(index * 3 + i) % list.length]);
};

const normalizeKey = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

// ── Frontend Engineer: React + JavaScript ─────────────────────────────

const frontendMcqs = [
  {
    id: "webdev-fe-mcq-001",
    title: "JavaScript typeof null",
    question: "What does `typeof null` return in JavaScript?",
    topics: ["web-dev", "javascript"],
    subtopics: ["types", "typeof"],
    options: ["'null'", "'object'", "'undefined'", "'number'"],
    answer: "B",
    explanation: "A long-standing quirk: typeof null is 'object'. Use === null to test for null.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-002",
    title: "Event loop order",
    question: "After synchronous code finishes, which typically runs first in the browser?",
    topics: ["web-dev", "javascript"],
    subtopics: ["event-loop", "microtasks"],
    options: ["setTimeout callback", "Microtasks (e.g. promise .then)", "requestAnimationFrame always", "Script load event"],
    answer: "B",
    explanation: "Microtasks drain before the next macrotask (e.g. setTimeout).",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-003",
    title: "Closure capture",
    question: "A loop with `var i` and setTimeout logging `i` prints 5 five times. The fix is:",
    topics: ["web-dev", "javascript"],
    subtopics: ["closure", "scope"],
    options: ["Use let instead of var", "Remove setTimeout", "Use == instead of ===", "Add async to loop"],
    answer: "A",
    explanation: "let is block-scoped; each iteration gets its own binding for closures.",
    source: SRC.gfg,
  },
  {
    id: "webdev-fe-mcq-004",
    title: "Strict equality",
    question: "Which is true in JavaScript?",
    topics: ["web-dev", "javascript"],
    subtopics: ["equality", "coercion"],
    options: ["[] == false is false", "null == undefined is true", "NaN === NaN is true", "'' === 0 is true"],
    answer: "B",
    explanation: "null == undefined is true; NaN is never equal to itself with ===.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-005",
    title: "Promise state",
    question: "Once a Promise is fulfilled or rejected, its state:",
    topics: ["web-dev", "javascript"],
    subtopics: ["promises", "async"],
    options: ["Can change if you call resolve again", "Is immutable", "Resets on catch()", "Becomes pending after then()"],
    answer: "B",
    explanation: "Promise state is settled permanently; later resolve/reject calls are ignored.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-006",
    title: "DOM event propagation",
    question: "Event bubbling means handlers run from:",
    topics: ["web-dev", "javascript"],
    subtopics: ["dom", "events"],
    options: ["Window to target", "Target outward to ancestors", "Only the target element", "Document only"],
    answer: "B",
    explanation: "Bubble phase: target → parent → … → window (unless stopPropagation).",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-007",
    title: "localStorage vs sessionStorage",
    question: "sessionStorage differs from localStorage because data:",
    topics: ["web-dev", "javascript"],
    subtopics: ["storage", "browser"],
    options: ["Is encrypted by default", "Clears when the tab/window session ends", "Cannot store strings", "Is shared across all origins"],
    answer: "B",
    explanation: "sessionStorage is scoped to the browsing session for that tab.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-008",
    title: "React key prop",
    question: "Why does React warn when list items lack stable `key` props?",
    topics: ["web-dev", "react"],
    subtopics: ["keys", "reconciliation"],
    options: ["Keys slow rendering", "Keys help match identity across updates for efficient reorder", "Keys are only for CSS", "Keys replace useState"],
    answer: "B",
    explanation: "Keys identify items so React can preserve state and minimize DOM churn.",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-009",
    title: "Virtual DOM purpose",
    question: "React's reconciliation primarily uses the virtual DOM to:",
    topics: ["web-dev", "react"],
    subtopics: ["virtual-dom", "reconciliation"],
    options: ["Replace the browser entirely", "Batch and compute minimal real DOM updates", "Store server HTML", "Avoid JavaScript"],
    answer: "B",
    explanation: "VDOM diffing reduces expensive direct DOM manipulation.",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-010",
    title: "useState updates",
    question: "Calling setState/setter twice with the same primitive in one event handler in React 18 typically:",
    topics: ["web-dev", "react"],
    subtopics: ["hooks", "state"],
    options: ["Always runs effects twice synchronously", "May batch into one re-render in event handlers", "Throws in strict mode only", "Skips the second update always in production"],
    answer: "B",
    explanation: "React batches state updates in event handlers; functional updates help when depending on prior state.",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-011",
    title: "useEffect dependencies",
    question: "An empty dependency array [] on useEffect means:",
    topics: ["web-dev", "react"],
    subtopics: ["hooks", "useEffect"],
    options: ["Run every render", "Run once after mount (and cleanup on unmount)", "Never run", "Run only on error"],
    answer: "B",
    explanation: "[] runs after initial paint; cleanup runs before unmount and before re-run if deps change.",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-012",
    title: "Controlled input",
    question: "A controlled React input means:",
    topics: ["web-dev", "react"],
    subtopics: ["forms", "controlled-components"],
    options: ["DOM owns the value", "React state is the single source of truth for value", "It cannot use onChange", "It disables validation"],
    answer: "B",
    explanation: "value + onChange tie input to React state.",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-013",
    title: "Props vs state",
    question: "Which is correct?",
    topics: ["web-dev", "react"],
    subtopics: ["props", "state"],
    options: ["Props are mutable by the child", "State is passed from parent only", "Props flow down; state is local unless lifted", "State replaces props in function components"],
    answer: "C",
    explanation: "Props are read-only from parent; state belongs to the component (or lifted parent).",
    source: SRC.react,
  },
  {
    id: "webdev-fe-mcq-014",
    title: "CSS specificity",
    question: "Which selector generally wins if all apply to the same element?",
    topics: ["web-dev", "html-css"],
    subtopics: ["css", "specificity"],
    options: ["Element selector", "Class selector", "Inline style", "Universal selector"],
    answer: "C",
    explanation: "Inline styles beat IDs/classes/elements unless !important overrides.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-015",
    title: "Flexbox main axis",
    question: "In a flex container with flex-direction: row, justify-content aligns items along:",
    topics: ["web-dev", "html-css"],
    subtopics: ["flexbox", "layout"],
    options: ["Cross axis", "Main axis (horizontal here)", "Z-index stack", "Grid tracks"],
    answer: "B",
    explanation: "justify-content aligns on main axis; align-items on cross axis.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-016",
    title: "CORS preflight",
    question: "Browsers send an OPTIONS preflight for cross-origin requests when:",
    topics: ["web-dev", "networks"],
    subtopics: ["cors", "http"],
    options: ["Always for GET", "Certain non-simple methods/headers trigger it", "Only on localhost", "Never for JSON APIs"],
    answer: "B",
    explanation: "Non-simple requests (e.g. custom headers, PUT) trigger preflight.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-mcq-017",
    title: "React.memo purpose",
    question: "React.memo on a component primarily:",
    topics: ["web-dev", "react"],
    subtopics: ["performance", "memo"],
    options: ["Caches fetch results", "Skips re-render if props are shallow-equal", "Replaces useMemo for all hooks", "Fixes key warnings"],
    answer: "B",
    explanation: "memo avoids re-render when props unchanged (shallow compare).",
    source: SRC.react,
  },
];

const frontendRubrics = [
  {
    id: "webdev-fe-rub-001",
    title: "Explain closures",
    question: "Explain JavaScript closures with a practical example (e.g. counter or event handler). When can they cause memory leaks?",
    topics: ["web-dev", "javascript"],
    subtopics: ["closure", "scope"],
    criteria: [
      "Defines closure as function retaining access to outer lexical scope",
      "Gives a concrete code-level or behavioral example",
      "Explains creation at function definition time",
      "Mentions leak scenarios (long-lived refs, detached DOM handlers)",
      "States mitigation (null refs, remove listeners)",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fe-rub-002",
    title: "Event loop mental model",
    question: "Walk through what happens when sync code, a Promise, and setTimeout(0) run in order in the browser.",
    topics: ["web-dev", "javascript"],
    subtopics: ["event-loop", "async"],
    criteria: [
      "Runs synchronous stack first",
      "Drains microtasks before next macrotask",
      "Places setTimeout in macrotask queue",
      "Mentions render/paint timing at high level",
      "Avoids claiming infinite parallel threads in JS",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-003",
    title: "debounce vs throttle",
    question: "When would you use debounce vs throttle on a search input or scroll handler?",
    topics: ["web-dev", "javascript"],
    subtopics: ["performance", "events"],
    criteria: [
      "Defines debounce (wait for pause) vs throttle (rate limit)",
      "Maps search typing to debounce",
      "Maps scroll/resize tracking to throttle where appropriate",
      "Mentions UX and API cost trade-offs",
      "Notes cleanup on unmount in React",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fe-rub-004",
    title: "React reconciliation",
    question: "How does React decide what to update in the DOM when state changes in a list?",
    topics: ["web-dev", "react"],
    subtopics: ["reconciliation", "keys"],
    criteria: [
      "Mentions element type and props diff",
      "Explains role of keys for list identity",
      "Warns against index keys when reorder/filter",
      "Connects to preserving component state",
      "Keeps explanation at fresher-appropriate depth",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-005",
    title: "useEffect pitfalls",
    question: "Describe common mistakes with useEffect (missing deps, stale closures, missing cleanup).",
    topics: ["web-dev", "react"],
    subtopics: ["hooks", "useEffect"],
    criteria: [
      "Explains dependency array purpose",
      "Gives stale closure example and fix (deps or functional update)",
      "Mentions subscriptions/timers need cleanup",
      "Avoids disabling eslint-deps as only answer",
      "Mentions strict mode double-invoke in dev briefly",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-006",
    title: "Lifting state up",
    question: "Two sibling components must share filter state. How do you structure React state?",
    topics: ["web-dev", "react"],
    subtopics: ["state", "architecture"],
    criteria: [
      "Moves shared state to common ancestor",
      "Passes value and updater via props",
      "Avoids duplicating source of truth",
      "Mentions context if prop drilling deep (optional)",
      "Clear data flow direction",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-007",
    title: "Context vs prop drilling",
    question: "When is React Context appropriate vs passing props manually?",
    topics: ["web-dev", "react"],
    subtopics: ["context", "props"],
    criteria: [
      "Context for widely needed stable data (theme, auth user)",
      "Warns context causes broad re-renders if not split/memoized",
      "Props preferred for local/parent-child data",
      "Mentions provider placement",
      "Fresher-safe example (theme or locale)",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-008",
    title: "Accessibility basics",
    question: "What steps make a custom modal dialog more accessible?",
    topics: ["web-dev", "html-css"],
    subtopics: ["accessibility", "a11y"],
    criteria: [
      "Focus trap or return focus on close",
      "aria-modal / role=dialog and labelled title",
      "Keyboard Escape to close",
      "Visible focus indicators",
      "Avoids div-only buttons without roles",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-009",
    title: "CSS Box model",
    question: "Explain content-box vs border-box and why many teams set box-sizing globally.",
    topics: ["web-dev", "html-css"],
    subtopics: ["css", "box-model"],
    criteria: [
      "Defines width including padding/border for border-box",
      "Explains layout surprises with content-box",
      "Mentions universal border-box reset pattern",
      "Connects to responsive layouts",
      "Clear and concise",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-010",
    title: "Fetch error handling",
    question: "Why must you check response.ok when using fetch()? How would you handle errors in UI?",
    topics: ["web-dev", "javascript"],
    subtopics: ["fetch", "http"],
    criteria: [
      "fetch does not reject on 404/500",
      "Check status or response.ok before parsing JSON",
      "try/catch for network failures",
      "User-facing error state in React",
      "Optional retry or toast pattern",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-011",
    title: "SPA vs MPA",
    question: "Compare SPA and multi-page applications for SEO, performance, and complexity.",
    topics: ["web-dev", "javascript"],
    subtopics: ["spa", "architecture"],
    criteria: [
      "SPA: client routing, fewer full reloads",
      "MPA: simpler SEO/history per page traditionally",
      "Mentions SSR/SSG as hybrid (Next.js) at high level",
      "Trade-offs for fresher product teams",
      "Balanced not one-sided",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fe-rub-012",
    title: "useMemo vs useCallback",
    question: "When would you use useMemo or useCallback in React? When is it premature optimization?",
    topics: ["web-dev", "react"],
    subtopics: ["hooks", "performance"],
    criteria: [
      "useMemo caches computed values; useCallback stable function ref",
      "Helps memoized children avoid re-renders",
      "Not needed for every render",
      "Profile/measure before micro-optimizing",
      "Mentions dependency arrays",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-013",
    title: "Prototype chain",
    question: "Explain prototypal inheritance in JavaScript. How does class syntax relate?",
    topics: ["web-dev", "javascript"],
    subtopics: ["prototype", "classes"],
    criteria: [
      "Objects delegate to prototype on property lookup",
      "__proto__ / Object.getPrototypeOf conceptually",
      "class is syntactic sugar over prototypes",
      "Mentions method on prototype vs instance",
      "Avoids confusion with classical inheritance only",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-014",
    title: "Responsive layout",
    question: "How would you build a responsive navbar that collapses on mobile?",
    topics: ["web-dev", "html-css"],
    subtopics: ["responsive", "flexbox"],
    criteria: [
      "Media queries or mobile-first breakpoints",
      "Flex/grid for layout",
      "Accessible toggle button",
      "Touch-friendly targets",
      "Avoids horizontal scroll on small screens",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-015",
    title: "XSS prevention",
    question: "What is XSS and how do React and good frontend practices reduce risk?",
    topics: ["web-dev", "javascript"],
    subtopics: ["security", "xss"],
    criteria: [
      "Defines injecting malicious scripts into rendered pages",
      "React escapes text by default in JSX",
      "Warns on dangerouslySetInnerHTML",
      "Validate/sanitize on server too",
      "Mentions CSP briefly optional",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fe-rub-016",
    title: "Custom hook design",
    question: "Design a useFetch(url) custom hook. What states and cleanup would it expose?",
    topics: ["web-dev", "react"],
    subtopics: ["hooks", "custom-hooks"],
    criteria: [
      "States: loading, data, error",
      "AbortController or ignore flag on unmount/url change",
      "Refetch or dependency on url",
      "Does not fetch in render body without effect",
      "Simple API for components",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fe-rub-017",
    title: "Shadow DOM vs React",
    question: "What is Shadow DOM and when might web components complement a React app?",
    topics: ["web-dev", "javascript"],
    subtopics: ["web-components", "encapsulation"],
    criteria: [
      "Encapsulated DOM/CSS scope",
      "Use cases: design system widgets, third-party embeds",
      "React can render inside or wrap components",
      "Not required for every app",
      "Clear fresher-level scope",
    ],
    source: SRC.mdn,
  },
];

// ── Backend Engineer: Node.js + Python ────────────────────────────────

const backendMcqs = [
  {
    id: "webdev-be-mcq-001",
    title: "Node event loop",
    question: "In Node.js, which phase primarily runs timers scheduled with setTimeout/setInterval?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["event-loop", "timers"],
    options: ["Poll phase", "Timers phase", "Check phase", "Close callbacks only"],
    answer: "B",
    explanation: "Timers phase executes due timer callbacks.",
    source: SRC.node,
  },
  {
    id: "webdev-be-mcq-002",
    title: "Express middleware",
    question: "In Express, middleware functions receive (req, res, next). Calling next() without ending the response:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["express", "middleware"],
    options: ["Always sends 404", "Passes control to the next middleware", "Crashes the process", "Commits a transaction"],
    answer: "B",
    explanation: "next() continues the chain; you must send a response or call next exactly once per path.",
    source: SRC.express,
  },
  {
    id: "webdev-be-mcq-003",
    title: "CommonJS vs ESM",
    question: "Which is valid in Node for ESM modules?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["modules", "esm"],
    options: ["require() in .mjs file", "import from in .mjs or \"type\":\"module\"", "module.exports in .mjs only", "import is browser-only"],
    answer: "B",
    explanation: "ESM uses import/export; package type module or .mjs extension.",
    source: SRC.node,
  },
  {
    id: "webdev-be-mcq-004",
    title: "HTTP status for validation",
    question: "For a REST API, invalid client input (bad JSON field) should usually return:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["rest", "http"],
    options: ["500 Internal Server Error", "404 Not Found", "400 Bad Request", "302 Found"],
    answer: "C",
    explanation: "4xx for client errors; 400 for malformed/invalid input.",
    source: SRC.rest,
  },
  {
    id: "webdev-be-mcq-005",
    title: "JWT structure",
    question: "A JSON Web Token (JWT) consists of:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["jwt", "auth"],
    options: ["Header, payload, signature", "Username and password only", "Session ID in cookie only", "SQL query hash"],
    answer: "A",
    explanation: "JWT is header.payload.signature (base64url segments).",
    source: SRC.rest,
  },
  {
    id: "webdev-be-mcq-006",
    title: "Idempotent HTTP method",
    question: "Which HTTP method is idempotent (repeating should not change outcome beyond first apply)?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["rest", "http"],
    options: ["POST", "PATCH always", "PUT (replacing same resource)", "CONNECT"],
    answer: "C",
    explanation: "PUT replace same URI is idempotent; POST creates are not.",
    source: SRC.rest,
  },
  {
    id: "webdev-be-mcq-007",
    title: "Node streams benefit",
    question: "Readable streams in Node help when:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["streams", "performance"],
    options: ["Loading entire 2GB file into memory at once", "Processing large files chunk-by-chunk", "Replacing Express", "Disabling the event loop"],
    answer: "B",
    explanation: "Streams bound memory while processing large I/O.",
    source: SRC.node,
  },
  {
    id: "webdev-be-mcq-008",
    title: "process.env purpose",
    question: "Twelve-factor apps store secrets and config in:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["config", "env"],
    options: ["Hard-coded in repo", "Environment variables", "Comments only", "Global variables in client bundle"],
    answer: "B",
    explanation: "Config via env; never commit secrets to git.",
    source: SRC.node,
  },
  {
    id: "webdev-be-mcq-009",
    title: "Python list vs tuple",
    question: "Which is true about Python tuples?",
    topics: ["web-dev", "python"],
    subtopics: ["python", "data-structures"],
    options: ["Mutable after creation", "Immutable sequences, often used as keys/records", "Same as JavaScript Array", "Cannot hold mixed types"],
    answer: "B",
    explanation: "Tuples are immutable; lists are mutable.",
    source: SRC.python,
  },
  {
    id: "webdev-be-mcq-010",
    title: "Python GIL (high level)",
    question: "CPython's GIL means for CPU-bound threads on one process:",
    topics: ["web-dev", "python"],
    subtopics: ["python", "concurrency"],
    options: ["True parallel CPU execution on all cores always", "Only one thread executes Python bytecode at a time per process", "No threading allowed", "Replaces asyncio"],
    answer: "B",
    explanation: "GIL limits parallel bytecode; use multiprocessing or native extensions for CPU parallelism.",
    source: SRC.python,
  },
  {
    id: "webdev-be-mcq-011",
    title: "Flask vs Django (fresher)",
    question: "Flask is often chosen over Django when you need:",
    topics: ["web-dev", "python"],
    subtopics: ["flask", "django"],
    options: ["Built-in admin and ORM mandatory", "Minimal microframework you extend yourself", "No HTTP support", "Only async ASGI out of box always"],
    answer: "B",
    explanation: "Flask is lightweight; Django is batteries-included.",
    source: SRC.gfg,
  },
  {
    id: "webdev-be-mcq-012",
    title: "SQL injection fix",
    question: "Best defense against SQL injection in backend code:",
    topics: ["web-dev", "python"],
    subtopics: ["security", "sql"],
    options: ["String concat with escaped quotes only", "Parameterized queries / ORM bindings", "Hide error messages only", "Use GET for all queries"],
    answer: "B",
    explanation: "Prepared statements separate code from data.",
    source: SRC.gfg,
  },
  {
    id: "webdev-be-mcq-013",
    title: "Redis use case",
    question: "Redis is commonly used in backends for:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["redis", "caching"],
    options: ["Primary relational reporting warehouse", "In-memory cache or session store", "Replacing HTTP", "Compiling TypeScript"],
    answer: "B",
    explanation: "Redis: cache, sessions, rate limits, pub/sub.",
    source: SRC.gfg,
  },
  {
    id: "webdev-be-mcq-014",
    title: "async/await in Node",
    question: "await inside an async route handler primarily:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["async", "express"],
    options: ["Blocks the entire server thread pool like Java", "Pauses that async function until Promise settles without blocking the event loop for I/O", "Replaces try/catch", "Runs synchronously on main thread always for CPU work"],
    answer: "B",
    explanation: "Non-blocking I/O; CPU-heavy work still needs worker threads/queues.",
    source: SRC.node,
  },
  {
    id: "webdev-be-mcq-015",
    title: "REST noun URLs",
    question: "Which URL style is most RESTful for listing users?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["rest", "api-design"],
    options: ["GET /getAllUsers", "GET /users", "POST /users/list", "GET /users/action/fetch"],
    answer: "B",
    explanation: "Resources as nouns; HTTP verbs express actions.",
    source: SRC.rest,
  },
  {
    id: "webdev-be-mcq-016",
    title: "Python decorator",
    question: "A Python decorator wraps a function to:",
    topics: ["web-dev", "python"],
    subtopics: ["decorators", "python"],
    options: ["Delete the function", "Add behavior before/after without changing call site syntax", "Convert to tuple", "Disable type hints"],
    answer: "B",
    explanation: "Decorators are higher-order functions (@syntax sugar).",
    source: SRC.python,
  },
  {
    id: "webdev-be-mcq-017",
    title: "Rate limiting",
    question: "API rate limiting primarily protects against:",
    topics: ["web-dev", "nodejs"],
    subtopics: ["security", "rate-limit"],
    options: ["Valid JSON parsing", "Abuse, bursts, and DoS-style traffic", "HTTPS certificates", "CORS preflight only"],
    answer: "B",
    explanation: "Limits unfair usage and stabilizes backend capacity.",
    source: SRC.rest,
  },
];

const backendRubrics = [
  {
    id: "webdev-be-rub-001",
    title: "Design REST API",
    question: "Design CRUD REST endpoints for a `tasks` resource. Include status codes for create, read, update, delete.",
    topics: ["web-dev", "nodejs"],
    subtopics: ["rest", "api-design"],
    criteria: [
      "Resourceful paths (/tasks, /tasks/:id)",
      "Correct verbs GET POST PUT/PATCH DELETE",
      "201 on create, 404 on missing id, 204 or 200 on delete",
      "Consistent error body shape",
      "Versioning or pagination mentioned optional",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-be-rub-002",
    title: "JWT auth flow",
    question: "Explain login with JWT: where tokens are issued, stored, and how refresh might work at high level.",
    topics: ["web-dev", "nodejs"],
    subtopics: ["jwt", "auth"],
    criteria: [
      "Server validates credentials then signs JWT",
      "Client sends Authorization Bearer on requests",
      "Mentions short-lived access + refresh pattern optional",
      "HTTPS and secret/key rotation awareness",
      "Does not store JWT in localStorage without acknowledging XSS trade-off",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-be-rub-003",
    title: "Express error middleware",
    question: "How should global error-handling middleware be registered and what is its signature?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["express", "error-handling"],
    criteria: [
      "Four arguments (err, req, res, next)",
      "Registered after routes",
      "Centralized logging and sanitized client message",
      "Distinguishes operational vs programmer errors lightly",
      "Avoids leaking stack in production",
    ],
    source: SRC.express,
  },
  {
    id: "webdev-be-rub-004",
    title: "Node scalability",
    question: "How can a Node HTTP server scale horizontally and what remains shared state problems?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["scalability", "architecture"],
    criteria: [
      "Multiple instances behind load balancer",
      "Sticky sessions or external session store if needed",
      "Stateless app design preferred",
      "WebSockets/pub-sub may need Redis adapter",
      "Database as coordination point",
    ],
    source: SRC.node,
  },
  {
    id: "webdev-be-rub-005",
    title: "Caching strategy",
    question: "When cache API responses in Redis, how do you handle cache invalidation after an update?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["redis", "caching"],
    criteria: [
      "TTL as simple strategy",
      "Invalidate keys on write (delete or update cache)",
      "Cache-aside pattern description",
      "Mentions stampede/thundering herd lightly optional",
      "Key naming convention",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-be-rub-006",
    title: "Python asyncio vs threads",
    question: "When choose asyncio vs threading for a Python web service doing many DB calls?",
    topics: ["web-dev", "python"],
    subtopics: ["asyncio", "concurrency"],
    criteria: [
      "Async good for many concurrent I/O waits",
      "Threads blocked by GIL for CPU but I/O releases GIL",
      "Async requires async-compatible drivers",
      "Avoid mixing blocking calls in async loop",
      "Practical recommendation for I/O-heavy API",
    ],
    source: SRC.python,
  },
  {
    id: "webdev-be-rub-007",
    title: "Input validation",
    question: "Where should you validate API input in a Node + Express stack?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["validation", "security"],
    criteria: [
      "Validate at boundary (middleware/schema)",
      "Reject early with 400",
      "Schema libs or manual checks",
      "Never trust client-only validation",
      "Sanitize for XSS if reflecting input optional",
    ],
    source: SRC.express,
  },
  {
    id: "webdev-be-rub-008",
    title: "Database indexing",
    question: "A query filtering users by email is slow at scale. What indexing advice do you give?",
    topics: ["web-dev", "python"],
    subtopics: ["database", "indexing"],
    criteria: [
      "Index on email column if selective",
      "Explain lookup vs full scan concept",
      "Unique index if emails unique",
      "Watch write amplification",
      "Verify with EXPLAIN optional",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-be-rub-009",
    title: "File upload handling",
    question: "Outline safe handling of file uploads in a backend API (size, type, storage).",
    topics: ["web-dev", "nodejs"],
    subtopics: ["uploads", "security"],
    criteria: [
      "Limit size and MIME/extension allowlist",
      "Store outside web root or use object storage",
      "Randomize filenames",
      "Scan/async virus scan optional mention",
      "Do not execute uploaded content",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-be-rub-010",
    title: "Logging and observability",
    question: "What would you log for each API request in production without leaking secrets?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["logging", "observability"],
    criteria: [
      "Request id, method, path, status, latency",
      "Structured JSON logs",
      "Redact tokens/passwords",
      "Correlation across services optional",
      "Log levels error vs info",
    ],
    source: SRC.node,
  },
  {
    id: "webdev-be-rub-011",
    title: "Webhooks design",
    question: "A payment provider sends webhooks to your server. How do you verify and process them safely?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["webhooks", "security"],
    criteria: [
      "Verify signature/HMAC with shared secret",
      "Idempotent processing (store event ids)",
      "Return 200 quickly; async work in queue optional",
      "Retry-safe handlers",
      "HTTPS only",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-be-rub-012",
    title: "ORM N+1 problem",
    question: "Explain the N+1 query problem and one fix in an ORM context.",
    topics: ["web-dev", "python"],
    subtopics: ["orm", "database"],
    criteria: [
      "1 query for list + N for related entities",
      "Fix: eager loading/join/select_related/prefetch",
      "Impact on latency at scale",
      "Measure before optimizing",
      "Clear example domain (posts + comments)",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-be-rub-013",
    title: "Environment parity",
    question: "How do dev/staging/prod differ for config and what breaks when they diverge?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["devops", "config"],
    criteria: [
      "Env-specific URLs, keys, feature flags",
      "Parity reduces 'works on my machine'",
      "Separate databases and buckets",
      "Migrations tested in staging",
      "Secrets manager not committed files",
    ],
    source: SRC.node,
  },
  {
    id: "webdev-be-rub-014",
    title: "Pagination API",
    question: "Design cursor vs offset pagination for a feed API. Trade-offs?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["api-design", "pagination"],
    criteria: [
      "Offset simple but slow/ inconsistent on live data",
      "Cursor stable for large feeds",
      "Return next cursor token",
      "Limit page size caps",
      "Document sort order",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-be-rub-015",
    title: "Python virtualenv",
    question: "Why use virtual environments and requirements.txt/pyproject in Python projects?",
    topics: ["web-dev", "python"],
    subtopics: ["python", "packaging"],
    criteria: [
      "Isolate dependencies per project",
      "Reproducible installs",
      "Avoid global site-packages conflicts",
      "Pin versions for production",
      "venv + pip install -r",
    ],
    source: SRC.python,
  },
  {
    id: "webdev-be-rub-016",
    title: "Graceful shutdown",
    question: "How should a Node server shut down gracefully on SIGTERM in Kubernetes?",
    topics: ["web-dev", "nodejs"],
    subtopics: ["nodejs", "devops"],
    criteria: [
      "Stop accepting new connections",
      "Drain in-flight requests with timeout",
      "Close DB pools",
      "Exit process after deadline",
      "Health check fails when draining optional",
    ],
    source: SRC.node,
  },
];

// ── Full Stack Engineer: Vanilla JS + MERN + MEAN ─────────────────────

const fullstackMcqs = [
  {
    id: "webdev-fs-mcq-001",
    title: "MERN stack letter",
    question: "In MERN, the document database is:",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "stack"],
    options: ["MySQL", "MongoDB", "MariaDB", "Memcached"],
    answer: "B",
    explanation: "MERN: MongoDB, Express, React, Node.",
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-mcq-002",
    title: "MEAN Angular",
    question: "MEAN stack replaces React with:",
    topics: ["web-dev", "mean"],
    subtopics: ["angular", "stack"],
    options: ["Vue", "Angular", "Svelte", "Next.js only"],
    answer: "B",
    explanation: "MEAN: MongoDB, Express, Angular, Node.",
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-mcq-003",
    title: "JSON vs BSON",
    question: "MongoDB stores documents internally primarily as:",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "data"],
    options: ["CSV", "BSON (binary JSON-like)", "XML", "Plain text SQL"],
    answer: "B",
    explanation: "BSON extends JSON types (e.g. Date, ObjectId).",
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-mcq-004",
    title: "mongoose role",
    question: "Mongoose in a MERN app is mainly used to:",
    topics: ["web-dev", "mern"],
    subtopics: ["mongoose", "schema"],
    options: ["Bundle React", "Define schemas/models and validate MongoDB documents", "Replace Express", "Compile Sass"],
    answer: "B",
    explanation: "ODM layer: schemas, validation, queries.",
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-mcq-005",
    title: "CORS in full stack",
    question: "React on localhost:3000 calling API on localhost:5000 fails without:",
    topics: ["web-dev", "fullstack"],
    subtopics: ["cors", "mern"],
    options: ["Same port only", "Server CORS headers or dev proxy", "Deleting JWT", "Using SQL only"],
    answer: "B",
    explanation: "Cross-origin browser requests need CORS or proxy in dev.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fs-mcq-006",
    title: "HTTP-only cookie",
    question: "Storing session id in HttpOnly cookie helps reduce:",
    topics: ["web-dev", "fullstack"],
    subtopics: ["auth", "security"],
    options: ["SQL injection", "XSS stealing token via document.cookie", "DNS failures", "CSS bugs"],
    answer: "B",
    explanation: "HttpOnly cookies not readable by JS; mitigates some XSS token theft.",
    source: SRC.rest,
  },
  {
    id: "webdev-fs-mcq-007",
    title: "Vanilla DOM query",
    question: "Selecting the first element with id `submit` in vanilla JS:",
    topics: ["web-dev", "vanilla-js"],
    subtopics: ["dom", "selectors"],
    options: ["document.query('submit')", "document.getElementById('submit')", "window.#submit", "React.findDOMNode only"],
    answer: "B",
    explanation: "getElementById or querySelector('#submit').",
    source: SRC.mdn,
  },
  {
    id: "webdev-fs-mcq-008",
    title: "fetch credentials",
    question: "To send cookies on cross-origin fetch from SPA when server allows credentials:",
    topics: ["web-dev", "vanilla-js"],
    subtopics: ["fetch", "cookies"],
    options: ["credentials: 'omit' always", "credentials: 'include' and Access-Control-Allow-Credentials", "Only WebSocket", "Disable HTTPS"],
    answer: "B",
    explanation: "Both client credentials mode and server CORS credential header required.",
    source: SRC.mdn,
  },
  {
    id: "webdev-fs-mcq-009",
    title: "Express static files",
    question: "In production MERN, React build is often served by:",
    topics: ["web-dev", "mern"],
    subtopics: ["express", "deployment"],
    options: ["MongoDB", "Express static middleware or CDN", "Mongoose only", "Python Flask only"],
    answer: "B",
    explanation: "express.static('build') or CDN for assets; API on same or separate host.",
    source: SRC.express,
  },
  {
    id: "webdev-fs-mcq-010",
    title: "ObjectId purpose",
    question: "MongoDB ObjectId is primarily:",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "objectid"],
    options: ["User password hash", "Unique document identifier", "JWT signature", "CSS class"],
    answer: "B",
    explanation: "Default _id type; unique in collection.",
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-mcq-011",
    title: "Angular dependency injection",
    question: "In MEAN/Angular, dependency injection provides:",
    topics: ["web-dev", "mean"],
    subtopics: ["angular", "di"],
    options: ["CSS minification", "Shared services without manual singleton wiring", "Mongo queries only", "Node cluster mode"],
    answer: "B",
    explanation: "DI injects services into components/constructors.",
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-mcq-012",
    title: "RESTful create",
    question: "Creating a document via MERN API typically uses:",
    topics: ["web-dev", "mern"],
    subtopics: ["rest", "crud"],
    options: ["GET /api/items/create", "POST /api/items with JSON body", "DELETE /api/items", "OPTIONS only"],
    answer: "B",
    explanation: "POST to collection URL with body; 201 + Location optional.",
    source: SRC.rest,
  },
  {
    id: "webdev-fs-mcq-013",
    title: "dotenv purpose",
    question: "In a MERN repo, dotenv on the server loads:",
    topics: ["web-dev", "mern"],
    subtopics: ["config", "env"],
    options: ["React components", "Environment variables from .env into process.env", "Mongo sharding rules", "Browser localStorage"],
    answer: "B",
    explanation: "Server-side config; never expose secrets in React REACT_APP unless public by design.",
    source: SRC.node,
  },
  {
    id: "webdev-fs-mcq-014",
    title: "Aggregation pipeline",
    question: "MongoDB aggregation is used to:",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "aggregation"],
    options: ["Compile React", "Transform and compute on documents in stages ($match, $group)", "Replace Express routing", "Encrypt JWT"],
    answer: "B",
    explanation: "Pipeline stages process documents server-side.",
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-mcq-015",
    title: "Axios interceptors",
    question: "Axios response interceptors are useful to:",
    topics: ["web-dev", "fullstack"],
    subtopics: ["axios", "auth"],
    options: ["Style CSS", "Attach tokens globally or refresh on 401 centrally", "Run Mongo migrations", "Replace Redux always"],
    answer: "B",
    explanation: "Centralize auth headers and error handling for API client.",
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-mcq-016",
    title: "Same-origin policy",
    question: "Same-origin policy restricts:",
    topics: ["web-dev", "vanilla-js"],
    subtopics: ["browser", "security"],
    options: ["Server CPU usage", "How documents from one origin access another origin's data", "npm installs", "Git pushes"],
    answer: "B",
    explanation: "Browser isolates origins; CORS is controlled relaxation.",
    source: SRC.mdn,
  },
];

const fullstackRubrics = [
  {
    id: "webdev-fs-rub-001",
    title: "MERN auth end-to-end",
    question: "Describe login flow in MERN: React form → API → MongoDB → token/cookie back to client.",
    topics: ["web-dev", "mern"],
    subtopics: ["auth", "fullstack"],
    criteria: [
      "Client POST credentials to /api/login",
      "Server hashes password compare, issues JWT or session",
      "Protected routes verify token middleware",
      "Client stores token safely (cookie HttpOnly or memory trade-offs)",
      "Logout and expiry handling mentioned",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-fs-rub-002",
    title: "Project structure",
    question: "How would you folder-structure a small MERN capstone (client/server, env, routes)?",
    topics: ["web-dev", "mern"],
    subtopics: ["architecture", "project-structure"],
    criteria: [
      "Separate client and server or monorepo clarity",
      "Routes/controllers/models split on server",
      "React components/pages/services on client",
      "Env samples documented",
      "Shared types optional mention",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-003",
    title: "Deploy MERN",
    question: "Outline deploying MERN: MongoDB Atlas, Node API, React static hosting.",
    topics: ["web-dev", "mern"],
    subtopics: ["deployment", "devops"],
    criteria: [
      "Atlas connection string in server env",
      "API on Render/Railway/EC2 etc.",
      "React build to CDN/Vercel/Netlify or same host",
      "CORS production origins configured",
      "HTTPS everywhere",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-004",
    title: "State management choice",
    question: "When use React Context vs Redux/Zustand in a MERN dashboard?",
    topics: ["web-dev", "mern"],
    subtopics: ["state", "react"],
    criteria: [
      "Local/useState for component UI",
      "Context for moderate global (auth theme)",
      "Redux/Zustand for complex shared async state",
      "Avoid over-engineering small apps",
      "Server state libraries optional (React Query)",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fs-rub-005",
    title: "Schema design Mongo",
    question: "Embed comments inside a post document vs separate collection—trade-offs?",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "schema-design"],
    criteria: [
      "Embed: fast read together, document size limit",
      "Reference: flexible, many comments, join/query cost",
      "Choose by access pattern",
      "Mentions 16MB doc limit for heavy embed",
      "Indexing referenced fields",
    ],
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-rub-006",
    title: "MEAN data binding",
    question: "Explain one-way vs two-way binding conceptually (Angular) vs React's model.",
    topics: ["web-dev", "mean"],
    subtopics: ["angular", "react"],
    criteria: [
      "React: props down, events up (one-way data flow)",
      "Angular historically two-way with [(ngModel)] sugar",
      "Predictability vs convenience trade-off",
      "Does not need Angular syntax mastery",
      "Compares at architecture level",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-007",
    title: "Vanilla JS todo app",
    question: "Build a todo list without frameworks: how store todos and re-render list?",
    topics: ["web-dev", "vanilla-js"],
    subtopics: ["dom", "state"],
    criteria: [
      "In-memory array or localStorage persistence",
      "Create DOM nodes or innerHTML with caution",
      "Event delegation on list optional",
      "Separate render function from data mutations",
      "XSS awareness if using user text",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fs-rub-008",
    title: "API error UX",
    question: "User submits form; API returns 422 validation errors. How should full stack handle display?",
    topics: ["web-dev", "fullstack"],
    subtopics: ["ux", "validation"],
    criteria: [
      "Server returns structured field errors",
      "Client maps errors to inputs",
      "Loading/disabled submit state",
      "Generic fallback toast",
      "No silent failures",
    ],
    source: SRC.rest,
  },
  {
    id: "webdev-fs-rub-009",
    title: "WebSocket use case",
    question: "When add WebSockets to a MERN app instead of polling?",
    topics: ["web-dev", "mern"],
    subtopics: ["websocket", "realtime"],
    criteria: [
      "Real-time chat, notifications, live scores",
      "Lower latency than poll",
      "Fallback/long polling mention optional",
      "Auth on socket connection",
      "Scale with Redis pub/sub optional",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-010",
    title: "CSRF vs XSS full stack",
    question: "Differentiate CSRF and XSS and one mitigation for each in a cookie-session app.",
    topics: ["web-dev", "fullstack"],
    subtopics: ["security", "csrf", "xss"],
    criteria: [
      "XSS: inject script; escape output, CSP, HttpOnly cookies",
      "CSRF: forged requests; SameSite cookies, CSRF tokens",
      "JWT in header shifts some CSRF risk",
      "HTTPS required",
      "Clear definitions",
    ],
    source: SRC.mdn,
  },
  {
    id: "webdev-fs-rub-011",
    title: "Image upload feature",
    question: "User profile photo upload: outline client and server steps in MERN.",
    topics: ["web-dev", "mern"],
    subtopics: ["uploads", "fullstack"],
    criteria: [
      "Client FormData multipart",
      "Server multer/busboy size limits",
      "Store S3/Cloudinary URL in Mongo user doc",
      "Return URL to client for avatar display",
      "Validate MIME type",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-012",
    title: "Optimistic UI",
    question: "Implement optimistic like button in React calling MERN API.",
    topics: ["web-dev", "mern"],
    subtopics: ["react", "ux"],
    criteria: [
      "Update UI before server ack",
      "Rollback on failure",
      "Disable double submit",
      "Sync with server response idempotency",
      "Loading state optional",
    ],
    source: SRC.react,
  },
  {
    id: "webdev-fs-rub-013",
    title: "Environment variables split",
    question: "Which env vars belong on React client vs Node server in MERN?",
    topics: ["web-dev", "mern"],
    subtopics: ["config", "security"],
    criteria: [
      "Client: public API URL only (REACT_APP_*)",
      "Server: DB URI, JWT secret, API keys",
      "Never expose secrets in bundle",
      "Different .env files",
      "Build-time vs runtime awareness",
    ],
    source: SRC.node,
  },
  {
    id: "webdev-fs-rub-014",
    title: "Indexing for MERN query",
    question: "App queries orders by userId and sort by createdAt. What Mongo indexes?",
    topics: ["web-dev", "mern"],
    subtopics: ["mongodb", "indexing"],
    criteria: [
      "Compound index { userId: 1, createdAt: -1 }",
      "Matches filter + sort",
      "Explain slow queries",
      "Avoid over-indexing writes",
      "Unique indexes where needed",
    ],
    source: SRC.mongo,
  },
  {
    id: "webdev-fs-rub-015",
    title: "Monorepo vs split repos",
    question: "Trade-offs monorepo vs separate client/server repos for campus MERN project.",
    topics: ["web-dev", "fullstack"],
    subtopics: ["architecture", "tooling"],
    criteria: [
      "Monorepo: shared types, atomic commits",
      "Split: independent deploy CI",
      "Team size and release cadence",
      "Tooling (npm workspaces) optional",
      "Practical recommendation",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-016",
    title: "Testing pyramid web",
    question: "What tests would you write for a MERN todo API and React UI?",
    topics: ["web-dev", "mern"],
    subtopics: ["testing", "quality"],
    criteria: [
      "Unit tests for utils and reducers",
      "Integration/supertest for API routes",
      "Component tests for critical UI",
      "E2E sparingly for happy path",
      "Mock external services",
    ],
    source: SRC.gfg,
  },
  {
    id: "webdev-fs-rub-017",
    title: "Version API",
    question: "How version a breaking REST change without breaking mobile/web clients?",
    topics: ["web-dev", "fullstack"],
    subtopics: ["api-design", "versioning"],
    criteria: [
      "/v1 vs /v2 or Accept header versioning",
      "Deprecate v1 with timeline",
      "Document changelog",
      "Backward compatible fields when possible",
      "Client feature detection optional",
    ],
    source: SRC.rest,
  },
];

// ── Validate counts ───────────────────────────────────────────────────

const counts = {
  feMcq: frontendMcqs.length,
  feRub: frontendRubrics.length,
  beMcq: backendMcqs.length,
  beRub: backendRubrics.length,
  fsMcq: fullstackMcqs.length,
  fsRub: fullstackRubrics.length,
};
const totalMcq = counts.feMcq + counts.beMcq + counts.fsMcq;
const totalRub = counts.feRub + counts.beRub + counts.fsRub;
if (totalMcq !== 50 || totalRub !== 50) {
  throw new Error(`Expected 50+50 rows, got mcq=${totalMcq} rubric=${totalRub} ${JSON.stringify(counts)}`);
}

const rubricColumns = [
  "questionId",
  "title",
  "question",
  "companyTags",
  "topics",
  "subtopics",
  "url",
  "rubric",
  "source",
  "verified",
  "qualityScore",
];
const mcqColumns = [
  "questionId",
  "title",
  "question",
  "companyTags",
  "topics",
  "subtopics",
  "url",
  "optionA",
  "optionB",
  "optionC",
  "optionD",
  "correctOptionId",
  "explanation",
  "source",
  "verified",
  "qualityScore",
];

const mapMcqRow = (item, pool, index) => ({
  questionId: item.id,
  title: item.title,
  question: item.question,
  companyTags: tagsFor(pool, index).join("|"),
  topics: item.topics.join("|"),
  subtopics: item.subtopics.join("|"),
  url: item.source,
  optionA: item.options[0],
  optionB: item.options[1],
  optionC: item.options[2],
  optionD: item.options[3],
  correctOptionId: item.answer,
  explanation: item.explanation,
  source: "public_interview_pattern_curated",
  verified: "false",
  qualityScore: "0.9",
});

const mapRubricRow = (item, pool, index) => ({
  questionId: item.id,
  title: item.title,
  question: item.question,
  companyTags: tagsFor(pool, index).join("|"),
  topics: item.topics.join("|"),
  subtopics: item.subtopics.join("|"),
  url: item.source,
  rubric: JSON.stringify(rubricFor(item.criteria)),
  source: "public_interview_pattern_curated",
  verified: "false",
  qualityScore: "0.9",
});

const files = [
  {
    name: "webdev-fe-medium-mcq-17.csv",
    roleTag: "Frontend Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "mcq_exact",
    rows: frontendMcqs.map((item, i) => mapMcqRow(item, "fe", i)),
  },
  {
    name: "webdev-fe-medium-rubric-17.csv",
    roleTag: "Frontend Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "rubric_llm",
    rows: frontendRubrics.map((item, i) => mapRubricRow(item, "fe", i)),
  },
  {
    name: "webdev-be-medium-mcq-17.csv",
    roleTag: "Backend Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "mcq_exact",
    rows: backendMcqs.map((item, i) => mapMcqRow(item, "be", i)),
  },
  {
    name: "webdev-be-medium-rubric-16.csv",
    roleTag: "Backend Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "rubric_llm",
    rows: backendRubrics.map((item, i) => mapRubricRow(item, "be", i)),
  },
  {
    name: "webdev-fs-medium-mcq-16.csv",
    roleTag: "Full Stack Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "mcq_exact",
    rows: fullstackMcqs.map((item, i) => mapMcqRow(item, "fs", i)),
  },
  {
    name: "webdev-fs-medium-rubric-17.csv",
    roleTag: "Full Stack Engineer",
    roundType: "Web Dev",
    evaluationStrategy: "rubric_llm",
    rows: fullstackRubrics.map((item, i) => mapRubricRow(item, "fs", i)),
  },
];

await fs.mkdir(outputDir, { recursive: true });
for (const file of files) {
  const columns = file.evaluationStrategy === "mcq_exact" ? mcqColumns : rubricColumns;
  await writeCsv(file.name, columns, file.rows);
}

const allItems = [
  ...frontendMcqs,
  ...frontendRubrics,
  ...backendMcqs,
  ...backendRubrics,
  ...fullstackMcqs,
  ...fullstackRubrics,
];

const summary = {
  outputDir,
  totalRows: allItems.length,
  mcqRows: totalMcq,
  rubricRows: totalRub,
  files: files.map(({ name, roleTag, roundType, evaluationStrategy, rows }) => ({
    name,
    roleTag,
    roundType,
    evaluationStrategy,
    difficulty: "medium",
    rows: rows.length,
  })),
  importHint:
    "Upload each CSV separately with matching role, round Web Dev, difficulty medium, and evaluation type.",
};

if (process.env.MONGO_URI) {
  const mongoose = (await import("mongoose")).default;
  const InterviewQuestion = (await import("../models/InterviewQuestion.js")).default;
  const CompanyStatic = (await import("../models/CompanyStatic.js")).default;
  await mongoose.connect(
    process.env.MONGO_URI,
    process.env.MONGODB_DB_NAME ? { dbName: process.env.MONGODB_DB_NAME } : undefined
  );

  const existing = await InterviewQuestion.find({}, { questionId: 1, title: 1, question: 1 }).lean();
  const knownCompanies = new Set(
    (await CompanyStatic.find({}, { name: 1 }).lean()).map((c) => c.name)
  );

  const existingIds = new Set(existing.map((row) => row.questionId));
  const existingTitleKeys = new Set(existing.map((row) => normalizeKey(row.title)));
  const existingQuestionKeys = new Set(
    existing.map((row) => normalizeKey(String(row.question || "").slice(0, 120)))
  );

  const unknownCompanies = new Set();
  for (const file of files) {
    for (const row of file.rows) {
      for (const company of String(row.companyTags || "").split("|")) {
        const name = company.trim();
        if (name && !knownCompanies.has(name)) unknownCompanies.add(name);
      }
    }
  }

  summary.dbDedupe = {
    duplicateIds: allItems.filter((item) => existingIds.has(item.id)).map((item) => item.id),
    duplicateTitles: allItems.filter((item) => existingTitleKeys.has(normalizeKey(item.title))).map((item) => item.title),
    duplicateQuestionPrefixes: allItems
      .filter((item) => existingQuestionKeys.has(normalizeKey(String(item.question).slice(0, 120))))
      .map((item) => item.id),
    unknownCompanies: [...unknownCompanies],
  };

  if (
    summary.dbDedupe.duplicateIds.length ||
    summary.dbDedupe.duplicateTitles.length ||
    summary.dbDedupe.duplicateQuestionPrefixes.length ||
    summary.dbDedupe.unknownCompanies.length
  ) {
    console.error(JSON.stringify(summary, null, 2));
    await mongoose.disconnect();
    process.exit(1);
  }
  await mongoose.disconnect();
}

console.log(JSON.stringify(summary, null, 2));
