import dotenv from "dotenv";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.join(__dirname, "data", "generated-interview-imports");

/** Verified semiconductor + product-hardware companies in CompanyStatic */
const COMPANIES = {
  semi: [
    "Texas Instruments", "ARM", "Qualcomm", "Analog Devices", "Nvidia", "AMD",
    "Micron Semiconductors", "Infineon", "NXP", "Marvell Technology", "Samsung",
    "Global Foundries", "Renesas Electronics", "Skyworks", "SignalChip",
    "Ascent Circuits", "Tejas Networks", "Microchip",
  ],
};

const SOURCES = {
  digital: "https://www.geeksforgeeks.org/digital-electronics-logic-design-tutorials/",
  vlsi: "https://www.geeksforgeeks.org/vlsi-design-tutorial/",
  verilog: "https://www.chipverify.com/verilog/verilog-tutorial",
  semi: "https://www.geeksforgeeks.org/semiconductor-devices/",
  hr: "https://www.geeksforgeeks.org/hr-interview-questions/",
};

const q = (id, title, question, topics, subtopics, source, criteria, mode = "design") => ({
  id, title, question, topics, subtopics, source, criteria, mode,
});

const h = (id, title, question, topics, subtopics, source, criteria, signals) => ({
  id, title, question, topics, subtopics, source, criteria, signals,
});

const m = (id, title, question, topics, subtopics, source, options, answer, explanation) => ({
  id, title, question, topics, subtopics, source, options, answer, explanation,
});

// ── Circuit Design (50) — most common fresher VLSI oral/written design questions ──
const circuitQuestions = [
  q("vlsi-circ-med-001", "Implement 2:1 MUX",
    "Implement a 2:1 multiplexer using basic logic gates. Explain the truth table and gate-level diagram.",
    ["digital-logic", "combinational"], ["mux", "gates", "truth-table"], SOURCES.digital,
    ["Provides correct truth table for select and data inputs", "Draws or describes valid gate-level implementation", "Explains how select line routes one input to output", "Mentions propagation delay or fan-out briefly", "Uses clear notation and no floating outputs"]),
  q("vlsi-circ-med-002", "4:1 MUX from 2:1 MUX",
    "Design a 4:1 multiplexer using only 2:1 multiplexers. How many 2:1 blocks do you need?",
    ["digital-logic", "combinational"], ["mux", "hierarchy"], SOURCES.digital,
    ["Uses three 2:1 MUXes in a tree structure", "Explains select line decoding for four inputs", "Shows correct connectivity without input conflicts", "States total block count and reasoning", "Verifies all input combinations"]),
  q("vlsi-circ-med-003", "Full adder from half adders",
    "Design a full adder using two half adders and an OR gate. Explain carry propagation.",
    ["digital-logic", "arithmetic"], ["full-adder", "half-adder", "carry"], SOURCES.digital,
    ["Correct sum and carry equations", "Shows half-adder cascade structure", "Explains carry-in and carry-out behavior", "Traces at least one input combination", "Notes extension to multi-bit adders"]),
  q("vlsi-circ-med-004", "K-map minimization",
    "Minimize the Boolean function F(A,B,C) = Σ(1,3,5,7) using a 3-variable K-map.",
    ["digital-logic", "boolean-algebra"], ["k-map", "minimization"], SOURCES.digital,
    ["Draws or describes correct K-map grouping", "Produces minimal SOP expression", "Uses largest valid groups and handles don't-cares if any", "Shows final simplified equation", "Checks against truth table"]),
  q("vlsi-circ-med-005", "D latch versus D flip-flop",
    "Explain the difference between a D latch and a positive-edge-triggered D flip-flop. When is each used?",
    ["sequential-logic", "timing"], ["latch", "flip-flop", "edge-trigger"], SOURCES.digital,
    ["States level-sensitive vs edge-triggered behavior", "Explains transparent window problem in latches", "Notes metastability risk with asynchronous inputs to FF", "Gives appropriate use case for each", "Mentions clock signal role clearly"]),
  q("vlsi-circ-med-006", "Synchronous reset",
    "Why is synchronous reset generally preferred over asynchronous reset in RTL design?",
    ["sequential-logic", "rtl"], ["reset", "synchronous", "timing"], SOURCES.verilog,
    ["Explains reset removal relative to clock edge", "Notes timing analysis and STA simplicity with sync reset", "Mentions async reset metastability or recovery/removal issues", "Acknowledges trade-offs such as reset latency", "Connects to synthesis and DFT considerations"]),
  q("vlsi-circ-med-007", "Mod-6 counter",
    "Design a mod-6 counter using flip-flops. What happens if you use only a mod-8 counter without correction?",
    ["sequential-logic", "counters"], ["mod-counter", "flip-flop"], SOURCES.digital,
    ["Uses sufficient flip-flops and feedback for state 101 skip or equivalent", "Lists state transition table for 0–5", "Explains illegal states if uncorrected mod-8 used", "Mentions reset to known state", "Verifies count sequence"]),
  q("vlsi-circ-med-008", "FSM Mealy vs Moore",
    "Compare Mealy and Moore finite state machines. Which has shorter latency to output change?",
    ["fsm", "digital-design"], ["mealy", "moore", "latency"], SOURCES.digital,
    ["Defines output dependence on state vs state+input", "States Mealy can react in same cycle as input change", "Notes Moore output is stable during state", "Discusses encoding and timing implications", "Gives simple example such as sequence detector"]),
  q("vlsi-circ-med-009", "Sequence detector 1011",
    "Outline the FSM states needed to detect overlapping sequence 1011 in a serial bit stream.",
    ["fsm", "digital-design"], ["sequence-detector", "overlapping"], SOURCES.digital,
    ["Defines states tracking progress through 1-0-1-1 pattern", "Handles overlapping matches correctly", "Specifies transitions on 0 and 1 inputs", "Indicates output assertion on final bit", "Mentions reset and default state"]),
  q("vlsi-circ-med-010", "Setup and hold time",
    "Define setup time and hold time for a flip-flop. What failure mode occurs if hold time is violated?",
    ["timing", "sequential-logic"], ["setup", "hold", "metastability"], SOURCES.vlsi,
    ["Defines setup as minimum data stable before clock edge", "Defines hold as minimum data stable after clock edge", "Explains metastability or unpredictable Q if violated", "Notes clock skew worsens margins", "Mentions fixing with delay cells or better floorplan at high level"]),
  q("vlsi-circ-med-011", "CMOS inverter VTC",
    "Sketch the voltage transfer characteristic of a CMOS inverter. Where is the switching threshold?",
    ["cmos", "analog-digital"], ["inverter", "vtc", "noise-margin"], SOURCES.vlsi,
    ["Describes high output for low input and vice versa", "Identifies switching threshold near VDD/2 for symmetric devices", "Mentions noise margins NML and NMH conceptually", "Notes sharp transition region benefit", "Relates to rail-to-rail swing"]),
  q("vlsi-circ-med-012", "Static power in CMOS",
    "What causes static (leakage) power in modern CMOS and one technique to reduce it?",
    ["cmos", "low-power"], ["leakage", "subthreshold", "power-gating"], SOURCES.vlsi,
    ["Mentions subthreshold leakage and gate leakage at high level", "Notes static power rises with scaling", "Names one technique such as power gating, multi-Vt, or body bias", "Distinguishes static from dynamic switching power", "Connects to mobile and IoT relevance"]),
  q("vlsi-circ-med-013", "Dynamic power equation",
    "Write the dynamic power expression for CMOS switching and explain each term.",
    ["cmos", "low-power"], ["dynamic-power", "capacitance", "frequency"], SOURCES.vlsi,
    ["States P = α C V² f or equivalent form", "Explains load capacitance and activity factor", "Notes voltage squared dependence", "Relates frequency to clock rate", "Mentions reducing VDD or clock gating to save power"]),
  q("vlsi-circ-med-014", "Tri-state buffer use",
    "Why are tri-state buffers used on a shared bus? What happens if two drivers activate simultaneously?",
    ["digital-logic", "bus"], ["tri-state", "contention", "bus"], SOURCES.digital,
    ["Explains high-Z state for bus sharing", "Warns of bus contention if multiple drivers active", "Mentions need for enable control and timing", "Gives example such as bidirectional data bus", "Notes modern on-chip often uses mux instead but concept remains"]),
  q("vlsi-circ-med-015", "Encoder vs priority encoder",
    "What is the difference between a binary encoder and a priority encoder?",
    ["digital-logic", "combinational"], ["encoder", "priority"], SOURCES.digital,
    ["Encoder assumes one-hot input active", "Priority encoder resolves multiple active inputs by priority rule", "Gives truth table or example for 4-to-2 priority encoder", "Notes use in interrupt handling", "Avoids ambiguous output when multiple inputs high"]),
  q("vlsi-circ-med-016", "Decoder application",
    "How does a 3-to-8 decoder implement a Boolean function?",
    ["digital-logic", "combinational"], ["decoder", "minterm"], SOURCES.digital,
    ["Maps minterms to OR of decoder outputs", "Shows select lines as function inputs", "Uses enable pin if relevant", "Connects to ROM/PLA concept at high level", "Demonstrates with small example"]),
  q("vlsi-circ-med-017", "Ripple carry delay",
    "Why does a ripple-carry adder become slow for wide operands?",
    ["arithmetic", "timing"], ["ripple-carry", "propagation-delay"], SOURCES.digital,
    ["Carry propagates sequentially through each stage", "Delay grows linearly with bit width", "Mentions carry-lookahead or prefix tree as improvement", "Quantifies worst-case path conceptually", "Compares area versus speed trade-off"]),
  q("vlsi-circ-med-018", "Clock skew problem",
    "Define clock skew. How can positive skew affect setup timing?",
    ["timing", "clock"], ["clock-skew", "setup", "cts"], SOURCES.vlsi,
    ["Defines skew as arrival time difference at flops", "Explains effective cycle time reduction with positive skew on capture", "Notes hold time can worsen with wrong skew direction", "Mentions clock tree synthesis goal", "States need for balanced distribution"]),
  q("vlsi-circ-med-019", "Blocking vs non-blocking",
    "In Verilog, when should you use non-blocking assignments (<=) in sequential always blocks?",
    ["rtl", "verilog"], ["blocking", "non-blocking", "simulation"], SOURCES.verilog,
    ["Non-blocking for sequential logic to avoid race in simulation", "Blocking often for combinational logic", "Explains NBA schedules updates at end of time step", "Warns mixing styles causes mismatches", "Connects to synthesizable RTL style"]),
  q("vlsi-circ-med-020", "Incomplete sensitivity list",
    "What problem arises from an incomplete sensitivity list in combinational always @(*) blocks?",
    ["rtl", "verilog"], ["sensitivity-list", "latch-inference"], SOURCES.verilog,
    ["Simulator may miss input changes in old Verilog style", "Can infer unintended latches if outputs not assigned all branches", "Recommends always @(*) or explicit default assignments", "Notes synthesis versus simulation mismatch risk", "Gives example of missing input"]),
  q("vlsi-circ-med-021", "Synchronizer two-flop",
    "Why use a two-flop synchronizer when crossing a single-bit signal into a new clock domain?",
    ["cdc", "timing"], ["synchronizer", "metastability", "cdc"], SOURCES.vlsi,
    ["First flop may go metastable on async input", "Second flop resolves to valid logic level with high probability", "Notes MTBF improves with faster clock and proper cell selection", "States this is for single-bit control not buses", "Mentions multi-bit needs FIFO or handshake"]),
  q("vlsi-circ-med-022", "FIFO for CDC",
    "Why is an asynchronous FIFO used for wide data crossing between clock domains?",
    ["cdc", "design"], ["async-fifo", "gray-code", "handshake"], SOURCES.vlsi,
    ["Avoids sampling multi-bit bus with independent synchronizers", "Uses gray-code pointers for safe full/empty detection", "Explains write and read clocks independent", "Mentions latency and flow control", "Notes common in SoC IP interfaces"]),
  q("vlsi-circ-med-023", "Pipeline register purpose",
    "Insert a pipeline register between combinational stages. What improves and what is the cost?",
    ["pipelining", "timing"], ["pipeline", "throughput", "latency"], SOURCES.vlsi,
    ["Reduces combinational depth per cycle improving max frequency", "Increases latency in cycles", "Can increase throughput for steady stream", "Adds flip-flop and clock power overhead", "Notes retiming concept"]),
  q("vlsi-circ-med-024", "Glitch and hazard",
    "Explain a static-1 hazard in combinational logic. How can it be eliminated?",
    ["digital-logic", "hazards"], ["hazard", "glitch", "k-map"], SOURCES.digital,
    ["Momentary output dip when input changes due to path delay mismatch", "Shows hazard on K-map with adjacent groups not covering transition", "Adds redundant term to cover hazard", "Distinguishes static vs dynamic hazards", "Notes hazards matter in async inputs to flops"]),
  q("vlsi-circ-med-025", "SR latch forbidden input",
    "What happens when S=1 and R=1 simultaneously in a basic NOR-based SR latch?",
    ["sequential-logic", "latches"], ["sr-latch", "invalid-state"], SOURCES.digital,
    ["Both outputs may drive same level causing race or invalid state", "States forbidden or invalid input combination", "Notes reset to known state required after", "Prefers gated or clocked versions in practice", "Relates to why SR rarely used raw in RTL"]),
  q("vlsi-circ-med-026", "JK flip-flop toggle",
    "Explain toggle mode of a JK flip-flop and one application.",
    ["sequential-logic", "flip-flop"], ["jk-flop", "toggle", "counter"], SOURCES.digital,
    ["J=K=1 causes output toggle each active clock edge", "Used in counters and frequency dividers", "Contrasts with D flip-flop simplicity in modern design", "Mentions excitation table", "Notes preset/clear if applicable"]),
  q("vlsi-circ-med-027", "Ring oscillator concept",
    "Describe how an odd number of inverters forms a ring oscillator. What sets frequency?",
    ["analog-digital", "timing"], ["ring-oscillator", "delay"], SOURCES.vlsi,
    ["Odd stages required for sustained oscillation", "Frequency inversely related to per-stage delay", "Notes used for crude on-chip clock or characterization", "Not used for precision production clocks", "Mentions enable control for test"]),
  q("vlsi-circ-med-028", "Pull-up pull-down",
    "In CMOS, why do we use PMOS for pull-up and NMOS for pull-down in an inverter?",
    ["cmos", "devices"], ["pmos", "nmos", "inverter"], SOURCES.vlsi,
    ["Relates to carrier mobility and threshold for strong pull-up/down", "Describes complementary structure with no static current in ideal case", "Notes both devices sized for symmetric switching", "Connects to layout matching", "Avoids pass-transistor weak logic levels confusion"]),
  q("vlsi-circ-med-029", "Transmission gate",
    "What is a CMOS transmission gate and when is it used?",
    ["cmos", "analog-digital"], ["transmission-gate", "mux"], SOURCES.vlsi,
    ["Parallel NMOS and PMOS with complementary gate drives", "Passes analog or full-swing logic when on", "Used in muxes and latches", "Compares to single pass transistor threshold drop", "Notes on-resistance variation with input"]),
  q("vlsi-circ-med-030", "SRAM cell stability",
    "Describe a 6T SRAM cell at high level. What keeps the stored bit stable?",
    ["memory", "cmos"], ["sram", "6t-cell", "bistable"], SOURCES.vlsi,
    ["Two cross-coupled inverters form bistable latch", "Access transistors connect bit lines for read/write", "Explains read disturb and write margin conceptually", "Contrasts with DRAM refresh need", "Notes used in caches and registers"]),
  q("vlsi-circ-med-031", "Write operation SRAM",
    "During an SRAM write, why must bit lines be driven strongly?",
    ["memory", "timing"], ["sram", "write", "margin"], SOURCES.vlsi,
    ["Must overpower feedback loop to flip stored value", "Weak write may fail or slow write", "Mentions bit-line precharge before access", "Notes process voltage temperature impact on margin", "Connects to yield in memory arrays"]),
  q("vlsi-circ-med-032", "PLA versus ROM",
    "Compare PLA and ROM for implementing combinational logic.",
    ["digital-design", "memory"], ["pla", "rom", "logic-array"], SOURCES.digital,
    ["PLA uses programmable AND and OR planes", "ROM uses fixed decoder and programmable outputs", "Discusses density and flexibility trade-offs", "Notes modern designs use standard cells instead", "Educational link to FPGA LUT concept"]),
  q("vlsi-circ-med-033", "Verilog case full case",
    "Why should a combinational case statement in Verilog be full case or include default?",
    ["rtl", "verilog"], ["case-statement", "latch-inference"], SOURCES.verilog,
    ["Incomplete case may infer latch for uncovered inputs", "Default assigns known value for all branches", "Important for synthesis matching intent", "Mentions parallel_case and full_case pragmas cautiously", "Uses enum or one-hot encoding best practice"]),
  q("vlsi-circ-med-034", "Parameterized width adder",
    "How would you parameterize an N-bit adder module in Verilog?",
    ["rtl", "verilog"], ["parameter", "generate", "adder"], SOURCES.verilog,
    ["Uses parameter WIDTH or similar", "Generate loop or behavioral + for instantiation", "Exports carry out signal", "Testbench varies parameter", "Synthesis creates correct width hardware"]),
  q("vlsi-circ-med-035", "Testbench clock generation",
    "Write pseudocode or describe generating a 50% duty clock in a Verilog testbench.",
    ["verification", "verilog"], ["testbench", "clock", "simulation"], SOURCES.verilog,
    ["Uses forever loop with half-period delays", "Or always toggle every #half_period", "Initial block starts clock", "Timescale directive awareness", "Notes not synthesizable code acceptable in TB"]),
  q("vlsi-circ-med-036", "Setup slack intuition",
    "If setup slack is negative after place-and-route, what three fixes might you try?",
    ["timing", "physical-design"], ["setup", "slack", "optimization"], SOURCES.vlsi,
    ["Reduce combinational logic depth or pipeline", "Lower clock frequency", "Improve cell sizing or routing on critical path", "Reduce clock skew beneficially if applicable", "Mentions ECO or RTL change"]),
  q("vlsi-circ-med-037", "Hold slack fix",
    "Hold violations often appear after adding delay on data path. Why add buffer delay on clock or data?",
    ["timing", "physical-design"], ["hold", "buffer", "min-delay"], SOURCES.vlsi,
    ["Hold requires data stable after clock edge minimum time", "Fast paths may violate hold at slow corner", "Adding delay on data path increases hold margin", "Distinguishes from setup which wants faster paths", "Notes fix at post-route stage"]),
  q("vlsi-circ-med-038", "Fan-out delay",
    "How does excessive fan-out on a net affect delay and what mitigates it?",
    ["timing", "physical-design"], ["fan-out", "buffer", "drive-strength"], SOURCES.vlsi,
    ["Large capacitive load slows transition", "Insert buffer tree or upsize driver", "Mentions logical versus physical fan-out", "Relates to clock nets special handling", "Notes synthesis drive strength options"]),
  q("vlsi-circ-med-039", "One-hot FSM encoding",
    "When is one-hot FSM state encoding preferred over binary?",
    ["fsm", "encoding"], ["one-hot", "timing", "area"], SOURCES.vlsi,
    ["Simpler next-state logic often faster", "Uses more flip-flops for wide state count", "Good when state count modest and speed critical", "Easier debug in simulation", "Trade-off area versus timing"]),
  q("vlsi-circ-med-040", "Debouncer circuit",
    "Outline a digital debouncer for a mechanical switch input before sending to a processor.",
    ["digital-design", "practical"], ["debounce", "counter", "fsm"], SOURCES.digital,
    ["Waits for stable input over time window", "Uses counter or shift register stability check", "Filters bounce glitches", "Outputs clean level transition", "Notes common in embedded hardware interfaces"]),
  q("vlsi-circ-med-041", "BCD to 7-segment",
    "Design approach for BCD to seven-segment decoder. What inputs and outputs?",
    ["digital-logic", "combinational"], ["bcd", "seven-segment", "decoder"], SOURCES.digital,
    ["Four BCD inputs represent decimal 0-9", "Seven segment outputs with segment mapping", "Handles invalid BCD optionally blank", "Truth table or case structure", "Common lab interview question"]),
  q("vlsi-circ-med-042", "Johnson counter",
    "Explain a Johnson (twisted ring) counter and its modulus for n flip-flops.",
    ["sequential-logic", "counters"], ["johnson-counter", "modulus"], SOURCES.digital,
    ["Inverts feedback from last flop to first", "Modulus 2n for n flip-flops", "Generates zigzag pattern on outputs", "Compares to standard ring counter", "Uses in timing circuits historically"]),
  q("vlsi-circ-med-043", "Comparator from subtractor",
    "How can a magnitude comparator use a subtractor or adder?",
    ["digital-logic", "arithmetic"], ["comparator", "subtractor"], SOURCES.digital,
    ["Subtract A-B and inspect sign and zero flags", "Greater/equal/less from carry and zero", "Extends to unsigned comparison", "Two's complement for signed variant mentioned", "Efficient combined datapath"]),
  q("vlsi-circ-med-044", "Clock gating cell",
    "What is integrated clock gating and how does it save dynamic power?",
    ["low-power", "rtl"], ["clock-gating", "icg", "enable"], SOURCES.vlsi,
    ["ANDs clock with enable using latch-based gating cell", "Stops toggling downstream flops when idle", "Must meet enable setup/hold to clock", "Synthesis inserts ICG from RTL enable patterns", "Major technique in mobile SoCs"]),
  q("vlsi-circ-med-045", "Reset synchronizer release",
    "Why should async reset de-assertion be synchronized to clock?",
    ["reset", "cdc"], ["reset-synchronizer", "recovery"], SOURCES.verilog,
    ["Prevents reset removal near clock edge causing metastability", "Uses async assert sync deassert chain", "Standard RTL pattern for IP blocks", "Avoids partial reset across hierarchy", "Mentions reset tree distribution"]),
  q("vlsi-circ-med-046", "Signed arithmetic overflow",
    "How detect overflow when adding two signed numbers in hardware?",
    ["arithmetic", "digital-logic"], ["overflow", "signed", "two-complement"], SOURCES.digital,
    ["XOR of carry into MSB and carry out of MSB", "Or compare sign bits of operands and result", "Explains positive+positive giving negative as overflow", "Extends to ALU flag generation", "Distinguishes carry out versus overflow"]),
  q("vlsi-circ-med-047", "Barrel shifter",
    "Describe function of a barrel shifter in a processor datapath.",
    ["datapath", "digital-design"], ["barrel-shifter", "shift", "alu"], SOURCES.digital,
    ["Shifts by variable amount in one or few stages", "Uses mux stages for power-of-two shifts", "Left/right and arithmetic shift variants", "Critical for ALU operations", "Trade-off area versus delay"]),
  q("vlsi-circ-med-048", "Wallace tree",
    "What is a Wallace tree used for in multiplier design?",
    ["arithmetic", "datapath"], ["multiplier", "wallace-tree", "partial-product"], SOURCES.vlsi,
    ["Compresses partial products in parallel reduction tree", "Faster than sequential accumulation", "Followed by final adder", "Area versus delay trade-off", "Common interview topic for DSP blocks"]),
  q("vlsi-circ-med-049", "Latch-up concern",
    "What is latch-up in CMOS and one prevention method at layout level?",
    ["cmos", "reliability"], ["latch-up", "guard-ring", "esd"], SOURCES.vlsi,
    ["Parasitic SCR path from VDD to GND triggered by overvoltage or noise", "Guard rings and proper substrate ties reduce risk", "Separate analog/digital wells where needed", "ESD structures related topic", "Process and layout awareness"]),
  q("vlsi-circ-med-050", "Design review checklist",
    "You review an RTL block before tape-out. List five checks you would perform as a junior engineer.",
    ["verification", "rtl"], ["design-review", "checklist", "quality"], SOURCES.verilog,
    ["Reset and clock domain crossing correctness", "Full case/default and no unintended latches", "Assertions or protocol checks if applicable", "Synthesis lint and timing constraint presence", "Documentation of interfaces and assumptions"]),
];

// ── Circuit Design MCQ (50) — common fresher written-test questions ─────
const circuitMcqs = [
  m("vlsi-circ-mcq-001", "NAND universal gate",
    "Which gate is considered universal because any Boolean function can be implemented using it alone?",
    ["digital-logic", "gates"], ["universal-gate", "nand"], SOURCES.digital,
    ["NAND", "XOR", "XNOR", "Buffer"], "A", "NAND (and NOR) alone can implement NOT, AND, and OR functions."),
  m("vlsi-circ-mcq-002", "De Morgan's theorem",
    "Which identity is correct according to De Morgan's laws?",
    ["boolean-algebra", "digital-logic"], ["de-morgan", "logic"], SOURCES.digital,
    ["(A·B)' = A' + B'", "(A·B)' = A' · B'", "(A+B)' = A' + B'", "A+A' = 0"], "A", "De Morgan: complement of product equals sum of complements."),
  m("vlsi-circ-mcq-003", "Absorption law",
    "Simplify A + A·B.",
    ["boolean-algebra", "digital-logic"], ["absorption", "simplification"], SOURCES.digital,
    ["A", "B", "A+B", "A'"], "A", "Absorption law: A + AB = A."),
  m("vlsi-circ-mcq-004", "Full adder sum",
    "The sum output S of a full adder is (in XOR form):",
    ["arithmetic", "digital-logic"], ["full-adder", "xor"], SOURCES.digital,
    ["A ⊕ B ⊕ Cin", "A + B + Cin", "A·B·Cin", "(A+B)Cin"], "A", "Full adder sum is the three-input XOR of A, B, and carry-in."),
  m("vlsi-circ-mcq-005", "2:1 MUX select",
    "In a 2:1 MUX, when select S = 1, the output Y equals:",
    ["combinational", "mux"], ["multiplexer", "select"], SOURCES.digital,
    ["I1", "I0", "S", "I0 + I1"], "A", "Select line chooses I0 when S=0 and I1 when S=1."),
  m("vlsi-circ-mcq-006", "4:1 MUX select lines",
    "How many select lines are required for a 4:1 multiplexer?",
    ["combinational", "mux"], ["multiplexer", "select-width"], SOURCES.digital,
    ["2", "1", "4", "3"], "A", "2^n inputs need n select lines; 4 inputs need 2 select lines."),
  m("vlsi-circ-mcq-007", "D flip-flop trigger",
    "A positive-edge-triggered D flip-flop samples input D on:",
    ["sequential-logic", "flip-flop"], ["d-flop", "edge-trigger"], SOURCES.digital,
    ["Rising clock edge", "Falling clock edge", "High level of clock", "Low level of clock"], "A", "Positive-edge DFF updates on 0→1 clock transition."),
  m("vlsi-circ-mcq-008", "Latch vs FF sensitivity",
    "A transparent D latch is:",
    ["sequential-logic", "latches"], ["latch", "level-sensitive"], SOURCES.digital,
    ["Level-sensitive", "Edge-sensitive", "Combinational only", "Asynchronous only"], "A", "Latch follows input while enable is active (level-sensitive)."),
  m("vlsi-circ-mcq-009", "Setup time",
    "Setup time is the minimum interval data must be stable:",
    ["timing", "sequential-logic"], ["setup-time", "flip-flop"], SOURCES.vlsi,
    ["Before the active clock edge", "After the active clock edge", "Only during reset", "Only when clock is low"], "A", "Setup ensures data is stable before the capturing clock edge."),
  m("vlsi-circ-mcq-010", "Hold time violation",
    "A hold time violation most directly risks:",
    ["timing", "sequential-logic"], ["hold-time", "metastability"], SOURCES.vlsi,
    ["Metastability or incorrect capture", "Increased dynamic power only", "Higher fan-out drive", "Larger die area"], "A", "Insufficient hold margin can cause the wrong value to be latched."),
  m("vlsi-circ-mcq-011", "K-map group size",
    "In a Karnaugh map, valid implicant groups must contain:",
    ["boolean-algebra", "k-map"], ["karnaugh-map", "grouping"], SOURCES.digital,
    ["1, 2, 4, … powers of two cells", "Any odd number of cells", "Exactly three cells always", "Only single cells"], "A", "Groups must be rectangular powers of two for valid minimization."),
  m("vlsi-circ-mcq-012", "Gray code property",
    "Adjacent codes in Gray sequence differ in:",
    ["number-systems", "digital-logic"], ["gray-code", "encoding"], SOURCES.digital,
    ["Exactly one bit", "Two bits always", "All bits", "No bits"], "A", "Gray code changes one bit per step, reducing logic hazards in counters."),
  m("vlsi-circ-mcq-013", "Excess-3 property",
    "Excess-3 code for decimal digits is obtained by adding ___ to natural BCD.",
    ["number-systems", "digital-logic"], ["excess-3", "bcd"], SOURCES.digital,
    ["3", "1", "7", "15"], "A", "Excess-3 adds 3 (0011) to each BCD digit representation."),
  m("vlsi-circ-mcq-014", "Mod-10 counter FFs",
    "What is the minimum number of flip-flops needed for a mod-10 counter?",
    ["sequential-logic", "counters"], ["mod-counter", "flip-flop"], SOURCES.digital,
    ["4", "3", "10", "2"], "A", "2^3=8 < 10 ≤ 16=2^4, so at least 4 flip-flops are required."),
  m("vlsi-circ-mcq-015", "Ring counter modulus",
    "A ring counter made with 5 flip-flops (single 1 pattern) has modulus:",
    ["sequential-logic", "counters"], ["ring-counter", "modulus"], SOURCES.digital,
    ["5", "10", "32", "4"], "A", "Standard ring counter cycles through N states with N flip-flops."),
  m("vlsi-circ-mcq-016", "Johnson counter modulus",
    "A Johnson (twisted ring) counter with 4 flip-flops has modulus:",
    ["sequential-logic", "counters"], ["johnson-counter", "modulus"], SOURCES.digital,
    ["8", "4", "16", "6"], "A", "Johnson counter modulus is 2n for n flip-flops."),
  m("vlsi-circ-mcq-017", "CMOS static current",
    "In ideal CMOS static logic, steady-state current from VDD to GND is:",
    ["cmos", "low-power"], ["static-power", "cmos-inverter"], SOURCES.vlsi,
    ["Negligible (except leakage)", "Always maximum", "Equal to peak switching current", "Independent of input"], "A", "Complementary pull-up/down avoids DC path in valid logic levels."),
  m("vlsi-circ-mcq-018", "CMOS inverter pull-up",
    "In a standard CMOS inverter, the pull-up device is:",
    ["cmos", "devices"], ["pmos", "nmos", "inverter"], SOURCES.vlsi,
    ["PMOS", "NMOS", "Both NMOS only", "Resistor only"], "A", "PMOS connects output to VDD when input is low."),
  m("vlsi-circ-mcq-019", "Tri-state output",
    "When disabled, a tri-state buffer output is in:",
    ["digital-logic", "bus"], ["tri-state", "high-z"], SOURCES.digital,
    ["High-impedance state", "Strong logic 0", "Strong logic 1", "Oscillation"], "A", "High-Z allows multiple drivers to share a bus when inactive."),
  m("vlsi-circ-mcq-020", "Verilog NBA in sequential",
    "In synthesizable sequential always blocks, assignments should normally use:",
    ["rtl", "verilog"], ["non-blocking", "sequential"], SOURCES.verilog,
    ["Non-blocking (<=)", "Blocking (=)", "Force/release", "Assign only"], "A", "NBA avoids race conditions between parallel flip-flop updates in simulation."),
  m("vlsi-circ-mcq-021", "Verilog blocking combinational",
    "For combinational always blocks, the recommended assignment style is:",
    ["rtl", "verilog"], ["blocking", "combinational"], SOURCES.verilog,
    ["Blocking (=)", "Non-blocking (<=)", "Only wire assign forbidden", "Deassign"], "A", "Blocking assignments reflect immediate combinational dependency."),
  m("vlsi-circ-mcq-022", "Latch inference cause",
    "A combinational always block may infer a latch when:",
    ["rtl", "verilog"], ["latch-inference", "incomplete-case"], SOURCES.verilog,
    ["Not all input conditions assign every output", "Using non-blocking assignments", "Using parameters", "Using integer types"], "A", "Incomplete branches leave outputs holding previous value → latch."),
  m("vlsi-circ-mcq-023", "Sensitivity list best practice",
    "In Verilog-2001, which construct automatically tracks all read signals in combinational logic?",
    ["rtl", "verilog"], ["always-star", "sensitivity"], SOURCES.verilog,
    ["always @(*)", "always @(posedge clk)", "initial", "forever"], "A", "@(*) replaces manual sensitivity lists and reduces omission errors."),
  m("vlsi-circ-mcq-024", "2's complement range",
    "For an 8-bit two's complement number, the representable range is:",
    ["number-systems", "arithmetic"], ["two-complement", "range"], SOURCES.digital,
    ["-128 to +127", "0 to 255", "-127 to +127", "-256 to +255"], "A", "n-bit signed range is -2^(n-1) to 2^(n-1)-1."),
  m("vlsi-circ-mcq-025", "Signed overflow flag",
    "Signed addition overflow occurs when carry into MSB ___ carry out of MSB (XOR).",
    ["arithmetic", "digital-logic"], ["overflow", "signed"], SOURCES.digital,
    ["Differs from", "Equals", "Is always 1", "Is always 0"], "A", "Overflow XOR of carry-in and carry-out at sign bit detects signed overflow."),
  m("vlsi-circ-mcq-026", "Priority encoder",
    "A priority encoder differs from a basic encoder because it:",
    ["combinational", "encoder"], ["priority-encoder", "multiple-inputs"], SOURCES.digital,
    ["Handles multiple active inputs by priority rule", "Requires one-hot input only", "Has no enable pin", "Outputs analog voltage"], "A", "Priority encoder resolves multiple highs to highest-priority code."),
  m("vlsi-circ-mcq-027", "Decoder use",
    "A 3-to-8 decoder with enable can implement:",
    ["combinational", "decoder"], ["minterm", "logic"], SOURCES.digital,
    ["Any function of three variables as OR of minterms", "Only parity functions", "Only sequential state machines", "Analog filtering"], "A", "Each output corresponds to one minterm; OR outputs to implement SOP."),
  m("vlsi-circ-mcq-028", "Demultiplexer function",
    "A 1-to-4 demultiplexer routes one input to:",
    ["combinational", "demux"], ["demultiplexer", "select"], SOURCES.digital,
    ["One of four outputs based on select", "All outputs simultaneously", "Only the MSB output", "Clock input only"], "A", "Select lines choose which output receives the input."),
  m("vlsi-circ-mcq-029", "Fan-out limit",
    "Large fan-out on a gate output primarily increases:",
    ["timing", "physical-design"], ["fan-out", "delay"], SOURCES.vlsi,
    ["Load capacitance and propagation delay", "Supply voltage", "Threshold voltage", "Channel length"], "A", "More driven inputs add capacitance, slowing transitions."),
  m("vlsi-circ-mcq-030", "Propagation delay",
    "Propagation delay tp is typically measured between:",
    ["timing", "digital-logic"], ["propagation-delay", "transition"], SOURCES.digital,
    ["50% input to 50% output crossing", "0% to 100% output only", "Reset to Q only", "Clock to power rail"], "A", "Standard delay metric uses mid-rail input and output points."),
  m("vlsi-circ-mcq-031", "Clock skew sign",
    "Positive clock skew means the capture flip-flop clock arrives:",
    ["timing", "clock"], ["clock-skew", "capture"], SOURCES.vlsi,
    ["Later than the launch flip-flop clock", "Earlier than launch clock", "At exactly the same instant globally", "Only during reset"], "A", "Skew is difference in clock arrival times at different flops."),
  m("vlsi-circ-mcq-032", "Mealy machine output",
    "In a Mealy FSM, outputs depend on:",
    ["fsm", "digital-design"], ["mealy", "output"], SOURCES.digital,
    ["Present state and inputs", "Present state only", "Next state only", "Reset only"], "A", "Mealy outputs are functions of state and current inputs."),
  m("vlsi-circ-mcq-033", "Moore machine output",
    "In a Moore FSM, outputs depend on:",
    ["fsm", "digital-design"], ["moore", "output"], SOURCES.digital,
    ["Present state only", "Inputs only", "Next state and inputs", "Clock period only"], "A", "Moore outputs are associated with states, not inputs directly."),
  m("vlsi-circ-mcq-034", "Synchronous counter advantage",
    "Synchronous counters are preferred over ripple counters mainly because:",
    ["sequential-logic", "counters"], ["synchronous", "ripple"], SOURCES.digital,
    ["All flops share a common clock edge reducing cumulative delay", "They use fewer wires", "They need no flip-flops", "They cannot exceed modulus 2"], "A", "Ripple counters accumulate stage delays; sync counters toggle together."),
  m("vlsi-circ-mcq-035", "Static-1 hazard",
    "A static-1 hazard produces:",
    ["digital-logic", "hazards"], ["static-hazard", "glitch"], SOURCES.digital,
    ["A momentary 0 glitch when output should stay 1", "Permanent oscillation", "Always correct output", "Only metastability"], "A", "Static-1 hazard is a brief dip in an otherwise steady high output."),
  m("vlsi-circ-mcq-036", "Open-drain output",
    "Open-drain (open-collector) outputs typically require:",
    ["digital-logic", "io"], ["open-drain", "pull-up"], SOURCES.digital,
    ["External or internal pull-up resistor", "No connection to any rail", "Only PMOS pull-up on same gate", "Higher supply voltage"], "A", "Open-drain can pull low; pull-up defines high level."),
  m("vlsi-circ-mcq-037", "Binary to Gray MSB",
    "In binary-to-Gray conversion, the MSB of Gray code equals:",
    ["number-systems", "encoding"], ["gray-code", "conversion"], SOURCES.digital,
    ["MSB of binary", "XOR of all binary bits", "Inverted MSB always", "Sum of binary bits"], "A", "G[n-1] = B[n-1]; other bits G[i] = B[i] ⊕ B[i+1]."),
  m("vlsi-circ-mcq-038", "NAND implements AND",
    "To build an AND gate using only NAND gates (without NOT), minimum NAND count is:",
    ["digital-logic", "gates"], ["nand", "and-implementation"], SOURCES.digital,
    ["2", "1", "3", "4"], "A", "NAND(A,B) followed by NAND with both inputs tied to its output inverts once → AND."),
  m("vlsi-circ-mcq-039", "Canonical SOP",
    "Canonical SOP form uses:",
    ["boolean-algebra", "digital-logic"], ["sop", "minterms"], SOURCES.digital,
    ["Sum of minterms", "Product of maxterms only", "Only single literals", "Only NAND literals"], "A", "SOP = OR of AND terms each covering one minterm."),
  m("vlsi-circ-mcq-040", "Invalid BCD",
    "Which 4-bit pattern is NOT a valid BCD digit?",
    ["number-systems", "bcd"], ["bcd", "invalid-code"], SOURCES.digital,
    ["1010", "0101", "1001", "0000"], "A", "Valid BCD is 0000–1001 (0–9); 1010–1111 are invalid."),
  m("vlsi-circ-mcq-041", "Metastability resolution",
    "Metastability in a flip-flop means the output is:",
    ["timing", "sequential-logic"], ["metastability", "cdc"], SOURCES.vlsi,
    ["Between valid logic levels temporarily", "Always at valid 0", "Always at valid 1", "At supply voltage"], "A", "Metastable state is an unresolved intermediate voltage region."),
  m("vlsi-circ-mcq-042", "Two-flop synchronizer purpose",
    "The second flip-flop in a two-flop synchronizer mainly:",
    ["cdc", "timing"], ["synchronizer", "metastability"], SOURCES.vlsi,
    ["Resolves metastability to a valid logic level", "Doubles clock frequency", "Implements reset tree", "Performs arithmetic"], "A", "Second stage samples Q of first after metastability window."),
  m("vlsi-circ-mcq-043", "Pipeline throughput",
    "Ideal pipelining with balanced stages primarily improves:",
    ["pipelining", "timing"], ["throughput", "latency"], SOURCES.vlsi,
    ["Maximum operating frequency / throughput", "Single-task latency always decreases", "Static power only", "Hold time margin always"], "A", "Pipelining raises clock rate; latency in cycles may increase."),
  m("vlsi-circ-mcq-044", "Clock gating benefit",
    "Integrated clock gating reduces dynamic power by:",
    ["low-power", "rtl"], ["clock-gating", "dynamic-power"], SOURCES.vlsi,
    ["Stopping clock toggling to idle flip-flops", "Lowering supply voltage always", "Removing all flip-flops", "Increasing switching activity"], "A", "Gated clocks prevent unnecessary downstream toggling."),
  m("vlsi-circ-mcq-045", "T flip-flop condition",
    "A T flip-flop toggles its output when T equals:",
    ["sequential-logic", "flip-flop"], ["t-flop", "toggle"], SOURCES.digital,
    ["1", "0", "X", "High-Z"], "A", "T=1 causes toggle on active clock edge; T=0 holds state."),
  m("vlsi-circ-mcq-046", "SR latch forbidden input",
    "For a NOR-based SR latch, the forbidden input combination is:",
    ["sequential-logic", "latches"], ["sr-latch", "invalid-state"], SOURCES.digital,
    ["S=1, R=1", "S=0, R=0", "S=1, R=0", "S=0, R=1"], "A", "S=R=1 can force both outputs low and create indeterminate state."),
  m("vlsi-circ-mcq-047", "Half adder carry",
    "The carry output of a half adder is:",
    ["arithmetic", "digital-logic"], ["half-adder", "carry"], SOURCES.digital,
    ["A·B", "A ⊕ B", "A + B", "A' + B'"], "A", "Half adder carry is AND of inputs; sum is XOR."),
  m("vlsi-circ-mcq-048", "PLA structure",
    "A Programmable Logic Array (PLA) implements logic using:",
    ["digital-design", "memory"], ["pla", "and-or"], SOURCES.digital,
    ["Programmable AND plane followed by OR plane", "Only ROM decoder", "Only shift registers", "Only analog switches"], "A", "PLA = programmable AND array feeding OR array."),
  m("vlsi-circ-mcq-049", "Setup slack negative",
    "Negative setup slack after STA means:",
    ["timing", "physical-design"], ["setup", "slack"], SOURCES.vlsi,
    ["Data arrives too late for the required clock period", "Hold time is violated only", "Power grid is weak", "Scan chain is missing"], "A", "Negative setup slack indicates paths fail required max delay."),
  m("vlsi-circ-mcq-050", "Bus contention result",
    "If two tri-state drivers actively drive opposite values on one bus simultaneously:",
    ["digital-logic", "bus"], ["contention", "tri-state"], SOURCES.digital,
    ["Bus contention and possible excessive current", "Valid wired-AND result always", "Automatic high-Z on both", "Increased noise margin"], "A", "Contention fights strong 0 vs strong 1 → high current and invalid logic."),
];

// ── Core Technical (30) — device, fab, architecture fundamentals ────────
const coreQuestions = [
  q("vlsi-core-med-001", "MOSFET regions of operation",
    "Explain cutoff, linear, and saturation regions of an NMOS transistor.",
    ["semiconductor-devices", "mosfet"], ["cutoff", "linear", "saturation"], SOURCES.semi,
    ["Cutoff when VGS below threshold", "Linear triode when VDS small", "Saturation when VDS exceeds VGS-Vth", "Relates IDs equation qualitatively in each region", "Connects to inverter switching"], "conceptual"),
  q("vlsi-core-med-002", "Threshold voltage factors",
    "What factors affect MOSFET threshold voltage Vth?",
    ["semiconductor-devices", "mosfet"], ["threshold", "process", "body-effect"], SOURCES.semi,
    ["Oxide thickness and doping concentration", "Body effect with source-body bias", "Temperature dependence", "Device length and short-channel effects at high level", "Implies process variation impact"], "conceptual"),
  q("vlsi-core-med-003", "PMOS vs NMOS speed",
    "Why is NMOS historically faster than PMOS in the same technology?",
    ["semiconductor-devices", "mosfet"], ["mobility", "electrons", "holes"], SOURCES.semi,
    ["Higher electron mobility in inversion layer than holes", "Leads to stronger NMOS drive for same size", "Motivates complementary CMOS sizing ratio", "Notes strain and high-k improvements over generations", "Interview classic question"], "conceptual"),
  q("vlsi-core-med-004", "PN junction depletion",
    "What is depletion region in a PN junction and how does reverse bias affect it?",
    ["semiconductor-devices", "pn-junction"], ["depletion", "reverse-bias"], SOURCES.semi,
    ["Diffusion creates empty ionized region", "Reverse bias widens depletion and blocks current", "Forward bias narrows and allows conduction", "Relates to diode I-V curve", "Foundation for transistor action"], "conceptual"),
  q("vlsi-core-med-005", "SRAM vs DRAM",
    "Compare SRAM and DRAM in terms of cell structure, speed, density, and use.",
    ["memory", "architecture"], ["sram", "dram", "cache"], SOURCES.semi,
    ["SRAM six-transistor bistable faster denser cost higher per bit", "DRAM one transistor one capacitor needs refresh", "SRAM in cache registers", "DRAM in main memory", "Trade-off speed density power cost"], "conceptual"),
  q("vlsi-core-med-006", "Flash memory NOR NAND",
    "High-level difference between NOR and NAND flash memory architectures.",
    ["memory", "non-volatile"], ["flash", "nor", "nand"], SOURCES.semi,
    ["NOR random access execute-in-place friendly", "NAND higher density block erase serial read", "NAND dominates storage SSD USB", "Erase/program cycles and wear", "Controller manages bad blocks in NAND"], "conceptual"),
  q("vlsi-core-med-007", "ASIC vs FPGA",
    "Compare ASIC and FPGA for product development at a fresher interview level.",
    ["design-flow", "fpga"], ["asic", "fpga", "nre"], SOURCES.vlsi,
    ["FPGA reprogrammable higher unit cost lower NRE faster prototype", "ASIC lower unit cost at volume high mask NRE longer cycle", "FPGA for validation and low volume", "ASIC for mobile SoC high volume", "Mentions RTL flows overlap"], "conceptual"),
  q("vlsi-core-med-008", "RTL synthesis meaning",
    "What does logic synthesis do to RTL Verilog?",
    ["design-flow", "synthesis"], ["rtl", "synthesis", "netlist"], SOURCES.vlsi,
    ["Maps behavioral RTL to gate-level netlist from library", "Optimizes for timing area power constraints", "Does not place or route", "Requires constraints and target technology", "Output for P&R tools"], "conceptual"),
  q("vlsi-core-med-009", "Place and route",
    "What happens during place-and-route after synthesis?",
    ["physical-design", "backend"], ["pnr", "floorplan", "routing"], SOURCES.vlsi,
    ["Places standard cells on die rows", "Routes signal clock power nets", "Optimizes timing DRC LVS targets", "Generates GDS for fabrication", "Iterates with timing closure"], "conceptual"),
  q("vlsi-core-med-010", "DRC and LVS",
    "Define DRC and LVS checks in physical verification.",
    ["physical-design", "verification"], ["drc", "lvs", "signoff"], SOURCES.vlsi,
    ["DRC checks layout rules spacing width", "LVS compares layout versus schematic/netlist connectivity", "Both required before tape-out", "Failures require layout ECO", "Foundry provides rule deck"], "conceptual"),
  q("vlsi-core-med-011", "Moore's Law implication",
    "What practical challenges arise as feature size scales down per Moore's Law?",
    ["technology", "scaling"], ["moore-law", "leakage", "variation"], SOURCES.semi,
    ["Leakage power increases importance", "Process variation affects yield", "Interconnect delay dominates", "DFM and lithography complexity", "Still motivates integration but slower cadence"], "conceptual"),
  q("vlsi-core-med-012", "SoC definition",
    "What is a System-on-Chip and name three typical IP blocks integrated.",
    ["soc", "architecture"], ["soc", "ip-blocks", "integration"], SOURCES.vlsi,
    ["Single chip integrates CPU memory controllers peripherals", "Examples DMA UART GPU NPU DDR controller", "Bus or network-on-chip connects blocks", "Verification complexity rises", "Power domains common"], "conceptual"),
  q("vlsi-core-med-013", "Cache hierarchy",
    "Why do processors use L1, L2, and L3 caches?",
    ["computer-architecture", "memory"], ["cache", "locality", "hierarchy"], SOURCES.semi,
    ["Exploits temporal and spatial locality", "Smaller faster caches close to core", "Larger slower levels reduce memory latency average", "Miss penalty motivates line size and associativity", "Coherency in multi-core mentioned"], "conceptual"),
  q("vlsi-core-med-014", "Pipeline hazard types",
    "Name three types of hazards in a pipelined processor.",
    ["computer-architecture", "pipeline"], ["hazards", "stall", "forwarding"], SOURCES.semi,
    ["Structural resource conflict", "Data RAW WAR WAW at high level", "Control branch mispredict", "Forwarding bypass reduces data stalls", "Branch prediction reduces control penalty"], "conceptual"),
  q("vlsi-core-med-015", "Interrupt versus polling",
    "Compare interrupt-driven and polling I/O for a peripheral.",
    ["embedded", "systems"], ["interrupt", "polling", "latency"], SOURCES.semi,
    ["Interrupt saves CPU until event occurs lower average load", "Polling simpler but wastes cycles", "Latency trade-offs for real-time", "DMA often paired with interrupts", "Context save overhead noted"], "conceptual"),
  q("vlsi-core-med-016", "Scan chain DFT",
    "What is scan insertion for manufacturing test?",
    ["dft", "testing"], ["scan", "atpg", "stuck-at"], SOURCES.vlsi,
    ["Replaces flops with scannable cells forming shift register", "Allows automatic test pattern generation for stuck-at faults", "Increases test coverage versus functional patterns alone", "Adds area and slight timing impact", "Standard in ASIC flow"], "conceptual"),
  q("vlsi-core-med-017", "BIST memory",
    "Why use built-in self-test for on-chip memories?",
    ["dft", "memory"], ["bist", "mbist", "yield"], SOURCES.vlsi,
    ["Tests arrays quickly on tester or boot", "Patterns target typical memory faults", "Reduces external test time cost", "Integrated controller in SoC", "Important for large SRAM instances"], "conceptual"),
  q("vlsi-core-med-018", "Antenna effect",
    "What is antenna effect in CMOS fabrication and how is it fixed?",
    ["physical-design", "reliability"], ["antenna", "routing", "diode"], SOURCES.vlsi,
    ["Long metal during etch collects charge damaging gate oxide", "Jumpers or diode clamps discharge during processing", "Router antenna rules in P&R", "More issue in upper metal before via down", "Foundry specifies limits"], "conceptual"),
  q("vlsi-core-med-019", "Electromigration basics",
    "What is electromigration in interconnects and why does it matter?",
    ["reliability", "physical-design"], ["em", "interconnect", "current-density"], SOURCES.vlsi,
    ["High current density moves metal atoms causing open or short", "Worse at narrow lines and high temperature", "Wide wires vias and spacing rules mitigate", "Long-term reliability signoff", "Relevant in power grids"], "conceptual"),
  q("vlsi-core-med-020", "Signal integrity crosstalk",
    "Define crosstalk between adjacent nets and one mitigation.",
    ["signal-integrity", "physical-design"], ["crosstalk", "coupling", "spacing"], SOURCES.vlsi,
    ["Capacitive coupling causes noise on victim net", "Can cause glitches or timing delta", "Increase spacing shielding or buffer victim", "Critical on long parallel buses", "SI analysis in signoff"], "conceptual"),
  q("vlsi-core-med-021", "Op-amp virtual short",
    "Explain virtual short concept in ideal op-amp negative feedback.",
    ["analog", "circuits"], ["op-amp", "feedback", "virtual-short"], SOURCES.semi,
    ["High gain forces input differential voltage near zero", "Enables predictable transfer functions", "Basis for buffers amplifiers filters", "Real op-amp has finite gain bandwidth", "Common analog interview question"], "conceptual"),
  q("vlsi-core-med-022", "RC low-pass filter",
    "How does an RC low-pass filter behave and where is cutoff frequency?",
    ["analog", "circuits"], ["rc-filter", "cutoff", "frequency"], SOURCES.semi,
    ["Attenuates high frequencies", "fc = 1/(2πRC) qualitative", "Used for power supply decoupling and signal filtering", "First-order roll-off", "Relates time constant τ = RC"], "conceptual"),
  q("vlsi-core-med-023", "ADC sampling theorem",
    "State Nyquist criterion for sampling an analog signal.",
    ["analog", "data-conversion"], ["nyquist", "sampling", "aliasing"], SOURCES.semi,
    ["Sample rate at least twice highest signal frequency", "Undersampling causes aliasing", "Anti-alias filter before ADC", "Relevant in mixed-signal SoC", "Connects to clock choice in data acquisition"], "conceptual"),
  q("vlsi-core-med-024", "Bandgap reference",
    "Why is a bandgap reference used in IC design?",
    ["analog", "power"], ["bandgap", "voltage-reference", "temperature"], SOURCES.semi,
    ["Provides stable reference against supply and temperature", "Combines PTAT and CTAT voltages", "Biases regulators and ADCs", "Found in nearly all chips", "Interview topic for analog roles"], "conceptual"),
  q("vlsi-core-med-025", "ESD protection",
    "Why are ESD protection structures placed at chip I/O pads?",
    ["reliability", "io"], ["esd", "hvd", "latch-up"], SOURCES.semi,
    ["Human-machine model discharge can destroy thin oxide", "Clamp diodes or specialty devices shunt current", "Required for manufacturing and field reliability", "Trade-off capacitance on high-speed I/O", "Design rule mandated"], "conceptual"),
  q("vlsi-core-med-026", "Metal layer purpose",
    "Why do modern processes use many metal layers?",
    ["physical-design", "technology"], ["metal-stack", "routing", "power"], SOURCES.vlsi,
    ["Separates signal power and clock routing planes", "Reduces congestion improves timing", "Upper thick metals for power delivery", "More layers higher cost", "Foundry specific stack rules"], "conceptual"),
  q("vlsi-core-med-027", "FinFET advantage",
    "What problem does FinFET transistor structure address?",
    ["technology", "devices"], ["finfet", "short-channel", "leakage"], SOURCES.semi,
    ["Better gate control reduces leakage at short channels", "Improved drive at scaled dimensions", "Dominant in advanced nodes", "More complex layout versus planar", "Industry scaling enabler"], "conceptual"),
  q("vlsi-core-med-028", "UVM role",
    "What is UVM in verification and why is it used?",
    ["verification", "methodology"], ["uvm", "systemverilog", "coverage"], SOURCES.vlsi,
    ["Standard library for reusable testbench components", "Promotes constrained random verification", "Functional coverage driven closure", "Industry standard for block and SoC sim", "Fresher may describe concept not code all APIs"], "conceptual"),
  q("vlsi-core-med-029", "Functional vs timing signoff",
    "Distinguish functional verification signoff from timing signoff.",
    ["verification", "timing"], ["signoff", "sta", "simulation"], SOURCES.vlsi,
    ["Functional proves behavior matches spec via simulation/formal", "Timing proves paths meet clock constraints via STA", "Both required for tape-out confidence", "Different tools and metrics", "Corner cases slow-fast process voltage temperature"], "conceptual"),
  q("vlsi-core-med-030", "Wafer yield",
    "What is die yield on a wafer and what affects it?",
    ["manufacturing", "economics"], ["yield", "defect-density", "cost"], SOURCES.semi,
    ["Fraction of good dies per wafer", "Defect density and die area drive yield formula qualitatively", "Smaller dies higher yield", "Impacts chip cost and pricing", "Test and redundancy improve effective yield"], "conceptual"),
];

// ── HR Behavioral (15) ──────────────────────────────────────────────────
const hrQuestions = [
  h("vlsi-hr-med-001", "Why VLSI role",
    "Why do you want to pursue a career in VLSI or hardware design?",
    ["hr", "motivation"], ["vlsi", "career-fit"], SOURCES.hr,
    ["Links personal interest to digital/analog hardware specifically", "Mentions relevant coursework projects or internships", "Shows awareness of semiconductor industry impact", "Avoids generic only salary answer", "Connects to company product domain if possible"],
    ["motivation", "roleUnderstanding", "companyFit"]),
  h("vlsi-hr-med-002", "RTL project explanation",
    "Walk me through a digital design or Verilog project from your coursework or internship.",
    ["hr", "project"], ["rtl", "portfolio"], SOURCES.hr,
    ["States problem specification and personal contribution clearly", "Explains design choices and verification approach", "Shares outcome such as simulation results or FPGA demo", "Acknowledges challenges and how resolved", "Uses structured concise explanation"],
    ["situationClarity", "technicalDepth", "ownership", "outcomes"]),
  h("vlsi-hr-med-003", "Debugging simulation failure",
    "Tell me about a time a simulation or lab result did not match expected output. What did you do?",
    ["hr", "problem-solving"], ["debugging", "simulation"], SOURCES.hr,
    ["Describes specific mismatch symptom", "Explains systematic debug such as waveform check assumptions", "Shows persistence and method not random changes", "Shares root cause found", "Reflects lesson for future verification"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-004", "Tight tape-out deadline",
    "Describe a situation where you had a tight deadline on a lab or project submission. How did you manage?",
    ["hr", "pressure"], ["deadline", "time-management"], SOURCES.hr,
    ["Sets context and deliverables", "Prioritizes critical path tasks", "Communicates early if blocked", "Delivers acceptable quality on time or negotiates scope", "Reflects on planning improvement"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-005", "Team lab conflict",
    "Tell me about a disagreement with a teammate on a group hardware lab project.",
    ["hr", "teamwork"], ["conflict", "collaboration"], SOURCES.hr,
    ["Explains disagreement objectively", "Shows listening and data or spec reference to resolve", "Focuses on project success not winning argument", "Positive team outcome", "Reflection on communication"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-006", "Learning Verilog quickly",
    "Describe how you learned Verilog or digital design tools when first exposed to them.",
    ["hr", "learning"], ["verilog", "self-learning"], SOURCES.hr,
    ["Names resources labs mentors or online material", "Shows hands-on practice beyond reading", "Gives evidence of skill such as completed design", "Demonstrates curiosity and discipline", "Connects to role readiness"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-007", "Attention to detail",
    "Give an example where attention to detail prevented a bug in your design or testbench.",
    ["hr", "quality"], ["detail", "verification"], SOURCES.hr,
    ["Specific near-miss or caught error", "Explains check that found issue", "Impact if undetected", "Personal habit or review process", "Shows pride in quality"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-008", "Why this semiconductor company",
    "Why do you want to join our company specifically?",
    ["hr", "motivation"], ["company-research", "fit"], SOURCES.hr,
    ["References company products technology node or culture research", "Connects personal skills to their domain analog digital memory etc", "Avoids generic praise only", "Shows long-term interest in semiconductor", "Authentic and specific"],
    ["motivation", "companyFit", "roleUnderstanding"]),
  h("vlsi-hr-med-009", "Handling repetitive verification",
    "Verification can involve repetitive test runs. How do you stay focused and effective?",
    ["hr", "work-style"], ["verification", "discipline"], SOURCES.hr,
    ["Acknowledges reality of regression runs", "Uses scripts automation or checklists", "Tracks coverage goals", "Takes structured breaks if needed", "Shows mature attitude toward flow"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-010", "Failure in competition or exam",
    "Tell me about an academic or competition failure and what you learned.",
    ["hr", "resilience"], ["failure", "learning"], SOURCES.hr,
    ["Honest account without excessive blame", "Identifies specific improvement actions taken after", "Shows improved later outcome if possible", "Demonstrates growth mindset", "Connects lesson to engineering work"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-011", "Explaining to non-expert",
    "Describe a time you explained a technical hardware concept to someone without an engineering background.",
    ["hr", "communication"], ["teaching", "simplicity"], SOURCES.hr,
    ["Chooses appropriate analogy or visual", "Avoids jargon overload", "Checks understanding", "Successful communication outcome", "Useful skill for cross-functional teams"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-012", "Internship contribution",
    "What was your most meaningful contribution during an internship or major project?",
    ["hr", "experience"], ["internship", "impact"], SOURCES.hr,
    ["Clear personal contribution not team-only claim", "Technical or process improvement described", "Measurable or observable impact", "Alignment with role expectations", "Humility about team support"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-013", "Staying updated in VLSI",
    "How do you keep yourself updated with trends in semiconductor and VLSI?",
    ["hr", "learning"], ["industry-awareness", "continuous-learning"], SOURCES.hr,
    ["Mentions credible sources conferences papers forums", "Gives recent example topic learned", "Shows genuine interest beyond exams", "Relates trend to career goals", "Balanced not name-dropping only"],
    ["motivation", "roleUnderstanding", "continuousLearning"]),
  h("vlsi-hr-med-014", "Ethical issue",
    "Tell me about a time you faced an ethical dilemma in academic or project work.",
    ["hr", "integrity"], ["ethics", "honesty"], SOURCES.hr,
    ["Describes dilemma clearly", "Shows integrity in decision", "Communicates appropriately to authority if needed", "Outcome and lesson stated", "Professional maturity"],
    ["situationClarity", "actionOwnership", "resultSpecificity", "reflection"]),
  h("vlsi-hr-med-015", "Five-year vision",
    "Where do you see yourself in five years in the VLSI/hardware field?",
    ["hr", "career-goals"], ["growth", "realistic-plan"], SOURCES.hr,
    ["Realistic progression such as design verification or PD depth", "Shows commitment to semiconductor domain", "Open to learning multiple aspects early career", "Aligns with company growth paths", "Avoids unrealistic only managerial claim"],
    ["motivation", "roleUnderstanding", "careerPlanning"]),
];

const companyTagsFor = (index) => {
  const pool = COMPANIES.semi;
  return Array.from({ length: 4 }, (_, offset) => pool[(index * 4 + offset) % pool.length]);
};

const circuitRubricFor = (criteria) =>
  criteria.map((text, index) => ({
    text,
    category: ["circuitCorrectness", "analysis", "tradeoffs", "practicalConstraints", "communication"][index] || "coverage",
    importance: index < 3 ? "mustHave" : "goodToHave",
    expectedAnswerMode: "design",
  }));

const coreRubricFor = (criteria) =>
  criteria.map((text, index) => ({
    text,
    category: ["fundamentals", "reasoning", "application", "assumptions", "communication"][index] || "coverage",
    importance: index < 3 ? "mustHave" : "goodToHave",
    expectedAnswerMode: "conceptual",
  }));

const hrRubricFor = (criteria) =>
  criteria.map((text, index) => ({
    text,
    category: ["situationClarity", "actionOwnership", "resultSpecificity", "reflection", "communication"][index] || "coverage",
    importance: index < 3 ? "mustHave" : "goodToHave",
    expectedAnswerMode: "story",
  }));

const csvEscape = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;
const writeCsv = async (fileName, columns, rows) => {
  const output = [
    columns.map(csvEscape).join(","),
    ...rows.map((row) => columns.map((column) => csvEscape(row[column])).join(",")),
  ].join("\n");
  await fs.writeFile(path.join(outputDir, fileName), `${output}\n`, "utf8");
};

const normalizeKey = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

await fs.mkdir(outputDir, { recursive: true });

let tagIndex = 0;
const nextTags = () => companyTagsFor(tagIndex++);

const rubricColumns = [
  "questionId", "title", "question", "companyTags", "topics", "subtopics", "url",
  "rubric", "source", "verified", "qualityScore",
];
const hrColumns = [...rubricColumns.slice(0, 8), "behavioralSignals", ...rubricColumns.slice(8)];
const mcqColumns = [
  "questionId", "title", "question", "companyTags", "topics", "subtopics", "url",
  "optionA", "optionB", "optionC", "optionD", "correctOptionId", "explanation",
  "source", "verified", "qualityScore",
];

const circuitCsv = "vlsi-circuit-design-medium-rubric-50.csv";
const circuitMcqCsv = "vlsi-circuit-design-medium-mcq-50.csv";
const coreCsv = "vlsi-core-technical-medium-rubric-30.csv";
const hrCsv = "vlsi-hr-medium-behavioral-15.csv";

await writeCsv(
  circuitCsv,
  rubricColumns,
  circuitQuestions.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: nextTags().join("|"),
    topics: item.topics.join("|"),
    subtopics: item.subtopics.join("|"),
    url: item.source,
    rubric: JSON.stringify(circuitRubricFor(item.criteria)),
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

tagIndex = 0;
await writeCsv(
  circuitMcqCsv,
  mcqColumns,
  circuitMcqs.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: nextTags().join("|"),
    topics: item.topics.join("|"),
    subtopics: item.subtopics.join("|"),
    url: item.source,
    optionA: item.options[0],
    optionB: item.options[1],
    optionC: item.options[2],
    optionD: item.options[3],
    correctOptionId: item.answer,
    explanation: item.explanation,
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

tagIndex = 0;
await writeCsv(
  coreCsv,
  rubricColumns,
  coreQuestions.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: nextTags().join("|"),
    topics: item.topics.join("|"),
    subtopics: item.subtopics.join("|"),
    url: item.source,
    rubric: JSON.stringify(coreRubricFor(item.criteria)),
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

tagIndex = 0;
await writeCsv(
  hrCsv,
  hrColumns,
  hrQuestions.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: nextTags().join("|"),
    topics: item.topics.join("|"),
    subtopics: item.subtopics.join("|"),
    url: item.source,
    rubric: JSON.stringify(hrRubricFor(item.criteria)),
    behavioralSignals: (item.signals || []).join("|"),
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

const summary = {
  outputDir,
  roleTag: "VLSI/Hardware Engineer",
  files: [
    { name: circuitCsv, roundType: "Circuit Design", evaluationStrategy: "rubric_llm", rows: circuitQuestions.length },
    { name: circuitMcqCsv, roundType: "Circuit Design", evaluationStrategy: "mcq_exact", rows: circuitMcqs.length },
    { name: coreCsv, roundType: "Core Technical", evaluationStrategy: "rubric_llm", rows: coreQuestions.length },
    { name: hrCsv, roundType: "HR", evaluationStrategy: "behavioral_llm", rows: hrQuestions.length },
  ],
  totalRows: circuitQuestions.length + circuitMcqs.length + coreQuestions.length + hrQuestions.length,
  companyPool: COMPANIES.semi.length,
};

const allNew = [...circuitQuestions, ...circuitMcqs, ...coreQuestions, ...hrQuestions];

if (process.env.MONGO_URI) {
  const mongoose = (await import("mongoose")).default;
  const InterviewQuestion = (await import("../models/InterviewQuestion.js")).default;
  const CompanyStatic = (await import("../models/CompanyStatic.js")).default;
  await mongoose.connect(process.env.MONGO_URI);

  const existing = await InterviewQuestion.find({}, { questionId: 1, title: 1, question: 1 }).lean();
  const known = new Set((await CompanyStatic.find({}, { name: 1 }).lean()).map((c) => c.name));
  const existingIds = new Set(existing.map((r) => r.questionId));
  const existingTitles = new Set(existing.map((r) => normalizeKey(r.title)));
  const existingQ = new Set(existing.map((r) => normalizeKey(r.question?.slice(0, 120))));

  summary.dbDedupe = {
    duplicateIds: allNew.filter((i) => existingIds.has(i.id)).map((i) => i.id),
    duplicateTitles: allNew.filter((i) => existingTitles.has(normalizeKey(i.title))).map((i) => i.title),
    duplicateQuestionPrefixes: allNew.filter((i) => existingQ.has(normalizeKey(i.question.slice(0, 120)))).map((i) => i.id),
    unknownCompanies: COMPANIES.semi.filter((c) => !known.has(c)),
  };

  if (
    summary.dbDedupe.duplicateIds.length ||
    summary.dbDedupe.duplicateTitles.length ||
    summary.dbDedupe.duplicateQuestionPrefixes.length ||
    summary.dbDedupe.unknownCompanies.length
  ) {
    console.error(JSON.stringify(summary, null, 2));
    await mongoose.disconnect();
    process.exit(1);
  }
  await mongoose.disconnect();
}

console.log(JSON.stringify(summary, null, 2));
