import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputDir = path.join(__dirname, "data", "generated-interview-imports");

const COMPANIES = {
  ecommerce: [
    "7-Eleven",
    "Amazon",
    "Eternal Limited",
    "Flipkart",
    "Lenskart",
    "Meesho",
    "Swiggy",
  ],
  cyber: [
    "Arctic Wolf",
    "Auxia",
    "EGDK",
    "IMPACT ANALYTICS",
    "Inflection.io",
    "MatreComm",
    "Nexthop AI",
    "OnSecurity Technologies",
    "Palo Alto Networks",
    "PrimeNumbers",
    "RNS Brains",
    "RedFold AI",
    "Robylon AI",
    "Saviynt",
    "Sigmoid",
    "Skylo Tech",
    "Turner TTS",
    "ZScaler",
  ],
  enterprise: [
    "Adobe",
    "Atlassian",
    "Cisco",
    "Cloudera",
    "Coupa Software",
    "Eightfold AI",
    "Fivetran",
    "HPE",
    "IBM",
    "LinkedIn",
    "Microsoft",
    "NetApp",
    "OneTrust",
    "Oracle",
    "Oracle Financial Services Software",
    "Red Hat",
    "SAP",
    "Twilio",
    "Whatfix",
    "o9 Solutions",
  ],
  product: [
    "AMD",
    "Airbus",
    "Ather Energy",
    "Boeing",
    "Cohesity",
    "Confluent",
    "Dell Technologies",
    "GE Healthcare",
    "Google",
    "Honeywell",
    "Juniper Networks",
    "New Relic",
    "Nokia",
    "Nvidia",
    "Qualcomm",
    "Samsung",
    "Siemens",
    "Walmart",
    "Walmart Labs",
    "Warner Music Group",
  ],
  service: [
    "Accenture",
    "BRILLIO",
    "Cognizant",
    "Deloitte",
    "Dentsu",
    "EY",
    "Epsilon",
    "Fractal Analytics",
    "Genpact",
    "GyanSys",
    "ITC Infotech",
    "Infosys",
    "LTIMindtree",
    "Mphasis",
    "Presidio",
    "Prodapt",
    "Sonata Software",
    "TCS NQT",
    "ThoughtWorks",
    "ZS Associates",
  ],
};

const SOURCES = {
  ecommerce:
    "https://igotanoffer.com/blogs/tech/amazon-machine-learning-engineer-interview",
  ecommerceRanking:
    "https://blog.flipkart.tech/multi-objective-optimisation-in-suggestions-ranking-flipkart-49099b951eae",
  cyber:
    "https://dataford.io/interview-guides/abnormal-ai/machine-learning-engineer",
  cyberSystems:
    "https://dataford.io/interview-guides/a10-networks/machine-learning-engineer",
  enterprise:
    "https://dataford.io/interview-guides/salesforce/machine-learning-engineer",
  enterpriseGenAi:
    "https://prachub.com/interview-guide/microsoft-machine-learning-engineer-interview-guide",
  product:
    "https://igotanoffer.com/en/advice/machine-learning-system-design-interview",
  service:
    "https://www.linkedin.com/posts/galgalepallavi_tcs-interviewexperience-genai-activity-7419624110521090048-Q3sC",
  serviceFresher:
    "https://www.geeksforgeeks.org/interview-experiences/tata-consultancy-services-tcs-prime-interview-experience-on-campus-2026/",
};

const q = (id, category, title, question, topics, source, criteria) => ({
  id,
  category,
  title,
  question,
  topics,
  source,
  criteria,
});

const descriptive = [
  q("aiml-cross-med-001", "ecommerce", "Two-stage recommendation system",
    "Design a two-stage product recommendation system for a marketplace with millions of items. Explain candidate generation, ranking, features, evaluation, and serving.",
    ["recommender-systems", "ranking", "ml-system-design"], SOURCES.ecommerce,
    ["Separates high-recall candidate retrieval from precise ranking", "Uses user, item, context, and interaction features without leakage", "Chooses implicit-feedback losses and negative sampling carefully", "Evaluates retrieval and ranking offline plus business metrics online", "Addresses latency, freshness, cold start, diversity, and monitoring"]),
  q("aiml-cross-med-002", "ecommerce", "Search relevance labels",
    "An e-commerce search team trains on clicks, but position bias makes top-ranked products appear more relevant. How would you create better labels and evaluate the new ranker?",
    ["learning-to-rank", "bias", "search"], SOURCES.ecommerceRanking,
    ["Identifies position and presentation bias in click labels", "Uses randomized traffic, propensity weighting, or debiased click models", "Distinguishes pointwise, pairwise, and listwise ranking objectives", "Uses NDCG or MRR with judged or debiased relevance data", "Confirms impact through guarded online experiments"]),
  q("aiml-cross-med-003", "ecommerce", "New-user recommendation cold start",
    "How would you personalize recommendations for a new user who has no purchase history and only two page views?",
    ["recommender-systems", "cold-start", "personalization"], SOURCES.ecommerce,
    ["Uses contextual, session, popularity, and item-content signals", "Updates recommendations from short-session behavior", "Balances exploration with safe popular defaults", "Handles consent and avoids overinterpreting sparse evidence", "Evaluates new-user cohorts separately using ranking and business metrics"]),
  q("aiml-cross-med-004", "ecommerce", "Intermittent SKU demand",
    "Design a demand-forecasting approach for products with intermittent sales, promotions, stockouts, and strong festival seasonality.",
    ["forecasting", "inventory", "time-series"], SOURCES.ecommerce,
    ["Treats stockouts as censored demand rather than true zero demand", "Models calendar, price, promotion, hierarchy, and availability effects", "Uses suitable intermittent-demand and global-model baselines", "Performs rolling-origin validation across seasonal periods", "Produces uncertainty estimates tied to inventory decisions"]),
  q("aiml-cross-med-005", "ecommerce", "Multi-objective ranking",
    "A search ranker improves click-through rate but reduces completed purchases and increases returns. How would you redesign its objective and experimentation plan?",
    ["learning-to-rank", "multi-objective-optimization", "experimentation"], SOURCES.ecommerceRanking,
    ["Explains why CTR is an incomplete proxy for customer value", "Defines conversion, revenue, return, relevance, and latency objectives", "Discusses weighted, constrained, or multi-task optimization", "Checks segment effects and delayed downstream outcomes", "Uses an A/B test with guardrails and a clear launch criterion"]),
  q("aiml-cross-med-006", "ecommerce", "Review-spam detection",
    "Build a model to detect coordinated fake product reviews when only a small fraction of reviews have reliable labels.",
    ["fraud-detection", "nlp", "graph-ml"], SOURCES.ecommerce,
    ["Combines text, timing, reviewer, product, and relationship signals", "Uses weak or semi-supervised labels with confidence tracking", "Models coordination through graph or group-level features", "Validates with time splits and investigator precision at capacity", "Plans adversarial monitoring and human-review feedback"]),
  q("aiml-cross-med-007", "ecommerce", "Delivery-time prediction",
    "A food-delivery ETA model is systematically late during rain and peak hours. How would you diagnose and improve it?",
    ["regression", "geospatial-ml", "model-monitoring"], SOURCES.ecommerce,
    ["Slices residuals by weather, geography, time, restaurant, and courier state", "Separates preparation, pickup, and travel components where useful", "Adds point-in-time traffic, weather, queue, and route features", "Uses robust loss and prediction intervals or quantiles", "Monitors calibration and deploys through a guarded experiment"]),
  q("aiml-cross-med-008", "ecommerce", "Visual product deduplication",
    "Design a system to find duplicate marketplace listings using product images and noisy titles while keeping false merges low.",
    ["computer-vision", "multimodal-ml", "similarity-search"], SOURCES.ecommerce,
    ["Creates image and text embeddings with category-aware metadata", "Uses approximate nearest-neighbor retrieval followed by verification", "Trains with hard positives and hard negatives", "Evaluates recall at k and pairwise precision by category", "Uses conservative merge thresholds, review queues, and drift monitoring"]),
  q("aiml-cross-med-009", "ecommerce", "Delayed conversion attribution",
    "Users often purchase days after seeing a recommendation. How would you train and evaluate a conversion model without mislabeling recent impressions as negatives?",
    ["labeling", "recommendation", "delayed-feedback"], SOURCES.ecommerce,
    ["Defines attribution and label-maturity windows explicitly", "Keeps unresolved impressions separate from confirmed negatives", "Considers delayed-feedback or survival modeling", "Prevents leakage from post-impression events", "Uses temporal evaluation and monitors delay distribution changes"]),
  q("aiml-cross-med-010", "ecommerce", "Sale-event model reliability",
    "Your recommendation model was trained on normal traffic. What would you do before and during a major sale event where traffic and user behavior change sharply?",
    ["distribution-shift", "recommender-systems", "mlops"], SOURCES.ecommerce,
    ["Backtests on prior high-traffic events and relevant cohorts", "Stress-tests feature pipelines, caches, and inference capacity", "Uses event-aware features and safe fallbacks", "Monitors score, inventory, latency, conversion, and diversity in real time", "Defines rollback and post-event retraining or recalibration"]),

  q("aiml-cross-med-011", "cyber", "Real-time phishing detection",
    "Design a real-time phishing-email detector using message text, headers, URLs, sender history, and organization context.",
    ["cybersecurity", "nlp", "ml-system-design"], SOURCES.cyber,
    ["Combines content, URL, sender, authentication, graph, and behavioral signals", "Uses time-based splits and campaign-aware grouping", "Optimizes precision and recall around quarantine and analyst capacity", "Meets ingestion, feature, and inference latency constraints", "Handles adversarial drift, explanations, feedback, and safe fallback"]),
  q("aiml-cross-med-012", "cyber", "Account-takeover features",
    "What features and validation strategy would you use to detect account takeover from login and session events?",
    ["cybersecurity", "anomaly-detection", "feature-engineering"], SOURCES.cyber,
    ["Uses device, IP, geolocation, impossible-travel, velocity, and behavioral signals", "Builds user-relative and peer-relative baselines", "Avoids leakage from remediation or investigation outcomes", "Uses chronological, user-aware evaluation with rare-event metrics", "Defines challenge, block, review actions and monitors attacker adaptation"]),
  q("aiml-cross-med-013", "cyber", "Unknown network attacks",
    "You have abundant normal network traffic but few examples of new attacks. Compare supervised classification, one-class learning, and unsupervised anomaly detection for this problem.",
    ["cybersecurity", "anomaly-detection", "model-selection"], SOURCES.cyberSystems,
    ["Explains assumptions and limitations of each learning setup", "Recognizes that unusual traffic is not necessarily malicious", "Proposes robust temporal and protocol-level features", "Evaluates with labeled incidents and analyst precision at capacity", "Combines anomaly scores, signatures, supervised models, and human feedback"]),
  q("aiml-cross-med-014", "cyber", "Adversarially robust malware model",
    "A malware classifier relies heavily on easily modified file metadata. How would you test and improve its robustness against evasion?",
    ["cybersecurity", "adversarial-ml", "malware"], SOURCES.cyberSystems,
    ["Threat-models which features an attacker can manipulate", "Tests realistic semantic-preserving perturbations and future malware families", "Adds harder-to-spoof behavioral or structural features", "Uses adversarial augmentation and model ensembles cautiously", "Monitors confidence, abstains on uncertain samples, and layers defenses"]),
  q("aiml-cross-med-015", "cyber", "SOC alert prioritization",
    "A security operations center can investigate only 300 alerts per day. Design a model and metric strategy for prioritizing alerts.",
    ["cybersecurity", "ranking", "decision-threshold"], SOURCES.cyber,
    ["Frames the task as ranking or constrained classification", "Uses severity, asset criticality, confidence, novelty, and incident context", "Optimizes precision, recall, or expected impact at review capacity", "Handles biased historical analyst labels", "Supports explanations, diversity, monitoring, and feedback from investigations"]),
  q("aiml-cross-med-016", "cyber", "Security-label scarcity",
    "Only 500 of ten million security events have analyst-confirmed labels. How would you use unlabeled data without letting noisy pseudo-labels dominate training?",
    ["semi-supervised-learning", "cybersecurity", "labeling"], SOURCES.cyber,
    ["Starts with a trustworthy supervised baseline and label audit", "Uses representation learning, clustering, or consistency methods appropriately", "Applies confidence thresholds and class-aware pseudo-label sampling", "Keeps a clean labeled validation set untouched", "Uses active learning to spend analyst effort on informative cases"]),
  q("aiml-cross-med-017", "cyber", "Identity attack graph",
    "Design graph features for detecting coordinated privilege abuse across users, devices, applications, and cloud resources.",
    ["graph-ml", "identity-security", "feature-engineering"], SOURCES.cyber,
    ["Defines meaningful heterogeneous nodes, edges, direction, and event time", "Builds neighborhood risk, rare-path, shared-entity, and temporal features", "Avoids future-edge leakage in offline graph construction", "Compares graph models with simpler graph-feature baselines", "Supports incremental updates, explanations, and low-latency scoring"]),
  q("aiml-cross-med-018", "cyber", "Safe LLM log assistant",
    "Design and evaluate an LLM assistant that summarizes security alerts and recommends investigation steps without inventing evidence.",
    ["generative-ai", "cybersecurity", "rag"], SOURCES.cyberSystems,
    ["Grounds responses in authorized alerts, logs, and playbooks", "Separates retrieved evidence from generated recommendations with citations", "Evaluates factuality, coverage, abstention, and analyst usefulness", "Tests prompt injection, data leakage, and malicious log content", "Adds permission checks, audit logs, human approval, and monitoring"]),
  q("aiml-cross-med-019", "cyber", "Attack-driven concept drift",
    "A login-risk model’s feature distributions are stable, yet confirmed attacks are increasing. How could concept drift exist without obvious covariate drift?",
    ["concept-drift", "cybersecurity", "model-monitoring"], SOURCES.cyber,
    ["Distinguishes changes in P(X), P(Y), and P(Y|X)", "Explains how attackers can change outcomes for similar observed features", "Checks delayed labels and performance by attack or user segment", "Looks for missing causal signals and new tactics", "Updates features, labels, thresholds, and models with safe validation"]),
  q("aiml-cross-med-020", "cyber", "False-positive incident",
    "After deployment, an anomaly detector floods analysts with legitimate backup traffic every Monday morning. Diagnose the failure and propose a durable fix.",
    ["anomaly-detection", "cybersecurity", "production-ml"], SOURCES.cyberSystems,
    ["Identifies recurring seasonality and missing operational context", "Adds time, workload, host-role, and maintenance-window features", "Uses contextual or seasonal baselines rather than a global threshold", "Backtests changes against attacks and benign peaks", "Adds analyst feedback, alert-volume guardrails, and recurrence monitoring"]),

  q("aiml-cross-med-021", "enterprise", "Tenant-aware churn prediction",
    "Design a churn model for enterprise SaaS where customers are organizations with many users, contracts, and product modules.",
    ["churn-modeling", "enterprise-saas", "classification"], SOURCES.enterprise,
    ["Defines churn, renewal horizon, and the account-level prediction unit", "Aggregates seat, usage, support, contract, and adoption signals point-in-time", "Handles few large tenants and segment heterogeneity", "Uses temporal validation and calibration by customer tier", "Connects scores to interventions and measures incremental retention"]),
  q("aiml-cross-med-022", "enterprise", "Support-ticket routing",
    "Build an NLP system that routes enterprise support tickets to the right product team while allowing new issue categories to appear.",
    ["nlp", "text-classification", "enterprise-ai"], SOURCES.enterprise,
    ["Uses ticket text, metadata, customer context, and product taxonomy", "Establishes lexical or linear baselines before transformers", "Supports hierarchical and unknown-category decisions with confidence thresholds", "Evaluates macro-F1, top-k accuracy, latency, and costly routing errors", "Learns from agent corrections and monitors taxonomy drift"]),
  q("aiml-cross-med-023", "enterprise", "Permission-aware enterprise RAG",
    "Design a RAG assistant over company documents where every employee has different document permissions.",
    ["rag", "access-control", "enterprise-ai"], SOURCES.enterpriseGenAi,
    ["Enforces authorization before or during retrieval, not only after generation", "Propagates document and chunk ACL metadata through indexes", "Uses identity-aware filtering with deny-by-default behavior", "Tests retrieval quality, groundedness, permission leakage, and revocation", "Includes audit logs, freshness, prompt-injection defenses, and abstention"]),
  q("aiml-cross-med-024", "enterprise", "Multi-tenant feature platform",
    "Design a feature platform used by multiple enterprise customers without allowing one tenant’s data or statistics to leak into another.",
    ["feature-store", "multi-tenancy", "ml-platform"], SOURCES.enterprise,
    ["Uses tenant-scoped storage, keys, authorization, and encryption", "Separates shared feature code from tenant-specific data and configuration", "Ensures offline-online parity and point-in-time correctness", "Prevents cross-tenant aggregates unless explicitly approved", "Adds lineage, quotas, isolation tests, monitoring, and deletion workflows"]),
  q("aiml-cross-med-025", "enterprise", "Scaling a heavy inference API",
    "A transformer inference endpoint misses its 200 ms p99 latency target during traffic spikes. How would you diagnose and optimize it?",
    ["model-serving", "transformers", "performance"], SOURCES.enterprise,
    ["Profiles tokenization, queueing, transfer, model, and post-processing time", "Uses batching, caching, quantization, distillation, or smaller models appropriately", "Scales replicas with concurrency and memory constraints understood", "Defines graceful degradation, timeouts, and fallback behavior", "Measures quality-latency-cost trade-offs under realistic load"]),
  q("aiml-cross-med-026", "enterprise", "RAG versus fine-tuning",
    "A client wants an LLM to answer questions about frequently changing internal policies. When would you choose RAG, fine-tuning, or both?",
    ["generative-ai", "rag", "fine-tuning"], SOURCES.enterpriseGenAi,
    ["Uses RAG for fresh, attributable external knowledge", "Uses fine-tuning for behavior, format, style, or task adaptation", "Explains why fine-tuning alone is poor for frequently changing facts", "Considers combined retrieval plus tuned behavior where justified", "Defines separate retrieval, generation, safety, cost, and freshness evaluations"]),
  q("aiml-cross-med-027", "enterprise", "Invoice information extraction",
    "Design a system to extract vendor, total, tax, currency, and line items from invoices with many layouts and languages.",
    ["document-ai", "multimodal-ml", "information-extraction"], SOURCES.enterpriseGenAi,
    ["Combines OCR, layout, visual, and textual representations", "Handles schema normalization, language, tables, and repeated fields", "Uses field-level confidence and business-rule validation", "Evaluates exact and fuzzy field metrics by template and language", "Routes uncertain cases to review and learns from corrections"]),
  q("aiml-cross-med-028", "enterprise", "Biased lead-scoring labels",
    "A sales lead model is trained on historical conversions, but salespeople contacted only leads selected by the previous model. What bias does this create and how would you address it?",
    ["selection-bias", "causal-inference", "lead-scoring"], SOURCES.enterprise,
    ["Identifies selective labels and policy-induced feedback loops", "Explains why uncontacted leads have missing counterfactual outcomes", "Uses randomized exploration or logged propensity information", "Considers inverse-propensity weighting, uplift, or bandit approaches", "Evaluates new policies online with business and fairness guardrails"]),
  q("aiml-cross-med-029", "enterprise", "Sparse enterprise forecasting",
    "Forecast weekly demand for thousands of B2B products when many product-customer series are sparse and customers place irregular bulk orders.",
    ["forecasting", "hierarchical-modeling", "enterprise-ai"], SOURCES.enterprise,
    ["Uses global or hierarchical models to share signal across sparse series", "Represents contracts, calendar, lead time, price, and customer effects", "Handles intermittent demand and outliers explicitly", "Uses rolling backtests and scale-appropriate metrics", "Produces uncertainty and reconciles forecasts to business hierarchies"]),
  q("aiml-cross-med-030", "enterprise", "Auditable employee recommendation",
    "An internal job-matching model recommends employees for roles. How would you make the system useful while controlling bias and preserving auditability?",
    ["recommender-systems", "responsible-ai", "enterprise-ai"], SOURCES.enterprise,
    ["Defines job-relevant features and excludes inappropriate protected proxies", "Audits exposure, ranking quality, calibration, and outcomes by group", "Provides candidate and recruiter explanations with uncertainty", "Allows appeals, human review, and correction of profile data", "Versions data and models and monitors feedback-loop effects"]),

  q("aiml-cross-med-031", "product", "Visual defect detection",
    "Design a vision model for manufacturing defects when defects are rare, vary in size, and new defect types appear after deployment.",
    ["computer-vision", "anomaly-detection", "manufacturing"], SOURCES.product,
    ["Chooses classification, detection, segmentation, or anomaly methods by requirement", "Uses high-resolution augmentation and defect-aware sampling", "Evaluates per-defect recall, false alarms, localization, and unseen shifts", "Handles label scarcity with transfer or self-supervised learning", "Supports edge latency, review, drift monitoring, and retraining"]),
  q("aiml-cross-med-032", "product", "Noisy speech recognition",
    "A voice-command model works in the lab but fails inside vehicles and factories. How would you improve robustness without collecting every possible noise condition?",
    ["speech-recognition", "robustness", "deep-learning"], SOURCES.product,
    ["Analyzes errors by noise, speaker, device, accent, and command", "Uses realistic noise and room-response augmentation", "Leverages pretrained speech representations and domain adaptation", "Measures task accuracy plus false activation and rejection rates", "Uses confidence, fallback, compression, and on-device monitoring"]),
  q("aiml-cross-med-033", "product", "Edge-model compression",
    "You must deploy an image classifier on a device with limited memory and a 30 ms latency budget. Compare quantization, pruning, and knowledge distillation.",
    ["edge-ai", "model-compression", "computer-vision"], SOURCES.product,
    ["Explains how each technique reduces compute or model size", "Distinguishes post-training from quantization-aware training", "Uses structured pruning when hardware acceleration matters", "Uses distillation to transfer behavior into a smaller architecture", "Benchmarks actual hardware quality, latency, memory, power, and regressions"]),
  q("aiml-cross-med-034", "product", "Predictive-maintenance leakage",
    "A predictive-maintenance model uses sensor readings from the 24 hours before failure and performs extremely well. What leakage and deployment-timing issues would you investigate?",
    ["predictive-maintenance", "data-leakage", "time-series"], SOURCES.product,
    ["Defines prediction horizon, lead time, and observation cutoff", "Checks maintenance actions and post-failure readings for leakage", "Avoids overlapping windows from the same event across splits", "Uses equipment and time-aware validation", "Evaluates useful early warning, false alarms, and operational cost"]),
  q("aiml-cross-med-035", "product", "Feed ranking with diversity",
    "A personalized content feed maximizes watch time but repeatedly shows near-identical content. How would you add diversity without destroying relevance?",
    ["ranking", "recommender-systems", "multi-objective-optimization"], SOURCES.product,
    ["Defines relevance, diversity, novelty, satisfaction, and safety metrics", "Uses reranking, maximal marginal relevance, or constrained optimization", "Balances short-term engagement with long-term user outcomes", "Evaluates per-user and catalog exposure effects", "Runs online experiments with retention and quality guardrails"]),
  q("aiml-cross-med-036", "product", "Billion-vector retrieval",
    "Design approximate nearest-neighbor retrieval for one billion embeddings under a strict latency and memory budget.",
    ["embeddings", "approximate-nearest-neighbor", "ml-system-design"], SOURCES.product,
    ["Chooses an index family based on recall, updates, memory, and latency", "Discusses partitioning, quantization, graph indexes, or inverted files", "Uses representative query benchmarks and recall at k", "Handles embedding versioning, incremental updates, and deletion", "Uses filtering, reranking, caching, and capacity monitoring"]),
  q("aiml-cross-med-037", "product", "Multimodal content moderation",
    "Design a system to detect policy-violating posts where meaning depends jointly on image, text, and context.",
    ["multimodal-ml", "content-moderation", "responsible-ai"], SOURCES.product,
    ["Uses modality-specific encoders plus fusion or cross-attention", "Builds policy-aligned labels and handles context-dependent ambiguity", "Evaluates rare classes, severity, slices, and adversarial variants", "Uses cascades and human review based on confidence and risk", "Monitors policy changes, appeals, fairness, latency, and drift"]),
  q("aiml-cross-med-038", "product", "Privacy-preserving personalization",
    "A mobile product needs personalized predictions but cannot upload raw user data. Compare on-device inference and federated learning.",
    ["privacy", "federated-learning", "edge-ai"], SOURCES.product,
    ["Explains on-device inference versus decentralized training", "Discusses non-IID clients, communication, aggregation, and device availability", "Adds secure aggregation and differential privacy where needed", "Evaluates privacy, quality, fairness, power, and bandwidth", "Handles model updates, rollback, poisoning, and client compatibility"]),
  q("aiml-cross-med-039", "product", "Unstable distributed training",
    "A multi-GPU transformer training run occasionally diverges after several hours. Give a systematic debugging plan.",
    ["deep-learning", "distributed-training", "debugging"], SOURCES.product,
    ["Reproduces with deterministic seeds and captures loss, gradients, and batches", "Checks corrupt data, masking, mixed precision, and exploding gradients", "Validates synchronization, optimizer state, checkpoint restore, and communication", "Uses gradient clipping, stable schedules, and numerical safeguards carefully", "Bisects data, code, hardware, and scale while preserving evidence"]),
  q("aiml-cross-med-040", "product", "Medical model domain shift",
    "A medical-image model trained at one hospital loses accuracy at another hospital. How would you diagnose and respond to the domain shift?",
    ["computer-vision", "domain-shift", "healthcare-ai"], SOURCES.product,
    ["Checks acquisition devices, protocols, populations, labels, and prevalence", "Evaluates calibration and performance by clinically relevant subgroup", "Uses harmonization, adaptation, or representative retraining data", "Avoids unsafe unsupervised adaptation without outcome validation", "Uses prospective validation, uncertainty, review, and deployment monitoring"]),

  q("aiml-cross-med-041", "service", "Framing an ambiguous client problem",
    "A client says, 'Use AI to increase revenue,' and provides one month of retail data. How would you turn this into a responsible ML project plan?",
    ["problem-framing", "consulting", "applied-ml"], SOURCES.serviceFresher,
    ["Clarifies business decisions, users, constraints, and measurable outcomes", "Audits whether the available data supports a valid target and timeline", "Prioritizes descriptive baselines before predictive or generative solutions", "Proposes demand, segmentation, recommendation, or pricing hypotheses carefully", "Defines validation, experiment, risks, milestones, and a non-ML alternative"]),
  q("aiml-cross-med-042", "service", "Small-data client model",
    "A client requests a deep-learning churn model but has only 4,000 labeled records. How would you respond and design the solution?",
    ["model-selection", "small-data", "consulting"], SOURCES.serviceFresher,
    ["Explains sample-size, overfitting, and maintenance concerns directly", "Starts with logistic regression and tree-based baselines", "Uses regularization, careful cross-validation, and uncertainty estimates", "Improves target quality and feature design before model complexity", "Compares business value and recommends the simplest reliable solution"]),
  q("aiml-cross-med-043", "service", "Production handoff",
    "You built an ML proof of concept for a client. What artifacts and controls are needed so another team can operate it reliably in production?",
    ["mlops", "documentation", "production-ml"], SOURCES.service,
    ["Provides versioned code, data contracts, features, model artifacts, and environments", "Documents training, evaluation, assumptions, limitations, and ownership", "Automates tests, deployment, monitoring, retraining, and rollback", "Defines SLAs, incident procedures, access, privacy, and audit controls", "Runs knowledge transfer and validates reproducibility with the receiving team"]),
  q("aiml-cross-med-044", "service", "Moving a POC to production",
    "An LLM prototype works on 30 demo questions but must now serve thousands of employees. What gaps would you address before launch?",
    ["generative-ai", "mlops", "enterprise-ai"], SOURCES.service,
    ["Builds representative, adversarial, and unanswerable evaluation sets", "Adds retrieval quality, grounding, safety, and permission tests", "Designs scalable serving with latency, rate, cache, and cost controls", "Adds observability, feedback, versioning, fallback, and rollback", "Completes security, privacy, legal, and human-approval requirements"]),
  q("aiml-cross-med-045", "service", "Legacy migration data quality",
    "A client’s model degraded after migrating from a legacy data warehouse to a cloud platform. How would you determine whether the migration caused it?",
    ["data-quality", "cloud-migration", "debugging"], SOURCES.service,
    ["Compares schemas, row counts, keys, nulls, ranges, and snapshots", "Checks join cardinality, timezone, units, precision, and backfill differences", "Recomputes identical features on matched records and timestamps", "Replays the same model artifact on old and new pipelines", "Adds parity tests, lineage, reconciliation reports, and rollback criteria"]),
  q("aiml-cross-med-046", "service", "Inference cost under an SLA",
    "A client requires 99.9% availability and 150 ms p95 latency but has a strict cloud budget. How would you design the model-serving trade-off?",
    ["model-serving", "cloud-cost", "system-design"], SOURCES.service,
    ["Quantifies QPS, payloads, latency percentiles, availability, and quality needs", "Benchmarks smaller models, quantization, batching, caching, and hardware", "Uses autoscaling with warm capacity and realistic load tests", "Defines timeouts, graceful degradation, fallback, and multi-zone reliability", "Tracks cost per prediction alongside quality and SLOs"]),
  q("aiml-cross-med-047", "service", "Reusable solution across clients",
    "How would you build a reusable document-classification platform for several clients while supporting different taxonomies and preventing data leakage?",
    ["multi-tenancy", "nlp", "ml-platform"], SOURCES.service,
    ["Separates reusable pipeline components from tenant configuration", "Enforces tenant isolation in storage, training, serving, and logs", "Supports taxonomy mapping, custom thresholds, and tenant-specific evaluation", "Uses shared pretrained representations only under valid data agreements", "Versions deployments and monitors quality, cost, and drift per tenant"]),
  q("aiml-cross-med-048", "service", "Reliable structured LLM output",
    "An LLM must return a fixed JSON schema for downstream automation. How would you make parsing reliable and handle invalid or partial responses?",
    ["generative-ai", "structured-output", "reliability"], SOURCES.service,
    ["Uses schema-constrained generation or function calling where supported", "Validates every response with strict typed schemas", "Retries or repairs with bounded attempts and idempotency", "Treats missing, extra, unsafe, and semantically invalid values explicitly", "Monitors failure rates and uses fallback or human review for high-risk actions"]),
  q("aiml-cross-med-049", "service", "Monitoring contract",
    "Define a production monitoring contract for a client-facing classification model when true labels arrive only monthly.",
    ["model-monitoring", "consulting", "delayed-labels"], SOURCES.service,
    ["Defines data, feature, score, decision, latency, and availability checks", "Uses qualified proxy metrics without presenting them as ground truth", "Evaluates matured labels monthly by segment and model version", "Sets alert thresholds, owners, severity, and response runbooks", "Specifies retraining, rollback, reporting, audit, and change-management rules"]),
  q("aiml-cross-med-050", "service", "Explaining a model disagreement",
    "A client stakeholder rejects a model because one prediction contradicts their intuition. How would you investigate and communicate the result?",
    ["explainability", "stakeholder-management", "model-debugging"], SOURCES.serviceFresher,
    ["Treats the example as evidence to investigate rather than dismissing it", "Checks data, feature values, model version, and prediction reproducibility", "Uses local explanations with limitations and relevant comparison cases", "Connects behavior to aggregate validation, uncertainty, and business cost", "Corrects defects when found and agrees on review, override, and monitoring policy"]),
];

const m = (id, category, title, question, topics, source, options, answer, explanation) => ({
  id, category, title, question, topics, source, options, answer, explanation,
});

const mcqs = [
  m("aiml-cross-med-mcq-001", "ecommerce", "Ranking metric", "Which metric gives more credit when a relevant product appears nearer the top of a ranked search result?", ["learning-to-rank", "evaluation"], SOURCES.ecommerceRanking, ["NDCG", "RMSE", "Adjusted R-squared", "Silhouette score"], "A", "NDCG discounts relevance by rank, rewarding systems that place useful results near the top."),
  m("aiml-cross-med-mcq-002", "ecommerce", "Implicit feedback", "Why is a missing click usually not a reliable negative label for a recommendation model?", ["recommender-systems", "labeling"], SOURCES.ecommerce, ["The item may never have been exposed to the user", "All unclicked items are duplicates", "Clicks are continuous variables", "Negative labels require images"], "A", "A user cannot click an item they did not see, so non-clicks mix disinterest with lack of exposure."),
  m("aiml-cross-med-mcq-003", "ecommerce", "Item cold start", "Which signal is most useful for recommending a newly listed product with no interactions?", ["recommender-systems", "cold-start"], SOURCES.ecommerce, ["Product-content attributes and embeddings", "Its historical click count", "Its historical purchase count", "Its mature return rate"], "A", "Content representations are available before interaction history and support similarity to known items."),
  m("aiml-cross-med-mcq-004", "ecommerce", "MAPE limitation", "Why can MAPE be unsuitable for forecasting demand for products with many zero-sales periods?", ["forecasting", "metrics"], SOURCES.ecommerce, ["It is undefined or unstable when actual demand is zero or near zero", "It always ignores seasonality", "It can evaluate only classifiers", "It requires image features"], "A", "MAPE divides by actual values, causing undefined or extreme errors around zero."),
  m("aiml-cross-med-mcq-005", "ecommerce", "Recommendation experiment", "A recommendation A/B test raises CTR but lowers completed purchases. What is the best conclusion?", ["experimentation", "recommendation"], SOURCES.ecommerceRanking, ["Do not launch based on CTR alone; inspect downstream objectives and guardrails", "Launch because CTR is always the primary business outcome", "The randomization must be invalid", "Offline NDCG must have increased"], "A", "CTR is a proxy; launch decisions should include conversion and other downstream customer outcomes."),

  m("aiml-cross-med-mcq-006", "cyber", "SOC threshold", "Lowering the threshold for sending security alerts to analysts will usually have which effect?", ["cybersecurity", "thresholding"], SOURCES.cyber, ["Higher recall and lower precision", "Lower recall and higher precision", "Perfect calibration", "No change in alert volume"], "A", "A lower threshold flags more cases, usually finding more attacks while producing more false positives."),
  m("aiml-cross-med-mcq-007", "cyber", "Autoencoder anomaly score", "In an autoencoder-based anomaly detector, what commonly serves as the anomaly score?", ["anomaly-detection", "deep-learning"], SOURCES.cyberSystems, ["Reconstruction error", "Training-set size", "Number of labels", "Learning-rate decay"], "A", "Inputs unlike learned normal patterns tend to reconstruct poorly, producing larger reconstruction error."),
  m("aiml-cross-med-mcq-008", "cyber", "Attack concept drift", "Which example best represents concept drift in phishing detection?", ["cybersecurity", "concept-drift"], SOURCES.cyber, ["The relationship between email signals and maliciousness changes as attackers adapt", "A column is renamed in one batch", "The inference server runs out of memory", "The training file is compressed"], "A", "Concept drift changes the mapping between observed features and the target behavior."),
  m("aiml-cross-med-mcq-009", "cyber", "Active learning", "Which unlabeled security event is generally most valuable to send for analyst labeling in uncertainty-based active learning?", ["active-learning", "cybersecurity"], SOURCES.cyber, ["An event near the model’s decision boundary", "The easiest event the model already predicts confidently", "A duplicate of every training example", "A randomly generated empty event"], "A", "Uncertain boundary cases can provide more information per expensive analyst label."),
  m("aiml-cross-med-mcq-010", "cyber", "Alert capacity metric", "A SOC can inspect only 200 alerts daily. Which metric directly measures the usefulness of the model’s daily queue?", ["ranking", "cybersecurity"], SOURCES.cyber, ["Precision at 200", "Training accuracy", "Mean squared feature value", "Parameter count"], "A", "Precision at the review cutoff measures how many investigated alerts are truly actionable."),

  m("aiml-cross-med-mcq-011", "enterprise", "RAG permissions", "Where should document authorization be enforced in a permission-aware RAG system?", ["rag", "access-control"], SOURCES.enterpriseGenAi, ["Before or during retrieval so unauthorized chunks never enter model context", "Only after displaying the generated answer", "Only during model pretraining", "Only in the browser cache"], "A", "Preventing unauthorized retrieval reduces both direct leakage and leakage through generated summaries."),
  m("aiml-cross-med-mcq-012", "enterprise", "LoRA purpose", "What is the main purpose of LoRA when adapting a large language model?", ["generative-ai", "fine-tuning"], SOURCES.enterpriseGenAi, ["Train small low-rank adapter parameters while keeping most base weights frozen", "Increase the tokenizer vocabulary without training", "Replace retrieval with SQL", "Guarantee factual output"], "A", "LoRA provides parameter-efficient adaptation by learning low-rank updates instead of all model weights."),
  m("aiml-cross-med-mcq-013", "enterprise", "Tenant leakage", "Which practice most directly prevents cross-tenant data leakage in a shared feature store?", ["multi-tenancy", "feature-store"], SOURCES.enterprise, ["Tenant-scoped keys plus server-side authorization", "Adding the tenant name to a dashboard title", "Using one global cache key", "Removing model versioning"], "A", "Storage keys and authorization must enforce tenant boundaries independently of UI behavior."),
  m("aiml-cross-med-mcq-014", "enterprise", "Online inference choice", "Which workload most strongly requires online rather than nightly batch inference?", ["model-serving", "enterprise-ai"], SOURCES.enterprise, ["Routing a newly submitted support ticket immediately", "Generating a monthly archived report", "Retraining a quarterly model", "Computing last year’s aggregate revenue"], "A", "Immediate routing requires a prediction based on a newly arriving event under an interactive latency target."),
  m("aiml-cross-med-mcq-015", "enterprise", "Offline-online parity", "What problem do shared feature definitions primarily reduce?", ["feature-store", "production-ml"], SOURCES.enterprise, ["Training-serving skew", "Label class imbalance", "Model explainability", "GPU fragmentation"], "A", "Using consistent transformations for historical and live features reduces differences between training and serving."),

  m("aiml-cross-med-mcq-016", "product", "CNN inductive bias", "Which property helps convolutional neural networks model images efficiently?", ["computer-vision", "deep-learning"], SOURCES.product, ["Local connectivity and shared weights", "A separate parameter for every image pixel and position", "Mandatory recurrence over rows", "Inability to represent edges"], "A", "Convolutions reuse local filters across positions, exploiting spatial structure with fewer parameters."),
  m("aiml-cross-med-mcq-017", "product", "Quantization", "What does post-training INT8 quantization primarily change?", ["model-compression", "edge-ai"], SOURCES.product, ["It represents weights and often activations with lower precision", "It adds more transformer layers", "It creates additional training labels", "It converts classification into clustering"], "A", "Lower-precision representations reduce model size and may accelerate supported hardware, with possible quality loss."),
  m("aiml-cross-med-mcq-018", "product", "Embedding similarity", "For L2-normalized embeddings, maximizing cosine similarity is equivalent to which ranking?", ["embeddings", "similarity-search"], SOURCES.product, ["Minimizing Euclidean distance", "Maximizing vector dimension", "Minimizing dataset size", "Maximizing cross-entropy directly"], "A", "For unit vectors, squared Euclidean distance equals 2 minus 2 times cosine similarity."),
  m("aiml-cross-med-mcq-019", "product", "Batch normalization inference", "During inference, batch normalization normally uses which statistics?", ["deep-learning", "model-serving"], SOURCES.product, ["Stored running mean and variance", "Only the current single example’s exact mean and variance", "Random statistics for augmentation", "The target-label distribution"], "A", "Inference uses learned affine parameters and running statistics accumulated during training."),
  m("aiml-cross-med-mcq-020", "product", "Data parallel training", "In synchronous data-parallel training, what is commonly synchronized across workers each step?", ["distributed-training", "deep-learning"], SOURCES.product, ["Gradients or parameter updates", "Raw customer records between unrelated datasets", "Only class names", "The validation labels into training"], "A", "Workers process different mini-batches and synchronize gradients or updates to maintain a shared model."),

  m("aiml-cross-med-mcq-021", "service", "Leakage-free preprocessing", "When using cross-validation, where should a standard scaler be fitted?", ["validation", "data-leakage"], SOURCES.serviceFresher, ["Separately on each training fold", "Once on the entire dataset before splitting", "Only on each validation fold", "After final predictions"], "A", "Fitting within each training fold prevents validation information from influencing preprocessing."),
  m("aiml-cross-med-mcq-022", "service", "Baseline value", "Why should an ML consulting project establish a simple baseline first?", ["model-selection", "consulting"], SOURCES.serviceFresher, ["To prove added complexity produces measurable value", "To guarantee deep learning wins", "To avoid defining metrics", "To eliminate production monitoring"], "A", "A baseline reveals whether a complex approach offers enough incremental value to justify its cost and risk."),
  m("aiml-cross-med-mcq-023", "service", "Model registry", "What is the primary role of a model registry?", ["mlops", "model-governance"], SOURCES.service, ["Track versioned model artifacts and their metadata or lifecycle", "Store only raw UI screenshots", "Replace all source control", "Generate ground-truth labels automatically"], "A", "A registry links deployable model versions to lineage, metrics, approvals, and lifecycle state."),
  m("aiml-cross-med-mcq-024", "service", "Structured LLM output", "Which approach most directly improves syntactic reliability when an LLM must return a fixed JSON structure?", ["generative-ai", "structured-output"], SOURCES.service, ["Schema-constrained output or function calling with validation", "Raising temperature to its maximum", "Removing all field definitions", "Accepting every response without parsing"], "A", "Constrained generation plus strict schema validation reduces malformed outputs and detects contract violations."),
  m("aiml-cross-med-mcq-025", "service", "Data drift", "Which observation is direct evidence of data drift but not necessarily concept drift?", ["model-monitoring", "drift"], SOURCES.service, ["A production feature distribution changes from the training baseline", "The relationship between features and labels changes", "A stakeholder changes the project deadline", "The model file has the same checksum"], "A", "A shift in P(X) is data drift; it does not by itself prove that P(Y|X) changed."),
];

const companyTagsFor = (category, index) => {
  const companies = COMPANIES[category];
  return Array.from({ length: 4 }, (_, offset) => companies[(index * 4 + offset) % companies.length]);
};

const rubricFor = (criteria) =>
  criteria.map((text, index) => ({
    text,
    category: ["problemFraming", "technicalReasoning", "tradeoffs", "evaluation", "productionReadiness"][index],
    importance: index < 3 ? "mustHave" : "goodToHave",
    expectedAnswerMode: "conceptual",
  }));

const csvEscape = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;
const writeCsv = async (fileName, columns, rows) => {
  const output = [
    columns.map(csvEscape).join(","),
    ...rows.map((row) => columns.map((column) => csvEscape(row[column])).join(",")),
  ].join("\n");
  await fs.writeFile(path.join(outputDir, fileName), `${output}\n`, "utf8");
};

await fs.mkdir(outputDir, { recursive: true });

const categoryOffsets = Object.fromEntries(Object.keys(COMPANIES).map((category) => [category, 0]));
const tagsForItem = (item) => {
  const index = categoryOffsets[item.category]++;
  return companyTagsFor(item.category, index);
};

await writeCsv(
  "ai-ml-cross-industry-medium-rubric-50.csv",
  ["questionId", "title", "question", "companyTags", "topics", "subtopics", "url", "rubric", "source", "verified", "qualityScore"],
  descriptive.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: tagsForItem(item).join("|"),
    topics: item.topics.join("|"),
    subtopics: item.topics.slice(1).join("|"),
    url: item.source,
    rubric: JSON.stringify(rubricFor(item.criteria)),
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

await writeCsv(
  "ai-ml-cross-industry-medium-mcq-25.csv",
  ["questionId", "title", "question", "companyTags", "topics", "subtopics", "url", "optionA", "optionB", "optionC", "optionD", "correctOptionId", "explanation", "source", "verified", "qualityScore"],
  mcqs.map((item) => ({
    questionId: item.id,
    title: item.title,
    question: item.question,
    companyTags: tagsForItem(item).join("|"),
    topics: item.topics.join("|"),
    subtopics: item.topics.slice(1).join("|"),
    url: item.source,
    optionA: item.options[0],
    optionB: item.options[1],
    optionC: item.options[2],
    optionD: item.options[3],
    correctOptionId: item.answer,
    explanation: item.explanation,
    source: "public_interview_pattern_curated",
    verified: "false",
    qualityScore: "0.9",
  }))
);

const categoryCounts = (items) =>
  items.reduce((counts, item) => ({ ...counts, [item.category]: (counts[item.category] || 0) + 1 }), {});

console.log(JSON.stringify({
  outputDir,
  rubricRows: descriptive.length,
  mcqRows: mcqs.length,
  rubricByCategory: categoryCounts(descriptive),
  mcqByCategory: categoryCounts(mcqs),
}));
