/**
 * Writes scripts/data/striver-sde-sheet/bulk-part-01.json … bulk-part-05.json
 * (20 questions each, 100 total). Run from backend root:
 *   node scripts/regenerateStriverSdeBulk.mjs
 *
 * Source label: striver_sde_sheet. Difficulties: only medium | hard.
 * Does not touch MongoDB.
 */
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, "data", "striver-sde-sheet");

const SRC = { source: "striver_sde_sheet", verified: false, qualityScore: 0.84 };

function starter(sig) {
  const s = sig.trim();
  if (s.endsWith(":")) return `${s}\n    pass\n`;
  return `${s}:\n    pass\n`;
}

/** @param {[object, unknown, boolean][]} rows [input, expectedOutput, isHidden] */
function tc(rows) {
  return rows.map(([input, expectedOutput, isHidden]) => ({
    input,
    expectedOutput,
    isHidden,
    weight: 1,
  }));
}

function doc(questionId, title, question, difficulty, topics, sig, cases, complexity) {
  return {
    questionId,
    title,
    question,
    roundType: "DSA",
    difficulty,
    topics,
    subtopics: [],
    evaluationStrategy: "code_execution",
    dsaMetadata: {
      supportedLanguages: ["python"],
      functionSignature: sig,
      starterCode: starter(sig),
    },
    testCases: tc(cases),
    rubric: [
      {
        text: "Implements a correct algorithm for the stated constraints.",
        category: "correctness",
        importance: "mustHave",
        expectedAnswerMode: "code",
      },
      {
        text: "Meets expected time/space complexity for the intended approach.",
        category: "complexity",
        importance: "goodToHave",
        expectedAnswerMode: "conceptual",
      },
    ],
    complexity: complexity || { time: "", space: "" },
    sourceMetadata: { ...SRC },
  };
}

/** 100 rows: [idSuffix, title, difficulty, topics, sig, question, cases, complexity?] */
const RAW = [
  [
    "bulk-001",
    "Longest Substring Without Repeating Characters",
    "medium",
    ["hashing", "strings", "sliding window"],
    "def length_of_longest_substring(s):",
    "Given a string `s`, return the length of the longest substring without repeating characters.",
    [
      [{ s: "abcabcbb" }, 3, false],
      [{ s: "bbbbb" }, 1, false],
      [{ s: "pwwkew" }, 3, true],
      [{ s: "" }, 0, true],
    ],
    { time: "O(n)", space: "O(min(n,m))" },
  ],
  [
    "bulk-002",
    "Reverse Words in a String",
    "medium",
    ["strings", "two pointers"],
    "def reverse_words(s):",
    "Given a string `s`, reverse the order of words. Words are non-empty sequences separated by spaces. Trim leading/trailing spaces and collapse internal spaces to single spaces in the output.",
    [
      [{ s: "the sky is blue" }, "blue is sky the", false],
      [{ s: "  hello world  " }, "world hello", false],
      [{ s: "a good   example" }, "example good a", true],
      [{ s: "word" }, "word", true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-003",
    "Longest Palindromic Substring Length",
    "medium",
    ["strings", "dynamic programming"],
    "def longest_palindrome_length(s):",
    "Given a string `s`, return the length of its longest palindromic substring.",
    [
      [{ s: "babad" }, 3, false],
      [{ s: "cbbd" }, 2, false],
      [{ s: "a" }, 1, true],
      [{ s: "ac" }, 1, true],
    ],
    { time: "O(n^2)", space: "O(1)" },
  ],
  [
    "bulk-004",
    "Majority Element II",
    "medium",
    ["arrays", "hashing"],
    "def majority_elements(nums):",
    "Given an integer array `nums` of length `n`, return all elements that appear strictly more than `floor(n/3)` times. Return the list sorted in ascending order.",
    [
      [{ nums: [3, 2, 3] }, [3], false],
      [{ nums: [1, 2] }, [1, 2], false],
      [{ nums: [1, 1, 1, 2, 2, 2, 3, 3] }, [1, 2], true],
      [{ nums: [0, 0, 0] }, [0], true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-005",
    "Find Peak Element",
    "medium",
    ["arrays", "binary search"],
    "def find_peak_element(nums):",
    "Given `nums`, find any index `i` where `nums[i] > nums[i+1]` and `nums[i] > nums[i-1]` (use `-inf` outside bounds). Return such an index.",
    [
      [{ nums: [1, 2, 3, 1] }, 2, false],
      [{ nums: [1, 2, 1, 3, 5, 6, 4] }, 5, false],
      [{ nums: [1] }, 0, true],
      [{ nums: [1, 2] }, 1, true],
    ],
    { time: "O(log n)", space: "O(1)" },
  ],
  [
    "bulk-006",
    "Search Insert Position",
    "medium",
    ["arrays", "binary search"],
    "def search_insert(nums, target):",
    "Given sorted distinct `nums` and `target`, return the index where `target` exists, or the index where it would be inserted to keep order.",
    [
      [{ nums: [1, 3, 5, 6], target: 5 }, 2, false],
      [{ nums: [1, 3, 5, 6], target: 2 }, 1, false],
      [{ nums: [1, 3, 5, 6], target: 7 }, 4, true],
      [{ nums: [1, 3, 5, 6], target: 0 }, 0, true],
    ],
    { time: "O(log n)", space: "O(1)" },
  ],
  [
    "bulk-007",
    "Sqrt(x)",
    "medium",
    ["math", "binary search"],
    "def my_sqrt(x):",
    "Given non-negative integer `x`, return the integer part of `sqrt(x)` truncated.",
    [
      [{ x: 4 }, 2, false],
      [{ x: 8 }, 2, false],
      [{ x: 0 }, 0, true],
      [{ x: 15 }, 3, true],
    ],
    { time: "O(log x)", space: "O(1)" },
  ],
  [
    "bulk-008",
    "Pow(x, n)",
    "medium",
    ["recursion", "math"],
    "def my_pow(x, n):",
    "Implement `x` raised to integer `n`. `n` can be negative.",
    [
      [{ x: 2.0, n: 10 }, 1024.0, false],
      [{ x: 2.1, n: 3 }, 9.261, false],
      [{ x: 2.0, n: -2 }, 0.25, true],
      [{ x: 1.0, n: 1000000 }, 1.0, true],
    ],
    { time: "O(log |n|)", space: "O(1)" },
  ],
  [
    "bulk-009",
    "Count Primes",
    "medium",
    ["math", "number theory"],
    "def count_primes(n):",
    "Given `n`, return the number of prime numbers strictly less than `n`.",
    [
      [{ n: 10 }, 4, false],
      [{ n: 0 }, 0, false],
      [{ n: 1 }, 0, true],
      [{ n: 100 }, 25, true],
    ],
    { time: "O(n log log n)", space: "O(n)" },
  ],
  [
    "bulk-010",
    "Jump Game",
    "medium",
    ["arrays", "greedy"],
    "def can_jump(nums):",
    "Given `nums` where `nums[i]` is max jump length from `i`, return whether you can reach the last index starting at 0.",
    [
      [{ nums: [2, 3, 1, 1, 4] }, true, false],
      [{ nums: [3, 2, 1, 0, 4] }, false, false],
      [{ nums: [0] }, true, true],
      [{ nums: [1, 0] }, true, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-011",
    "Jump Game II",
    "hard",
    ["arrays", "greedy"],
    "def jump(nums):",
    "Given `nums` as in Jump Game (always reachable last), return the minimum jumps to reach last index.",
    [
      [{ nums: [2, 3, 1, 1, 4] }, 2, false],
      [{ nums: [2, 3, 0, 1, 4] }, 2, false],
      [{ nums: [1, 1, 1, 1] }, 3, true],
      [{ nums: [1, 2] }, 1, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-012",
    "Gas Station",
    "medium",
    ["arrays", "greedy"],
    "def can_complete_circuit(gas, cost):",
    "Given `gas[i]` and `cost[i]` for a circular route, return starting station index to complete circuit once, or `-1` if impossible.",
    [
      [{ gas: [1, 2, 3, 4, 5], cost: [3, 4, 5, 1, 2] }, 3, false],
      [{ gas: [2, 3, 4], cost: [3, 4, 3] }, -1, false],
      [{ gas: [5, 1, 2, 3, 5], cost: [4, 4, 3, 4, 5] }, 4, true],
      [{ gas: [3, 1, 1], cost: [1, 2, 2] }, 0, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-013",
    "Candy",
    "hard",
    ["arrays", "greedy"],
    "def candy(ratings):",
    "`n` children in a line with `ratings`. Give each at least one candy; higher rating than neighbor must get more candies. Return minimum total candies.",
    [
      [{ ratings: [1, 0, 2] }, 5, false],
      [{ ratings: [1, 2, 2] }, 4, false],
      [{ ratings: [1, 3, 2, 2, 1] }, 7, true],
      [{ ratings: [1, 2, 87, 87, 87, 1] }, 9, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-014",
    "Trapping Rain Water",
    "hard",
    ["arrays", "two pointers", "stack"],
    "def trap(height):",
    "Given non-negative elevation map `height`, compute trapped rain water units between bars.",
    [
      [{ height: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] }, 6, false],
      [{ height: [4, 2, 0, 3, 2, 5] }, 9, false],
      [{ height: [1, 0, 1] }, 1, true],
      [{ height: [3, 0, 2, 0, 4] }, 7, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-015",
    "Container With Most Water",
    "medium",
    ["arrays", "two pointers"],
    "def max_area(height):",
    "Given vertical lines at x=i with height `height[i]`, find two lines that with x-axis form a container holding max water.",
    [
      [{ height: [1, 8, 6, 2, 5, 4, 8, 3, 7] }, 49, false],
      [{ height: [1, 1] }, 1, false],
      [{ height: [2, 3, 4, 5, 18, 17, 6] }, 17, true],
      [{ height: [1, 2, 1] }, 2, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-016",
    "3Sum Closest",
    "medium",
    ["arrays", "two pointers", "sorting"],
    "def three_sum_closest(nums, target):",
    "Given integer array `nums` and `target`, find three integers in `nums` whose sum is closest to `target`. Return that sum.",
    [
      [{ nums: [-1, 2, 1, -4], target: 1 }, 2, false],
      [{ nums: [0, 0, 0], target: 1 }, 0, false],
      [{ nums: [1, 1, 1, 0], target: 100 }, 3, true],
      [{ nums: [4, 5, 6], target: 0 }, 15, true],
    ],
    { time: "O(n^2)", space: "O(1)" },
  ],
  [
    "bulk-017",
    "Letter Combinations of a Phone Number",
    "medium",
    ["strings", "backtracking"],
    "def letter_combinations(digits):",
    "Given `digits` containing digits 2-9, return all letter combinations the number could represent on a phone pad. Return list sorted lexicographically.",
    [
      [{ digits: "23" }, ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"], false],
      [{ digits: "" }, [], false],
      [{ digits: "2" }, ["a", "b", "c"], true],
      [{ digits: "79" }, ["pw", "px", "py", "pz", "qw", "qx", "qy", "qz", "rw", "rx", "ry", "rz", "sw", "sx", "sy", "sz"], true],
    ],
    { time: "O(4^n)", space: "O(4^n)" },
  ],
  [
    "bulk-018",
    "Combination Sum",
    "medium",
    ["arrays", "backtracking"],
    "def combination_sum(candidates, target):",
    "Given distinct positive `candidates` and `target`, return all unique combinations that sum to `target` (reuse allowed). Each combination sorted ascending; outer list sorted lexicographically.",
    [
      [{ candidates: [2, 3, 6, 7], target: 7 }, [[7], [2, 2, 3]], false],
      [{ candidates: [2, 3, 5], target: 8 }, [[2, 3, 3], [3, 5]], false],
      [{ candidates: [2], target: 1 }, [], true],
      [{ candidates: [1], target: 2 }, [[1, 1]], true],
    ],
    { time: "O(2^n)", space: "O(target)" },
  ],
  [
    "bulk-019",
    "Generate Parentheses",
    "medium",
    ["strings", "backtracking"],
    "def generate_parenthesis(n):",
    "Given `n` pairs of parentheses, return all well-formed strings of length `2n`, sorted lexicographically.",
    [
      [{ n: 3 }, ["((()))", "(()())", "(())()", "()(())", "()()()"], false],
      [{ n: 1 }, ["()"], false],
      [{ n: 2 }, ["(())", "()()"], true],
      [{ n: 0 }, [""], true],
    ],
    { time: "O(4^n / sqrt(n))", space: "O(4^n / sqrt(n))" },
  ],
  [
    "bulk-020",
    "Permutation in String",
    "medium",
    ["strings", "sliding window", "hashing"],
    "def check_inclusion(s1, s2):",
    "Return `True` if some permutation of `s1` is a substring of `s2`, else `False`.",
    [
      [{ s1: "ab", s2: "eidbaooo" }, true, false],
      [{ s1: "ab", s2: "eidboaoo" }, false, false],
      [{ s1: "adc", s2: "dcda" }, true, true],
      [{ s1: "hello", s2: "ooolleoooleh" }, false, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-021",
    "Minimum Window Substring",
    "hard",
    ["strings", "sliding window", "hashing"],
    "def min_window(s, t):",
    "Return the minimum window substring of `s` containing all characters of `t` with multiplicity. If none, return empty string.",
    [
      [{ s: "ADOBECODEBANC", t: "ABC" }, "BANC", false],
      [{ s: "a", t: "a" }, "a", false],
      [{ s: "a", t: "aa" }, "", true],
      [{ s: "bbaa", t: "aba" }, "baa", true],
    ],
    { time: "O(|s|+|t|)", space: "O(|t|)" },
  ],
  [
    "bulk-022",
    "Sliding Window Maximum",
    "hard",
    ["arrays", "deque", "sliding window"],
    "def max_sliding_window(nums, k):",
    "Return max of each contiguous subarray of size `k` in order.",
    [
      [{ nums: [1, 3, -1, -3, 5, 3, 6, 7], k: 3 }, [3, 3, 5, 5, 6, 7], false],
      [{ nums: [1], k: 1 }, [1], false],
      [{ nums: [1, -1], k: 1 }, [1, -1], true],
      [{ nums: [9, 11], k: 2 }, [11], true],
    ],
    { time: "O(n)", space: "O(k)" },
  ],
  [
    "bulk-023",
    "Largest Rectangle in Histogram",
    "hard",
    ["arrays", "stack"],
    "def largest_rectangle_area(heights):",
    "Given bar heights, return largest rectangle area in histogram.",
    [
      [{ heights: [2, 1, 5, 6, 2, 3] }, 10, false],
      [{ heights: [2, 4] }, 4, false],
      [{ heights: [1] }, 1, true],
      [{ heights: [0, 9] }, 9, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-024",
    "Maximal Rectangle",
    "hard",
    ["arrays", "stack", "dynamic programming"],
    "def maximal_rectangle(matrix):",
    "`matrix` is list of equal-length strings of `'0'`/`'1'`. Return area of largest rectangle containing only ones.",
    [
      [{ matrix: ["10100", "10111", "11111", "10010"] }, 6, false],
      [{ matrix: ["0"] }, 0, false],
      [{ matrix: ["1"] }, 1, true],
      [{ matrix: ["11", "11"] }, 4, true],
    ],
    { time: "O(m n)", space: "O(n)" },
  ],
  [
    "bulk-025",
    "Median of Two Sorted Arrays",
    "hard",
    ["arrays", "binary search"],
    "def find_median_sorted_arrays(nums1, nums2):",
    "Given two sorted arrays, return the median of the combined multiset (as float; for even length use average of two middle values).",
    [
      [{ nums1: [1, 3], nums2: [2] }, 2.0, false],
      [{ nums1: [1, 2], nums2: [3, 4] }, 2.5, false],
      [{ nums1: [], nums2: [1] }, 1.0, true],
      [{ nums1: [2], nums2: [] }, 2.0, true],
    ],
    { time: "O(log(min(m,n)))", space: "O(1)" },
  ],
  [
    "bulk-026",
    "Word Search",
    "medium",
    ["matrix", "backtracking"],
    "def exist(board, word):",
    "`board` is list of strings of same length (letters). Return whether `word` exists as path moving up/down/left/right without reusing a cell.",
    [
      [{ board: ["ABCE", "SFCS", "ADEE"], word: "ABCCED" }, true, false],
      [{ board: ["ABCE", "SFCS", "ADEE"], word: "SEE" }, true, false],
      [{ board: ["ABCE", "SFCS", "ADEE"], word: "ABCB" }, false, true],
      [{ board: ["a"], word: "a" }, true, true],
    ],
    { time: "O(m n * 3^L)", space: "O(L)" },
  ],
  [
    "bulk-027",
    "Number of Islands",
    "medium",
    ["matrix", "dfs", "bfs"],
    "def num_islands(grid):",
    "`grid` is list of strings `'1'` land `'0'` water. Return number of islands (4-dir connected land).",
    [
      [{ grid: ["11110", "11010", "11000", "00000"] }, 1, false],
      [{ grid: ["11000", "11000", "00100", "00011"] }, 3, false],
      [{ grid: ["1"] }, 1, true],
      [{ grid: ["0"] }, 0, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-028",
    "Rotting Oranges",
    "medium",
    ["matrix", "bfs"],
    "def oranges_rotting(grid):",
    "`grid` is list of strings: `0` empty, `1` fresh, `2` rotten. Each minute rotten spreads to 4-adjacent fresh. Return minutes until no fresh, or `-1` if impossible.",
    [
      [{ grid: ["23", "12"] }, 1, false],
      [{ grid: ["11", "11", "00"] }, -1, false],
      [{ grid: ["0"] }, 0, true],
      [{ grid: ["22", "11", "11"] }, 2, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-029",
    "Course Schedule",
    "medium",
    ["graph", "topological sort"],
    "def can_finish(num_courses, prerequisites):",
    "`prerequisites` is list of `[a,b]` meaning take `b` before `a`. Return whether all `num_courses` can be finished.",
    [
      [{ num_courses: 2, prerequisites: [[1, 0]] }, true, false],
      [{ num_courses: 2, prerequisites: [[1, 0], [0, 1]] }, false, false],
      [{ num_courses: 1, prerequisites: [] }, true, true],
      [{ num_courses: 3, prerequisites: [[1, 0], [2, 1]] }, true, true],
    ],
    { time: "O(V+E)", space: "O(V+E)" },
  ],
  [
    "bulk-030",
    "Course Schedule II",
    "medium",
    ["graph", "topological sort"],
    "def find_order(num_courses, prerequisites):",
    "Return any valid order of course ids to finish all courses, or empty list if impossible.",
    [
      [{ num_courses: 2, prerequisites: [[1, 0]] }, [0, 1], false],
      [{ num_courses: 4, prerequisites: [[1, 0], [2, 0], [3, 1], [3, 2]] }, [0, 1, 2, 3], false],
      [{ num_courses: 1, prerequisites: [] }, [0], true],
      [{ num_courses: 2, prerequisites: [[0, 1], [1, 0]] }, [], true],
    ],
    { time: "O(V+E)", space: "O(V+E)" },
  ],
  [
    "bulk-031",
    "Clone Graph",
    "medium",
    ["graph", "hashing", "dfs"],
    "def clone_graph(adj):",
    "Undirected graph with `n` nodes labeled `1..n`. Input `adj` is list of `n` lists: neighbors of node `i+1` are `adj[i]`. Return **adjacency list** of the clone (same structure, deep copy).",
    [
      [{ adj: [[2, 4], [1, 3], [2, 4], [1, 3]] }, [[2, 4], [1, 3], [2, 4], [1, 3]], false],
      [{ adj: [[]] }, [[]], false],
      [{ adj: [[2], [1]] }, [[2], [1]], true],
      [{ adj: [[2, 3], [1, 3], [1, 2]] }, [[2, 3], [1, 3], [1, 2]], true],
    ],
    { time: "O(V+E)", space: "O(V+E)" },
  ],
  [
    "bulk-032",
    "Pacific Atlantic Water Flow",
    "medium",
    ["matrix", "dfs"],
    "def pacific_atlantic(heights):",
    "`heights` is list of equal-length lists of ints. Water flows from cell to 4-neighbor if neighbor height <= current. Pacific touches top/left; Atlantic bottom/right. Return list of `[r,c]` that can reach both, sorted by row then column.",
    [
      [
        {
          heights: [
            [1, 2, 2, 3, 5],
            [3, 2, 3, 4, 4],
            [2, 4, 5, 3, 1],
            [6, 7, 1, 4, 5],
            [5, 1, 1, 2, 4],
          ],
        },
        [
          [0, 4],
          [1, 3],
          [1, 4],
          [2, 2],
          [3, 0],
          [3, 1],
          [4, 0],
        ],
        false,
      ],
      [{ heights: [[1]] }, [[0, 0]], false],
      [{ heights: [[1, 1], [1, 1]] }, [[0, 0], [0, 1], [1, 0], [1, 1]], true],
      [{ heights: [[3, 3], [3, 3]] }, [[0, 0], [0, 1], [1, 0], [1, 1]], true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-033",
    "Cheapest Flights Within K Stops",
    "hard",
    ["graph", "dynamic programming"],
    "def find_cheapest_price(n, flights, src, dst, k):",
    "`flights` is list of `[from,to,price]`. Return cheapest price from `src` to `dst` with at most `k` stops, or `-1` if unreachable.",
    [
      [{ n: 4, flights: [[0, 1, 100], [1, 2, 100], [2, 0, 100], [1, 3, 600], [2, 3, 200]], src: 0, dst: 3, k: 1 }, 700, false],
      [{ n: 3, flights: [[0, 1, 100], [1, 2, 100], [0, 2, 500]], src: 0, dst: 2, k: 0 }, 500, false],
      [{ n: 3, flights: [[0, 1, 100], [1, 2, 100], [0, 2, 500]], src: 0, dst: 2, k: 1 }, 200, true],
      [{ n: 2, flights: [[1, 0, 5]], src: 0, dst: 1, k: 1 }, -1, true],
    ],
    { time: "O(E k)", space: "O(n k)" },
  ],
  [
    "bulk-034",
    "Network Delay Time",
    "medium",
    ["graph", "shortest path"],
    "def network_delay_time(times, n, k):",
    "`times` is list `[u,v,w]` directed edge delay. Signal starts at node `k`. Return time until all `n` nodes receive signal, or `-1` if impossible.",
    [
      [{ times: [[2, 1, 1], [2, 3, 1], [3, 4, 1]], n: 4, k: 2 }, 2, false],
      [{ times: [[1, 2, 1]], n: 2, k: 1 }, 1, false],
      [{ times: [[1, 2, 1]], n: 2, k: 2 }, -1, true],
      [{ times: [[1, 2, 1], [2, 3, 2], [1, 3, 4]], n: 3, k: 1 }, 3, true],
    ],
    { time: "O(E log V)", space: "O(V+E)" },
  ],
  [
    "bulk-035",
    "Course Schedule IV",
    "hard",
    ["graph", "floyd warshall"],
    "def check_if_prerequisite(num_courses, prerequisites, queries):",
    "For each query `[u,v]`, return whether `u` is prerequisite of `v` (direct or transitive). Return list of booleans in query order.",
    [
      [
        {
          num_courses: 2,
          prerequisites: [[1, 0]],
          queries: [
            [0, 1],
            [1, 0],
          ],
        },
        [false, true],
        false,
      ],
      [{ num_courses: 2, prerequisites: [], queries: [[1, 0], [0, 1]] }, [false, false], false],
      [{ num_courses: 3, prerequisites: [[1, 2]], queries: [[1, 0]] }, [false], true],
      [{ num_courses: 3, prerequisites: [[1, 0], [2, 0]], queries: [[2, 1]] }, [false], true],
    ],
    { time: "O(n^3 + q)", space: "O(n^2)" },
  ],
  [
    "bulk-036",
    "Alien Dictionary",
    "hard",
    ["graph", "topological sort"],
    "def alien_order(words):",
    "`words` is sorted list in alien language lex order. Return any valid order of letters used, or empty string if invalid.",
    [
      [{ words: ["wrt", "wrf", "er", "ett", "rftt"] }, "wertf", false],
      [{ words: ["z", "x"] }, "zx", false],
      [{ words: ["z", "x", "z"] }, "", true],
      [{ words: ["ab", "adc", "ad"] }, "", true],
    ],
    { time: "O(C)", space: "O(1)" },
  ],
  [
    "bulk-037",
    "Critical Connections in a Network",
    "hard",
    ["graph", "tarjan"],
    "def critical_connections(n, connections):",
    "Return list of bridges `[u,v]` with `u < v`, sorted lexicographically by pair.",
    [
      [
        { n: 4, connections: [[0, 1], [1, 2], [2, 0], [1, 3]] },
        [
          [1, 3],
        ],
        false,
      ],
      [{ n: 2, connections: [[0, 1]] }, [[0, 1]], false],
      [{ n: 3, connections: [[0, 1], [1, 2], [2, 0]] }, [], true],
      [{ n: 5, connections: [[1, 0], [2, 0], [3, 2], [4, 2], [4, 3]] }, [[0, 1]], true],
    ],
    { time: "O(V+E)", space: "O(V+E)" },
  ],
  [
    "bulk-038",
    "Number of Distinct Islands",
    "medium",
    ["matrix", "dfs", "hashing"],
    "def num_distinct_islands(grid):",
    "`grid` list of strings `1` land `0` water. Two islands are same shape if identical up to translation. Return count of distinct shapes.",
    [
      [{ grid: ["11000", "11000", "00011", "00011"] }, 1, false],
      [{ grid: ["11011", "00000", "11011"] }, 2, false],
      [{ grid: ["1"] }, 1, true],
      [{ grid: ["10", "01"] }, 2, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-039",
    "Longest Increasing Path in a Matrix",
    "hard",
    ["matrix", "dfs", "dynamic programming"],
    "def longest_increasing_path(matrix):",
    "`matrix` is list of equal-length lists of ints. Return longest strictly increasing path length in 4 directions.",
    [
      [{ matrix: [[9, 9, 4], [6, 6, 8], [2, 1, 1]] }, 4, false],
      [{ matrix: [[3, 4, 5], [3, 2, 6], [2, 2, 1]] }, 4, false],
      [{ matrix: [[1]] }, 1, true],
      [{ matrix: [[7, 7], [7, 7]] }, 1, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-040",
    "Word Ladder",
    "hard",
    ["graph", "bfs"],
    "def ladder_length(begin_word, end_word, word_list):",
    "Return length of shortest transformation sequence from `begin_word` to `end_word` changing one letter at a time, each step must be in `word_list` (end must be in list). If impossible return 0.",
    [
      [
        {
          begin_word: "hit",
          end_word: "cog",
          word_list: ["hot", "dot", "dog", "lot", "log", "cog"],
        },
        5,
        false,
      ],
      [{ begin_word: "hit", end_word: "cog", word_list: ["hot", "dot", "dog", "lot", "log"] }, 0, false],
      [{ begin_word: "a", end_word: "c", word_list: ["a", "b", "c"] }, 2, true],
      [{ begin_word: "same", end_word: "same", word_list: ["same"] }, 1, true],
    ],
    { time: "O(N * L^2)", space: "O(N)" },
  ],
  [
    "bulk-041",
    "Longest Consecutive Sequence",
    "medium",
    ["arrays", "hashing"],
    "def longest_consecutive(nums):",
    "Return length of longest consecutive elements sequence (values, not indices). O(n) expected.",
    [
      [{ nums: [100, 4, 200, 1, 3, 2] }, 4, false],
      [{ nums: [0, 3, 7, 2, 5, 8, 4, 6, 0, 1] }, 9, false],
      [{ nums: [] }, 0, true],
      [{ nums: [1, 2, 0, 1] }, 3, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-042",
    "Subarray Sum Equals K",
    "medium",
    ["arrays", "hashing", "prefix sum"],
    "def subarray_sum(nums, k):",
    "Return number of continuous subarrays whose sum equals `k`.",
    [
      [{ nums: [1, 1, 1], k: 2 }, 2, false],
      [{ nums: [1, 2, 3], k: 3 }, 2, false],
      [{ nums: [1], k: 0 }, 0, true],
      [{ nums: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], k: 0 }, 55, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-043",
    "Continuous Subarray Sum",
    "medium",
    ["arrays", "hashing", "math"],
    "def check_subarray_sum(nums, k):",
    "Return `True` if `nums` has a subarray of length at least 2 whose sum is a multiple of `k` (when k!=0, modulo k == 0; when k==0, sum==0).",
    [
      [{ nums: [23, 2, 4, 6, 7], k: 6 }, true, false],
      [{ nums: [23, 2, 6, 4, 7], k: 6 }, true, false],
      [{ nums: [23, 2, 6, 4, 7], k: 13 }, false, true],
      [{ nums: [0, 0], k: 1 }, true, true],
    ],
    { time: "O(n)", space: "O(min(n,k))" },
  ],
  [
    "bulk-044",
    "Find the Duplicate Number",
    "medium",
    ["arrays", "two pointers", "binary search"],
    "def find_duplicate(nums):",
    "`nums` length n+1 contains ints in `[1,n]` with exactly one duplicate. Return the duplicate value.",
    [
      [{ nums: [1, 3, 4, 2, 2] }, 2, false],
      [{ nums: [3, 1, 3, 4, 2] }, 3, false],
      [{ nums: [1, 1, 2] }, 1, true],
      [{ nums: [2, 2, 2, 2] }, 2, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-045",
    "Set Matrix Zeroes",
    "medium",
    ["matrix"],
    "def set_zeroes(matrix):",
    "`matrix` is list of equal-length lists of ints. If cell is 0, set its whole row and column to 0 in-place. Return the modified matrix.",
    [
      [
        { matrix: [[1, 1, 1], [1, 0, 1], [1, 1, 1]] },
        [
          [1, 0, 1],
          [0, 0, 0],
          [1, 0, 1],
        ],
        false,
      ],
      [{ matrix: [[0, 1, 2, 0], [3, 4, 5, 2], [1, 3, 1, 5]] }, [[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]], false],
      [{ matrix: [[1]] }, [[1]], true],
      [{ matrix: [[0], [1]] }, [[0], [0]], true],
    ],
    { time: "O(m n)", space: "O(1)" },
  ],
  [
    "bulk-046",
    "Spiral Matrix",
    "medium",
    ["matrix", "simulation"],
    "def spiral_order(matrix):",
    "Return elements of `matrix` (list of equal-length lists) in clockwise spiral order.",
    [
      [{ matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] }, [1, 2, 3, 6, 9, 8, 7, 4, 5], false],
      [{ matrix: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] }, [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7], false],
      [{ matrix: [[7]] }, [7], true],
      [{ matrix: [[1, 2], [3, 4]] }, [1, 2, 4, 3], true],
    ],
    { time: "O(m n)", space: "O(1)" },
  ],
  [
    "bulk-047",
    "Rotate Image",
    "medium",
    ["matrix"],
    "def rotate(matrix):",
    "Rotate `n x n` matrix 90 degrees clockwise in-place. Return the rotated matrix.",
    [
      [
        {
          matrix: [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
          ],
        },
        [
          [7, 4, 1],
          [8, 5, 2],
          [9, 6, 3],
        ],
        false,
      ],
      [
        {
          matrix: [
            [5, 1, 9, 11],
            [2, 4, 8, 10],
            [13, 3, 6, 7],
            [15, 14, 12, 16],
          ],
        },
        [
          [15, 13, 2, 5],
          [14, 3, 4, 1],
          [12, 6, 8, 9],
          [16, 7, 10, 11],
        ],
        false,
      ],
      [{ matrix: [[1]] }, [[1]], true],
      [{ matrix: [[1, 2], [3, 4]] }, [[3, 1], [4, 2]], true],
    ],
    { time: "O(n^2)", space: "O(1)" },
  ],
  [
    "bulk-048",
    "Word Search II",
    "hard",
    ["trie", "backtracking"],
    "def find_words(board, words):",
    "`board` list of strings; `words` list of strings. Return all words from `words` found in board (same rules as Word Search), sorted lexicographically, each unique once.",
    [
      [
        {
          board: ["oaan", "etae", "ihkr", "iflv"],
          words: ["oath", "pea", "eat", "rain"],
        },
        ["eat", "oath"],
        false,
      ],
      [{ board: ["ab", "cd"], words: ["ab", "cd", "ac"] }, ["ab", "ac", "cd"], false],
      [{ board: ["a"], words: ["a", "b"] }, ["a"], true],
      [{ board: ["ab", "cd"], words: [] }, [], true],
    ],
    { time: "O(m n * 4^L)", space: "O(AL)" },
  ],
  [
    "bulk-049",
    "Surrounded Regions",
    "medium",
    ["matrix", "dfs"],
    "def solve(board):",
    "`board` list of strings `X` and `O`. Capture surrounded `O` regions (flip to `X`) except those touching border. Return modified board as list of strings.",
    [
      [
        {
          board: ["XXXX", "XOOX", "XXOX", "XOXX"],
        },
        ["XXXX", "XXXX", "XXXX", "XOXX"],
        false,
      ],
      [{ board: ["X"] }, ["X"], false],
      [{ board: ["OO", "OO"] }, ["OO", "OO"], true],
      [{ board: ["OX", "XO"] }, ["OX", "XO"], true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-050",
    "Number of Enclaves",
    "medium",
    ["matrix", "dfs"],
    "def num_enclaves(grid):",
    "`grid` list of strings `1` land `0` water. Land not 4-connected to boundary is enclave. Return count of enclave land cells.",
    [
      [{ grid: ["000", "010", "000"] }, 0, false],
      [{ grid: ["0", "0", "0", "1"] }, 1, false],
      [{ grid: ["11", "11"] }, 0, true],
      [{ grid: ["100", "110", "010"] }, 1, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-051",
    "House Robber",
    "medium",
    ["arrays", "dynamic programming"],
    "def rob(nums):",
    "Non-adjacent houses max money sum on linear street.",
    [
      [{ nums: [1, 2, 3, 1] }, 4, false],
      [{ nums: [2, 7, 9, 3, 1] }, 12, false],
      [{ nums: [5] }, 5, true],
      [{ nums: [2, 1, 1, 2] }, 4, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-052",
    "House Robber II",
    "medium",
    ["arrays", "dynamic programming"],
    "def rob_circular(nums):",
    "Houses in circle (first and last adjacent). Return max non-adjacent sum.",
    [
      [{ nums: [2, 3, 2] }, 3, false],
      [{ nums: [1, 2, 3, 1] }, 4, false],
      [{ nums: [1] }, 1, true],
      [{ nums: [1, 2, 3] }, 3, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-053",
    "Decode Ways",
    "medium",
    ["strings", "dynamic programming"],
    "def num_decodings(s):",
    "String of digits `1-9` and `0`; letters `A=1`..`Z=26`. Count ways to decode whole string.",
    [
      [{ s: "12" }, 2, false],
      [{ s: "226" }, 3, false],
      [{ s: "06" }, 0, true],
      [{ s: "10" }, 1, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-054",
    "Unique Paths",
    "medium",
    ["math", "dynamic programming"],
    "def unique_paths(m, n):",
    "Robot top-left to bottom-right only right/down on `m x n` grid. Return number of paths.",
    [
      [{ m: 3, n: 7 }, 28, false],
      [{ m: 3, n: 2 }, 3, false],
      [{ m: 1, n: 1 }, 1, true],
      [{ m: 10, n: 10 }, 48620, true],
    ],
    { time: "O(min(m,n))", space: "O(1)" },
  ],
  [
    "bulk-055",
    "Unique Paths II",
    "medium",
    ["matrix", "dynamic programming"],
    "def unique_paths_with_obstacles(obstacle_grid):",
    "`obstacle_grid` list of lists 0 free 1 obstacle. Paths from top-left to bottom-right moving right/down.",
    [
      [{ obstacle_grid: [[0, 0, 0], [0, 1, 0], [0, 0, 0]] }, 2, false],
      [{ obstacle_grid: [[0, 1], [0, 0]] }, 1, false],
      [{ obstacle_grid: [[1]] }, 0, true],
      [{ obstacle_grid: [[0]] }, 1, true],
    ],
    { time: "O(m n)", space: "O(n)" },
  ],
  [
    "bulk-056",
    "Longest Common Subsequence",
    "medium",
    ["strings", "dynamic programming"],
    "def longest_common_subsequence(text1, text2):",
    "Return length of LCS of two strings.",
    [
      [{ text1: "abcde", text2: "ace" }, 3, false],
      [{ text1: "abc", text2: "abc" }, 3, false],
      [{ text1: "abc", text2: "def" }, 0, true],
      [{ text1: "bl", text2: "yby" }, 1, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-057",
    "Edit Distance",
    "hard",
    ["strings", "dynamic programming"],
    "def min_distance(word1, word2):",
    "Minimum operations (insert/delete/replace) to convert `word1` to `word2`.",
    [
      [{ word1: "horse", word2: "ros" }, 3, false],
      [{ word1: "intention", word2: "execution" }, 5, false],
      [{ word1: "", word2: "a" }, 1, true],
      [{ word1: "a", word2: "a" }, 0, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-058",
    "Burst Balloons",
    "hard",
    ["arrays", "dynamic programming"],
    "def max_coins(nums):",
    "Burst balloons to maximize coins: when bursting `i`, gain `nums[i-1]*nums[i]*nums[i+1]`; treat out-of-range as 1.",
    [
      [{ nums: [3, 1, 5, 8] }, 167, false],
      [{ nums: [1, 5] }, 10, false],
      [{ nums: [8] }, 8, true],
      [{ nums: [1, 2, 3] }, 12, true],
    ],
    { time: "O(n^3)", space: "O(n^2)" },
  ],
  [
    "bulk-059",
    "Regular Expression Matching",
    "hard",
    ["strings", "dynamic programming"],
    "def is_match(s, p):",
    "Full regex match: `.` any char, `*` zero+ of preceding element.",
    [
      [{ s: "aa", p: "a" }, false, false],
      [{ s: "aa", p: "a*" }, true, false],
      [{ s: "ab", p: ".*" }, true, true],
      [{ s: "aab", p: "c*a*b" }, true, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-060",
    "Wildcard Matching",
    "hard",
    ["strings", "dynamic programming", "greedy"],
    "def is_match_wildcard(s, p):",
    "`?` matches one char, `*` matches any sequence including empty.",
    [
      [{ s: "aa", p: "a" }, false, false],
      [{ s: "aa", p: "*" }, true, false],
      [{ s: "cb", p: "?a" }, false, true],
      [{ s: "adceb", p: "*a*b" }, true, true],
    ],
    { time: "O(m n)", space: "O(1)" },
  ],
  [
    "bulk-061",
    "Coin Change",
    "medium",
    ["arrays", "dynamic programming"],
    "def coin_change(coins, amount):",
    "Fewest coins to make `amount` with unlimited each coin, or `-1` if impossible.",
    [
      [{ coins: [1, 2, 5], amount: 11 }, 3, false],
      [{ coins: [2], amount: 3 }, -1, false],
      [{ coins: [1], amount: 0 }, 0, true],
      [{ coins: [1, 3, 4], amount: 6 }, 2, true],
    ],
    { time: "O(amount * len(coins))", space: "O(amount)" },
  ],
  [
    "bulk-062",
    "Coin Change 2",
    "medium",
    ["arrays", "dynamic programming"],
    "def change(amount, coins):",
    "Number of combinations to make `amount` (order of coins does not matter).",
    [
      [{ amount: 5, coins: [1, 2, 5] }, 4, false],
      [{ amount: 3, coins: [2] }, 0, false],
      [{ amount: 0, coins: [1] }, 1, true],
      [{ amount: 4, coins: [1, 2, 3] }, 4, true],
    ],
    { time: "O(amount * len(coins))", space: "O(amount)" },
  ],
  [
    "bulk-063",
    "Partition Equal Subset Sum",
    "medium",
    ["arrays", "dynamic programming"],
    "def can_partition(nums):",
    "Return whether array can be partitioned into two subsets with equal sum.",
    [
      [{ nums: [1, 5, 11, 5] }, true, false],
      [{ nums: [1, 2, 3, 5] }, false, false],
      [{ nums: [2, 2, 1, 1] }, true, true],
      [{ nums: [1] }, false, true],
    ],
    { time: "O(n * sum)", space: "O(sum)" },
  ],
  [
    "bulk-064",
    "Target Sum",
    "medium",
    ["arrays", "dynamic programming"],
    "def find_target_sum_ways(nums, target):",
    "Assign `+` or `-` before each number; count ways expression equals `target`.",
    [
      [{ nums: [1, 1, 1, 1, 1], target: 3 }, 5, false],
      [{ nums: [1], target: 1 }, 1, false],
      [{ nums: [1], target: 2 }, 0, true],
      [{ nums: [0, 0, 0, 0, 0, 0, 0, 0, 1], target: 1 }, 256, true],
    ],
    { time: "O(n * range)", space: "O(range)" },
  ],
  [
    "bulk-065",
    "Longest Increasing Subsequence",
    "medium",
    ["arrays", "binary search", "dynamic programming"],
    "def length_of_lis(nums):",
    "Return length of longest strictly increasing subsequence.",
    [
      [{ nums: [10, 9, 2, 5, 3, 7, 101, 18] }, 4, false],
      [{ nums: [0, 1, 0, 3, 2, 3] }, 4, false],
      [{ nums: [7, 7, 7] }, 1, true],
      [{ nums: [1, 3, 6, 7, 9, 4, 10, 5, 6] }, 6, true],
    ],
    { time: "O(n log n)", space: "O(n)" },
  ],
  [
    "bulk-066",
    "Longest String Chain",
    "medium",
    ["strings", "dynamic programming", "hashing"],
    "def longest_str_chain(words):",
    "Words distinct. Chain: each word after predecessor formed by inserting exactly one char anywhere. Return max chain length.",
    [
      [{ words: ["a", "b", "ba", "bca", "bda", "bdca"] }, 4, false],
      [{ words: ["xbc", "pcxbcf", "xb", "cxbc", "pcxbc"] }, 5, false],
      [{ words: ["abcd"] }, 1, true],
      [{ words: ["a", "ab", "ac", "bd"] }, 2, true],
    ],
    { time: "O(n * L^2)", space: "O(n)" },
  ],
  [
    "bulk-067",
    "Best Time to Buy and Sell Stock with Cooldown",
    "medium",
    ["arrays", "dynamic programming"],
    "def max_profit_cooldown(prices):",
    "Same as stock series but after sell must cooldown 1 day before buy.",
    [
      [{ prices: [1, 2, 3, 0, 2] }, 3, false],
      [{ prices: [1] }, 0, false],
      [{ prices: [6, 1, 3, 2, 4, 7] }, 7, true],
      [{ prices: [2, 1, 4] }, 3, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-068",
    "Best Time to Buy and Sell Stock III",
    "hard",
    ["arrays", "dynamic programming"],
    "def max_profit_at_most_two(prices):",
    "At most two non-overlapping transactions max profit.",
    [
      [{ prices: [3, 3, 5, 0, 0, 3, 1, 4] }, 6, false],
      [{ prices: [1, 2, 3, 4, 5] }, 4, false],
      [{ prices: [7, 6, 4, 3, 1] }, 0, true],
      [{ prices: [1, 2, 4, 2, 5, 7, 2, 4, 9, 0] }, 13, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-069",
    "Best Time to Buy and Sell Stock IV",
    "hard",
    ["arrays", "dynamic programming"],
    "def max_profit_k_transactions(k, prices):",
    "At most `k` transactions max profit on `prices`.",
    [
      [{ k: 2, prices: [2, 4, 1] }, 2, false],
      [{ k: 2, prices: [3, 2, 6, 5, 0, 3] }, 7, false],
      [{ k: 0, prices: [1, 2] }, 0, true],
      [{ k: 100, prices: [1, 2, 3, 4, 5] }, 4, true],
    ],
    { time: "O(n k)", space: "O(n k)" },
  ],
  [
    "bulk-070",
    "Partition Labels",
    "medium",
    ["strings", "greedy"],
    "def partition_labels(s):",
    "Partition `s` into max parts so each letter appears in at most one part. Return list of part sizes in order.",
    [
      [{ s: "ababcbacadefegdehijhklij" }, [9, 7, 8], false],
      [{ s: "eccbbbbdec" }, [10], false],
      [{ s: "a" }, [1], true],
      [{ s: "abc" }, [1, 1, 1], true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-071",
    "Merge Triplets to Form Target Triplet",
    "medium",
    ["arrays", "greedy"],
    "def merge_triplets(triplets, target):",
    "`triplets` list of `[a,b,c]`. Pick subset (each index independently max) so merged component-wise max equals `target` if possible.",
    [
      [{ triplets: [[2, 5, 3], [1, 8, 4], [1, 2, 1], [1, 2, 1]], target: [2, 5, 3] }, true, false],
      [{ triplets: [[3, 4, 5], [4, 5, 6]], target: [3, 2, 5] }, false, false],
      [{ triplets: [[1, 1, 1]], target: [1, 1, 1] }, true, true],
      [{ triplets: [[2, 3, 4], [5, 6, 7]], target: [5, 6, 7] }, true, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-072",
    "Non-overlapping Intervals",
    "medium",
    ["intervals", "greedy"],
    "def erase_overlap_intervals(intervals):",
    "Minimum intervals to remove so rest non-overlapping (open intervals touching endpoints allowed non-overlap if [a,b] [b,c]?). Use standard LeetCode: intervals closed, overlap if start < prev_end.",
    [
      [{ intervals: [[1, 2], [2, 3], [3, 4], [1, 3]] }, 1, false],
      [{ intervals: [[1, 2], [1, 2], [1, 2]] }, 2, false],
      [{ intervals: [[1, 2], [2, 3]] }, 0, true],
      [{ intervals: [[0, 2], [1, 3], [2, 4], [3, 5], [4, 6]] }, 2, true],
    ],
    { time: "O(n log n)", space: "O(1)" },
  ],
  [
    "bulk-073",
    "Meeting Rooms II",
    "medium",
    ["intervals", "heap"],
    "def min_meeting_rooms(intervals):",
    "Minimum conference rooms for all meetings `intervals` [start,end).",
    [
      [{ intervals: [[0, 30], [5, 10], [15, 20]] }, 2, false],
      [{ intervals: [[7, 10], [2, 4]] }, 1, false],
      [{ intervals: [[1, 5], [8, 9], [8, 9]] }, 2, true],
      [{ intervals: [] }, 0, true],
    ],
    { time: "O(n log n)", space: "O(n)" },
  ],
  [
    "bulk-074",
    "Minimum Platforms",
    "medium",
    ["arrays", "two pointers"],
    "def min_platforms(arrivals, departures):",
    "Trains `arrivals[i]` and `departures[i]` same day times in minutes sorted per problem input. Return min platforms needed (both arrays same length sorted).",
    [
      [
        { arrivals: [900, 940, 950, 1100, 1500, 1800], departures: [910, 1200, 1120, 1130, 1900, 2000] },
        3,
        false,
      ],
      [{ arrivals: [900, 1235], departures: [1100, 1240] }, 1, false],
      [{ arrivals: [1000], departures: [1010] }, 1, true],
      [{ arrivals: [10, 20, 30], departures: [15, 25, 35] }, 1, true],
    ],
    { time: "O(n log n)", space: "O(1)" },
  ],
  [
    "bulk-075",
    "Insert Interval",
    "medium",
    ["intervals"],
    "def insert_interval(intervals, new_interval):",
    "Non-overlapping sorted `intervals`, insert `new_interval` and merge. Return merged sorted list.",
    [
      [
        { intervals: [[1, 3], [6, 9]], new_interval: [2, 5] },
        [
          [1, 5],
          [6, 9],
        ],
        false,
      ],
      [
        {
          intervals: [
            [1, 2],
            [3, 5],
            [6, 7],
            [8, 10],
            [12, 16],
          ],
          new_interval: [4, 8],
        },
        [[1, 2], [3, 10], [12, 16]],
        false,
      ],
      [{ intervals: [], new_interval: [5, 7] }, [[5, 7]], true],
      [{ intervals: [[1, 5]], new_interval: [2, 3] }, [[1, 5]], true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-076",
    "LRU access pattern (hits and misses)",
    "hard",
    ["design", "hashing"],
    "def lru_pattern(cap, keys):",
    "Simulate LRU cache capacity `cap`. Process `keys` in order: each step is access to that key. On miss, insert key (evict LRU if full). Return list of booleans: True if access was hit, False if miss.",
    [
      [{ cap: 2, keys: [1, 2, 1, 3, 2] }, [false, false, true, false, true], false],
      [{ cap: 1, keys: [1, 1, 1] }, [false, true, true], false],
      [{ cap: 2, keys: [1, 2, 3, 1] }, [false, false, false, false], true],
      [{ cap: 3, keys: [1, 2, 3, 4, 1] }, [false, false, false, false, false], true],
    ],
    { time: "O(n)", space: "O(cap)" },
  ],
  [
    "bulk-077",
    "Word Break",
    "medium",
    ["strings", "dynamic programming"],
    "def word_break(s, word_dict):",
    "Return `True` if `s` can be segmented into a space-separated sequence of one or more words from `word_dict` (each word reusable).",
    [
      [{ s: "leetcode", word_dict: ["leet", "code"] }, true, false],
      [{ s: "applepenapple", word_dict: ["apple", "pen"] }, true, false],
      [{ s: "catsandog", word_dict: ["cats", "dog", "sand", "and", "cat"] }, false, true],
      [{ s: "a", word_dict: ["b"] }, false, true],
    ],
    { time: "O(n^2)", space: "O(n)" },
  ],
  [
    "bulk-078",
    "Maximal Square",
    "medium",
    ["matrix", "dynamic programming"],
    "def maximal_square(matrix):",
    "`matrix` is list of lists of 0/1 ints. Return the area of the largest square containing only ones.",
    [
      [
        {
          matrix: [
            [1, 0, 1, 0, 0],
            [1, 0, 1, 1, 1],
            [1, 1, 1, 1, 1],
            [1, 0, 0, 1, 0],
          ],
        },
        4,
        false,
      ],
      [{ matrix: [[0, 1], [1, 0]] }, 1, false],
      [{ matrix: [[0]] }, 0, true],
      [{ matrix: [[1]] }, 1, true],
    ],
    { time: "O(m n)", space: "O(n)" },
  ],
  [
    "bulk-079",
    "Count Sorted Vowel Strings",
    "medium",
    ["math", "dynamic programming"],
    "def count_vowel_strings(n):",
    "Return number of strings of length `n` using vowels `a,e,i,o,u` where vowels are in non-decreasing order (indices).",
    [
      [{ n: 1 }, 5, false],
      [{ n: 2 }, 15, false],
      [{ n: 3 }, 35, true],
      [{ n: 4 }, 70, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-080",
    "Split Array Largest Sum",
    "hard",
    ["arrays", "binary search"],
    "def split_array_largest_sum(nums, m):",
    "Split `nums` into `m` non-empty contiguous subarrays. Minimize the largest sum among these subarrays. Return that minimum possible largest sum.",
    [
      [{ nums: [7, 2, 5, 10, 8], m: 2 }, 18, false],
      [{ nums: [1, 2, 3, 4, 5], m: 2 }, 9, false],
      [{ nums: [1, 4, 4], m: 3 }, 4, true],
      [{ nums: [10], m: 1 }, 10, true],
    ],
    { time: "O(n log S)", space: "O(1)" },
  ],
  [
    "bulk-081",
    "XOR Queries of a Subarray",
    "medium",
    ["arrays", "bit manipulation"],
    "def xor_queries(arr, queries):",
    "For each query `[l,r]` inclusive, return XOR of `arr[l..r]`. Return list in query order.",
    [
      [{ arr: [1, 3, 4, 8], queries: [[0, 1], [1, 2], [0, 3], [3, 3]] }, [2, 7, 14, 8], false],
      [{ arr: [4, 8, 2, 10], queries: [[2, 3], [0, 2]] }, [8, 14], false],
      [{ arr: [5], queries: [[0, 0]] }, [5], true],
      [{ arr: [1, 2], queries: [[0, 0], [1, 1], [0, 1]] }, [1, 2, 3], true],
    ],
    { time: "O(n + q)", space: "O(n)" },
  ],
  [
    "bulk-082",
    "Shifting Letters",
    "medium",
    ["strings", "prefix sum"],
    "def shifting_letters(s, shifts):",
    "`shifts[i]` is how much to shift `s[i]` and all following letters (cumulative after applying all). Each shift wraps within lowercase `a-z`.",
    [
      [{ s: "abc", shifts: [3, 5, 9] }, "rpl", false],
      [{ s: "aaa", shifts: [1, 2, 3] }, "gfd", false],
      [{ s: "z", shifts: [1] }, "a", true],
      [{ s: "ab", shifts: [0, 0] }, "ab", true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-083",
    "ZigZag Conversion",
    "medium",
    ["strings"],
    "def convert(s, num_rows):",
    "Write string `s` in zigzag pattern on `num_rows` rows, then read row by row left-to-right to produce output string.",
    [
      [{ s: "PAYPALISHIRING", num_rows: 3 }, "PAHNAPLSIIGYIR", false],
      [{ s: "PAYPALISHIRING", num_rows: 4 }, "PINALSIGYAHRPI", false],
      [{ s: "A", num_rows: 1 }, "A", true],
      [{ s: "AB", num_rows: 1 }, "AB", true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-084",
    "Number of Tilings",
    "hard",
    ["dynamic programming"],
    "def num_tilings(n):",
    "Count ways to tile a `2 x n` board with `1x2` dominoes and `2x2` tromino shapes (LeetCode 790). Return count modulo `10^9 + 7`.",
    [
      [{ n: 3 }, 5, false],
      [{ n: 1 }, 1, false],
      [{ n: 2 }, 2, true],
      [{ n: 4 }, 11, true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-085",
    "Min Cost to Connect All Points",
    "medium",
    ["graph", "mst", "greedy"],
    "def min_cost_connect_points(points):",
    "`points` is list of `[x,y]` unique points. Return minimum total Manhattan distance to connect all points (complete graph edge weights).",
    [
      [{ points: [[0, 0], [2, 2], [3, 10], [5, 2], [7, 0]] }, 20, false],
      [{ points: [[3, 12], [-2, 5], [-4, 1]] }, 18, false],
      [{ points: [[0, 0]] }, 0, true],
      [{ points: [[0, 0], [1, 1]] }, 2, true],
    ],
    { time: "O(n^2 log n)", space: "O(n)" },
  ],
  [
    "bulk-086",
    "Swim in Rising Water",
    "hard",
    ["matrix", "binary search", "union find"],
    "def swim_in_water(grid):",
    "`grid` is `n x n` list of lists of non-negative ints (rain times). Start top-left at time `t` when cell value <= t; move 4-dir. Return minimum `t` to reach bottom-right.",
    [
      [{ grid: [[0, 2], [1, 3]] }, 3, false],
      [{ grid: [[0, 1, 2, 3, 4], [24, 23, 22, 21, 5], [12, 13, 14, 15, 16], [11, 17, 18, 19, 20], [10, 9, 8, 7, 6]] }, 16, false],
      [{ grid: [[0]] }, 0, true],
      [{ grid: [[3, 2], [0, 1]] }, 3, true],
    ],
    { time: "O(n^2 log n)", space: "O(n^2)" },
  ],
  [
    "bulk-087",
    "Keys and Rooms",
    "medium",
    ["graph", "dfs"],
    "def can_visit_all_rooms(rooms):",
    "`rooms` is list of lists: from room `i` keys go to `rooms[i]`. Start with room 0 unlocked. Return whether all rooms can be visited.",
    [
      [{ rooms: [[1], [2], [3], []] }, true, false],
      [{ rooms: [[1, 3], [3, 0, 1], [2], [0]] }, true, false],
      [{ rooms: [[1], []] }, false, true],
      [{ rooms: [[0]] }, true, true],
    ],
    { time: "O(n + e)", space: "O(n)" },
  ],
  [
    "bulk-088",
    "Shortest Distance to a Character",
    "medium",
    ["strings", "two pointers"],
    "def shortest_to_char(s, c):",
    "Return list of distances from each index in `s` to nearest occurrence of character `c`.",
    [
      [{ s: "loveleetcode", c: "e" }, [3, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 0], false],
      [{ s: "aaab", c: "b" }, [3, 2, 1, 0], false],
      [{ s: "a", c: "a" }, [0], true],
      [{ s: "ababa", c: "b" }, [1, 0, 1, 0, 1], true],
    ],
    { time: "O(n)", space: "O(1)" },
  ],
  [
    "bulk-089",
    "Shortest Path in Binary Matrix",
    "medium",
    ["matrix", "bfs"],
    "def shortest_path_binary_matrix(grid):",
    "`grid` is `n x n` list of lists 0/1. Find shortest clear path from top-left to bottom-right moving 8-directionally through 0 cells only. Return length (cells count) or `-1`.",
    [
      [{ grid: [[0, 1], [1, 0]] }, -1, false],
      [{ grid: [[0, 0, 0], [1, 1, 0], [1, 1, 0]] }, 4, false],
      [{ grid: [[0]] }, 1, true],
      [{ grid: [[1]] }, -1, true],
    ],
    { time: "O(n^2)", space: "O(n^2)" },
  ],
  [
    "bulk-090",
    "Minimum Genetic Mutation",
    "medium",
    ["graph", "bfs"],
    "def min_mutation(start, end, bank):",
    "Gene string length 8 of A,C,G,T. One mutation changes one character; must be in `bank` to be valid intermediate. Return min mutations from `start` to `end`, or `-1`.",
    [
      [{ start: "AACCGGTT", end: "AACCGGTA", bank: ["AACCGGTA"] }, 1, false],
      [{ start: "AACCGGTT", end: "AAACGGTA", bank: ["AACCGGTA", "AACCGCTA", "AAACGGTA"] }, 2, false],
      [{ start: "AAAAACCC", end: "AACCCCCC", bank: ["AAAACCCC", "AAACCCCC", "AACCCCCC"] }, 3, true],
      [{ start: "AAAAAAAA", end: "CCCCCCCC", bank: ["AAAAAAAA", "AAAAAAAC", "AAAACCAA", "AACCCCCC", "ACCCCCCC", "CCCCCCCC"] }, -1, true],
    ],
    { time: "O(n * bank)", space: "O(bank)" },
  ],
  [
    "bulk-091",
    "Open the Lock",
    "hard",
    ["graph", "bfs"],
    "def open_lock(deadends, target):",
    "4-wheel lock `0000` to `9999` strings; each move increments/decrements one wheel by 1 (with wrap). `deadends` cannot be visited. Return min moves to reach `target`, or `-1`.",
    [
      [{ deadends: ["0201", "0101", "0102", "1212", "2002"], target: "0202" }, 6, false],
      [{ deadends: ["8888"], target: "0009" }, 1, false],
      [{ deadends: ["8887", "8889", "8878", "8898", "8788", "8988", "7888", "9888"], target: "8888" }, -1, true],
      [{ deadends: [], target: "0000" }, 0, true],
    ],
    { time: "O(10^4)", space: "O(10^4)" },
  ],
  [
    "bulk-092",
    "Rotting Oranges (minutes variant)",
    "medium",
    ["matrix", "bfs"],
    "def oranges_rotting_minutes(grid):",
    "Same as rotting oranges: return minutes until no fresh orange remains, or `-1` if impossible.",
    [
      [{ grid: ["23", "12"] }, 1, false],
      [{ grid: ["11", "11", "00"] }, -1, false],
      [{ grid: ["0"] }, 0, true],
      [{ grid: ["22", "11", "11"] }, 2, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-093",
    "Pacific Atlantic Water Flow (variant check)",
    "medium",
    ["matrix", "dfs"],
    "def count_pacific_atlantic(heights):",
    "Same grid rules as Pacific/Atlantic flow. Return **count** of cells that can reach both oceans (4-direction, non-increasing height).",
    [
      [
        {
          heights: [
            [1, 2, 2, 3, 5],
            [3, 2, 3, 4, 4],
            [2, 4, 5, 3, 1],
            [6, 7, 1, 4, 5],
            [5, 1, 1, 2, 4],
          ],
        },
        7,
        false,
      ],
      [{ heights: [[1]] }, 1, false],
      [{ heights: [[1, 1], [1, 1]] }, 4, true],
      [{ heights: [[2, 2], [2, 2]] }, 4, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
  [
    "bulk-094",
    "Binary Tree Maximum Path Sum (on parent array)",
    "hard",
    ["trees", "dynamic programming"],
    "def max_path_sum_parent(parent, values):",
    "Hidden rooted tree: `parent[i]` is parent of `i` (-1 for root). `values[i]` is node weight. Return max path sum over any connected path in tree (may or may not pass through root).",
    [
      [{ parent: [-1, 0, 0, 2, 2], values: [1, 2, 3, 4, 5] }, 12, false],
      [{ parent: [-1, 0], values: [-10, 9] }, 9, false],
      [{ parent: [-1], values: [5] }, 5, true],
      [{ parent: [-1, 0, 1], values: [1, -2, 3] }, 3, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-095",
    "Redundant Connection",
    "medium",
    ["graph", "union find"],
    "def find_redundant_connection(edges):",
    "Undirected tree with one extra edge. Return the edge `[u,v]` that can be removed to make a tree; if multiple, return the last in `edges` order.",
    [
      [{ edges: [[1, 2], [1, 3], [2, 3]] }, [2, 3], false],
      [{ edges: [[1, 2], [2, 3], [3, 4], [1, 4], [1, 5]] }, [1, 4], false],
      [{ edges: [[1, 2], [1, 3], [2, 4], [3, 4]] }, [3, 4], true],
      [{ edges: [[1, 2], [2, 3], [3, 1]] }, [3, 1], true],
    ],
    { time: "O(n α(n))", space: "O(n)" },
  ],
  [
    "bulk-096",
    "Evaluate Reverse Polish Notation",
    "medium",
    ["stack", "arrays"],
    "def eval_rpn(tokens):",
    "`tokens` is postfix expression using integers and `+ - * /` operators. Return integer value (division truncates toward zero).",
    [
      [{ tokens: ["2", "1", "+", "3", "*"] }, 9, false],
      [{ tokens: ["4", "13", "5", "/", "+"] }, 6, false],
      [{ tokens: ["10", "6", "9", "3", "+", "-11", "*", "/", "*", "17", "+", "5", "+"] }, 22, true],
      [{ tokens: ["18", "6", "-", "7", "*"] }, 84, true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-097",
    "Simplify Path",
    "medium",
    ["strings", "stack"],
    "def simplify_path(path):",
    "Unix absolute path string: normalize `.`, `..`, multiple slashes. Return canonical path starting with `/`.",
    [
      [{ path: "/home/" }, "/home", false],
      [{ path: "/../" }, "/", false],
      [{ path: "/home//foo/" }, "/home/foo", true],
      [{ path: "/a/./b/../../c/" }, "/c", true],
    ],
    { time: "O(n)", space: "O(n)" },
  ],
  [
    "bulk-098",
    "Integer to English Words",
    "hard",
    ["math", "strings"],
    "def number_to_words(num):",
    "Convert non-negative integer `num` (< 2^31) to English words in Title Case with single spaces, no trailing space.",
    [
      [{ num: 123 }, "One Hundred Twenty Three", false],
      [{ num: 1000000 }, "One Million", false],
      [{ num: 0 }, "Zero", true],
      [{ num: 508 }, "Five Hundred Eight", true],
    ],
    { time: "O(log n)", space: "O(1)" },
  ],
  [
    "bulk-099",
    "Median Finder stream (final median)",
    "hard",
    ["heap", "design"],
    "def median_from_stream(values):",
    "Process `values` in order as insertions into a multiset. After each insertion the median is defined as lower middle for even count. Return the **median after the last** insertion (single number).",
    [
      [{ values: [1, 2, 3] }, 2, false],
      [{ values: [6, 10, 2, 6, 5] }, 6, false],
      [{ values: [1] }, 1, true],
      [{ values: [1, 2] }, 1, true],
    ],
    { time: "O(n log n)", space: "O(n)" },
  ],
  [
    "bulk-100",
    "Minimum Cost to Make at Least One Valid Path in a Grid",
    "hard",
    ["graph", "bfs", "0-1 bfs"],
    "def min_cost_grid(grid):",
    "`grid` is list of strings of digits `1-4` meaning arrow right/down/left/up from that cell. Changing a cell direction costs 1. Start `(0,0)` end `(m-1,n-1)` following arrows. Return minimum cost.",
    [
      [{ grid: ["12", "21"] }, 1, false],
      [{ grid: ["1111", "1111", "1111"] }, 0, false],
      [{ grid: ["1"] }, 0, true],
      [{ grid: ["13", "22"] }, 1, true],
    ],
    { time: "O(m n)", space: "O(m n)" },
  ],
];

async function main() {
  const docs = RAW.map(([idSuffix, title, diff, topics, sig, question, cases, complexity]) =>
    doc(`striver-sde-sheet-${idSuffix}`, title, question, diff, topics, sig, cases, complexity)
  );
  await fs.mkdir(OUT_DIR, { recursive: true });
  for (let part = 0; part < 5; part++) {
    const slice = docs.slice(part * 20, part * 20 + 20);
    const outPath = path.join(OUT_DIR, `bulk-part-0${part + 1}.json`);
    await fs.writeFile(outPath, JSON.stringify(slice, null, 2), "utf8");
    console.log("wrote", outPath, slice.length);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});