export const EXECUTION_SUCCESS = "EXECUTION_SUCCESS";
export const EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT";
export const EXECUTION_ERROR = "EXECUTION_ERROR";
export const EXECUTION_RUNTIME_ERROR = "EXECUTION_RUNTIME_ERROR";
export const EXECUTION_COMPILATION_ERROR = "EXECUTION_COMPILATION_ERROR";

export default {
  EXECUTION_SUCCESS,
  EXECUTION_TIMEOUT,
  EXECUTION_ERROR,
  EXECUTION_RUNTIME_ERROR,
  EXECUTION_COMPILATION_ERROR,
};
